### ISSUE TITLE
Rerendering qt from command line fails with error including a strange path

### ISSUE THREAD

**Issue by croth1** [conda-forge/conda-smithy#1008]
I tried rerendering the qt feedstock from command line and I am getting following error:

```
Traceback (most recent call last):
  File "/Users/christian/miniconda3/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/Users/christian/miniconda3/lib/python3.6/site-packages/conda_smithy/cli.py", line 424, in main
    args.subcommand_func(args)
  File "/Users/christian/miniconda3/lib/python3.6/site-packages/conda_smithy/cli.py", line 292, in __call__
    exclusive_config_file=args.exclusive_config_file,
  File "/Users/christian/miniconda3/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 1337, in main
    render_circle(env, config, forge_dir)
  File "/Users/christian/miniconda3/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 848, in render_circle
    upload_packages=upload_packages,
  File "/Users/christian/miniconda3/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 521, in _render_ci_provider
    channel_urls=forge_config.get("channels", {}).get("sources", []),
  File "/Users/christian/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 44, in render
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/Users/christian/miniconda3/lib/python3.6/site-packages/conda_build/render.py", line 784, in render_recipe
    m.config.compute_build_id(m.name(), reset=reset_build_id)
  File "/Users/christian/miniconda3/lib/python3.6/site-packages/conda_build/config.py", line 529, in compute_build_id
    old_dir = self.work_dir if len(os.listdir(self.work_dir)) > 0 else ""
FileNotFoundError: [Errno 2] No such file or directory: '/home/conda/feedstock_root/build_artifacts/work'
```

**Comment by isuruf** [comment]
This looks like a conda-build issue

**Comment by croth1** [comment]
It seems to be a conda issue; conda-build gets the wrong path from conda.base.context.
