### ISSUE TITLE
Inconsistent versioning scheme

### ISSUE THREAD

**Issue by vyasr** [conda-forge/conda-smithy#1010]
The most recent version of conda-smithy seems to have changed the versioning scheme, adding a 'v' to the version. This breaks conda's expected versioning scheme, because it tries to compare version v3.2.11 to 3.2.11 and thinks that they aren't equal.

Here's the traceback:
```
Traceback (most recent call last):
  File "/Users/vramasub/miniconda3/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/Users/vramasub/miniconda3/lib/python3.6/site-packages/conda_smithy/cli.py", line 424, in main
    args.subcommand_func(args)
  File "/Users/vramasub/miniconda3/lib/python3.6/site-packages/conda_smithy/cli.py", line 292, in __call__
    exclusive_config_file=args.exclusive_config_file,
  File "/Users/vramasub/miniconda3/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 1300, in main
    check_version_uptodate(r, "conda-smithy", __version__, error_on_warn)
  File "/Users/vramasub/miniconda3/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 1224, in check_version_uptodate
    raise RuntimeError("{} Exiting.".format(msg))
RuntimeError: conda-smithy version in root env (v3.2.11) is out-of-date (3.2.12). Exiting.
```

I originally raised this issue with conda, so you can find more information on conda/conda#8194.

**Comment by scopatz** [comment]
This was accidental, and 3.2.11 should not be used.  Please install 3.2.12

**Comment by vyasr** [comment]
Got it, thanks!
