### ISSUE TITLE
Automatic checks fail, conda-smithy fails with Response304ContentUnchanged

### ISSUE THREAD

**Issue by senarvi** [conda-forge/conda-smithy#1017]
After creating a new release in PyPI, cf-regro-autotick-bot creates an automatic [merge request](https://github.com/conda-forge/theanolm-feedstock/pull/4), but the AppVeyor and Travis builds fail. The problem is, they try to access "branch2.0" of conda-forge-ci-setup-feedstock:

https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py

Apparently they get the URL from .appveyor.yml and .travis.yml. I tried running `conda smithy rerender` to regenerate those files, but it gives me the following error message:

```
Traceback (most recent call last):
  File ".../lib/python3.7/site-packages/conda/core/subdir_data.py", line 218, in _load
    mod_etag_headers.get('_mod'))
  File ".../lib/python3.7/site-packages/conda/core/subdir_data.py", line 538, in fetch_repodata_remote_request
    raise Response304ContentUnchanged()
conda.core.subdir_data.Response304ContentUnchanged

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File ".../lib/python3.7/site-packages/conda_smithy/cli.py", line 424, in main
    args.subcommand_func(args)
  File ".../lib/python3.7/site-packages/conda_smithy/cli.py", line 292, in __call__
    exclusive_config_file=args.exclusive_config_file,
  File ".../lib/python3.7/site-packages/conda_smithy/configure_feedstock.py", line 1315, in main
    index = conda_build.conda_interface.get_index(channel_urls=["conda-forge"])
  File ".../lib/python3.7/site-packages/conda/exports.py", line 243, in get_index
    index = _get_index(channel_urls, prepend, platform, use_local, use_cache, unknown, prefix)
  File ".../lib/python3.7/site-packages/conda/common/io.py", line 85, in decorated
    return f(*args, **kwds)
  File ".../lib/python3.7/site-packages/conda/core/index.py", line 58, in get_index
    index = fetch_index(channel_urls, use_cache=use_cache)
  File ".../lib/python3.7/site-packages/conda/core/index.py", line 74, in fetch_index
    index.update((rec, rec) for rec in sd.iter_records())
  File ".../lib/python3.7/site-packages/conda/core/subdir_data.py", line 167, in iter_records
    self.load()
  File ".../lib/python3.7/site-packages/conda/core/subdir_data.py", line 147, in load
    _internal_state = self._load()
  File ".../lib/python3.7/site-packages/conda/core/subdir_data.py", line 224, in _load
    mod_etag_headers.get('_mod'))
  File ".../lib/python3.7/site-packages/conda/core/subdir_data.py", line 271, in _read_local_repdata
    _internal_state = self._process_raw_repodata_str(raw_repodata_str)
  File ".../lib/python3.7/site-packages/conda/core/subdir_data.py", line 308, in _process_raw_repodata_str
    json_obj = json.loads(raw_repodata_str or '{}')
  File ".../lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File ".../lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File ".../lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 76046 column 34 (char 2293760)
```

**Comment by senarvi** [comment]
After one year I tried again with the latest conda-smithy and it worked! :P
