### ISSUE TITLE
Rerender fails on Windows with git problem

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-smithy#1107]
Using the most recent `conda`, `conda-build` and `conda-smithy`, calling `conda smithy rerender -c auto` fails on Windows with a git problem (trying to create `index.lock` twice?):
```
[...]
INFO conda_build.variants:_combine_spec_dictionaries(189): Adding in variants from C:\ProgramData\Miniconda3\envs\builder\conda_build_config.yaml
top_level_loop_vars {'python', 'cxx_compiler', 'c_compiler'}
used_key_values OrderedDict([('channel_targets', ['conda-forge main']), ('channel_sources', ['conda-forge,defaults']), ('c_compiler', ('vs2015', 'vs2015', 'vs2008')), ('cxx_compiler', ('vs2015', 'vs2015', 'vs2008')), ('python', ('3.6', '3.7', '2.7')), ('pin_run_as_build', {'python': {'min_pin': 'x.x', 'max_pin': 'x.x'}}), ('zip_keys', [['python', 'c_compiler', 'cxx_compiler']])])
top_level_loop_vars {'python'}
used_key_values OrderedDict([('c_compiler_version', ['7']), ('c_compiler', ['gcc']), ('python', ['2.7', '3.6', '3.7']), ('cxx_compiler_version', ['7']), ('channel_targets', ['conda-forge main']), ('cxx_compiler', ['gxx']), ('channel_sources', ['conda-forge,defaults']), ('docker_image', ['condaforge/linux-anvil-comp7']), ('pin_run_as_build', {'python': {'min_pin': 'x.x', 'max_pin': 'x.x'}})])
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\builder\Scripts\conda-smithy-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\ProgramData\Miniconda3\envs\builder\lib\site-packages\conda_smithy\cli.py", line 485, in main
    args.subcommand_func(args)
  File "C:\ProgramData\Miniconda3\envs\builder\lib\site-packages\conda_smithy\cli.py", line 353, in __call__
    check=args.check
  File "C:\ProgramData\Miniconda3\envs\builder\lib\site-packages\conda_smithy\configure_feedstock.py", line 1449, in main
    render_azure(env, config, forge_dir)
  File "C:\ProgramData\Miniconda3\envs\builder\lib\site-packages\conda_smithy\configure_feedstock.py", line 1016, in render_azure
    upload_packages=upload_packages,
  File "C:\ProgramData\Miniconda3\envs\builder\lib\site-packages\conda_smithy\configure_feedstock.py", line 546, in _render_ci_provider
    metas, forge_dir, platform, arch, upload, forge_config
  File "C:\ProgramData\Miniconda3\envs\builder\lib\site-packages\conda_smithy\configure_feedstock.py", line 409, in dump_subspace_config_files
    yaml.dump(config, f, default_flow_style=False)
  File "C:\ProgramData\Miniconda3\envs\builder\lib\contextlib.py", line 119, in __exit__
    next(self.gen)
  File "C:\ProgramData\Miniconda3\envs\builder\lib\site-packages\conda_smithy\feedstock_io.py", line 55, in write_file
    repo.index.add([filename])
  File "C:\ProgramData\Miniconda3\envs\builder\lib\site-packages\git\index\base.py", line 795, in add
    self.write(ignore_extension_data=not write_extension_data)
  File "C:\ProgramData\Miniconda3\envs\builder\lib\site-packages\git\index\base.py", line 214, in write
    lfd.commit()
  File "C:\ProgramData\Miniconda3\envs\builder\lib\site-packages\gitdb\util.py", line 359, in commit
    self._end_writing(successful=True)
  File "C:\ProgramData\Miniconda3\envs\builder\lib\site-packages\gitdb\util.py", line 387, in _end_writing
    os.rename(lockfile, self._filepath)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\[...]\\preshed-feedstock\\.git\\index.lock' -> 'C:\\Users\\[...]\\preshed-feedstock\\.git\\index'
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at C:\ProgramData\Miniconda3\envs\builder:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                py37_1003    conda-forge
beautifulsoup4            4.7.1                 py37_1001    conda-forge
blinker                   1.4                        py_1    conda-forge
bzip2                     1.0.6             hfa6e2cd_1002    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py37_0    conda-forge
cffi                      1.12.3           py37hb32ad35_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
conda                     4.7.5                    py37_0    conda-forge
conda-build               3.18.7                   py37_1    conda-forge
conda-forge-pinning       2019.07.13                    0    conda-forge
conda-package-handling    1.3.11                   py37_0    conda-forge
conda-smithy              3.4.0                      py_1    conda-forge
conda-verify              3.1.1                 py37_1000    conda-forge
cryptography              2.7              py37hb32ad35_0    conda-forge
deprecated                1.2.5                      py_0    conda-forge
filelock                  3.0.10                     py_0    conda-forge
future                    0.17.1                py37_1000    conda-forge
git                       2.22.0                        0    conda-forge
gitdb2                    2.0.5                      py_0    conda-forge
gitpython                 2.1.11                     py_0    conda-forge
glob2                     0.7                        py_0    conda-forge
idna                      2.8                   py37_1000    conda-forge
isodate                   0.6.0                      py_1    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
libarchive                3.3.3             h4890af2_1006    conda-forge
libiconv                  1.15              hfa6e2cd_1005    conda-forge
liblief                   0.9.0                ha925a31_2
libxml2                   2.9.9                h9ce36c8_1    conda-forge
lz4-c                     1.8.3             he025d50_1001    conda-forge
lzo                       2.10              hfa6e2cd_1000    conda-forge
markupsafe                1.1.1            py37hfa6e2cd_0    conda-forge
menuinst                  1.4.16                   py37_0    conda-forge
msrest                    0.6.8                      py_0    conda-forge
oauthlib                  3.0.1                      py_0    conda-forge
openssl                   1.1.1c               hfa6e2cd_0    conda-forge
pip                       19.1.1                   py37_0    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
psutil                    5.6.3            py37hfa6e2cd_0    conda-forge
py-lief                   0.9.0            py37ha925a31_2
pycosat                   0.6.3           py37hfa6e2cd_1001    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pycrypto                  2.6.1           py37hfa6e2cd_1002    conda-forge
pygithub                  1.43.6                   py37_0    conda-forge
pyjwt                     1.7.1                      py_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pysocks                   1.7.0                    py37_0    conda-forge
python                    3.7.3                h510b542_1    conda-forge
python-libarchive-c       2.8                   py37_1004    conda-forge
pytz                      2019.1                     py_0    conda-forge
pywin32                   224             py37hfa6e2cd_1000    conda-forge
pyyaml                    5.1.1            py37hfa6e2cd_0    conda-forge
requests                  2.22.0                   py37_1    conda-forge
requests-oauthlib         1.2.0                      py_0    conda-forge
ruamel                    1.0                      py37_0    conda-forge
ruamel.yaml               0.15.99          py37hfa6e2cd_0    conda-forge
ruamel_yaml               0.15.71         py37hfa6e2cd_1000    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
smmap2                    2.0.5                      py_0    conda-forge
soupsieve                 1.9.2                    py37_0    conda-forge
sqlite                    3.29.0               hfa6e2cd_0    conda-forge
tqdm                      4.32.2                     py_0    conda-forge
urllib3                   1.25.3                   py37_0    conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_4
vsts-python-api           0.1.22                     py_0    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
win_inet_pton             1.1.0                    py37_0    conda-forge
wincertstore              0.2                   py37_1002    conda-forge
wrapt                     1.11.2           py37hfa6e2cd_0    conda-forge
xz                        5.2.4             h2fa13f4_1001    conda-forge
yaml                      0.1.7             hfa6e2cd_1001    conda-forge
zlib                      1.2.11            h2fa13f4_1005    conda-forge
zstd                      1.4.0                hd8a0e53_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : base
    active env location : C:\ProgramData\Miniconda3\envs\builder
            shell level : 1
       user config file : C:\Users\[user]\.condarc
 populated config files : C:\Users\[user]\.condarc
          conda version : 4.7.5
    conda-build version : 3.18.7
         python version : 3.7.3.final.0
       virtual packages :
       base environment : C:\ProgramData\Miniconda3\envs\builder  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Miniconda3\envs\builder\pkgs
                          C:\Users\[user]\.conda\pkgs
                          C:\Users\[user]\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Miniconda3\envs\builder\envs
                          C:\Users\[user]\.conda\envs
                          C:\Users\[user]\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.5 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.17763
          administrator : True
             netrc file : None
           offline mode : False
```
</details>

**Comment by scopatz** [comment]
What recipe is this for?

**Comment by h-vetinari** [comment]
I tried compiling a few of the r-feedstocks locally yesterday (after `@conda-forge-admin` failed at rerendering), essentially all that are requirements of [r-recommended](https://github.com/conda-forge/r-recommended-feedstock/blob/master/recipe/meta.yaml).

I only uploaded 4 PRs (which by now got superseded by the migration), but all but 2 failed with this error when trying `conda smithy rerender` locally.

**Comment by h-vetinari** [comment]
Closing this as outdated/obsolete
