### ISSUE TITLE
Not compatible with ruamel.yaml 0.16

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-smithy#1139]
Fails with,

```
Traceback (most recent call last):

  File "/home/travis/miniconda/bin/conda-smithy", line 10, in <module>

    sys.exit(main())

  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_smithy/cli.py", line 470, in main

    args.subcommand_func(args)

  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_smithy/cli.py", line 217, in __call__

    args.feedstock_directory, owner, repo

  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_smithy/ci_register.py", line 351, in travis_token_update_conda_forge_config

    ] = travis_encrypt_binstar_token(slug, item)

  File "/home/travis/miniconda/lib/python3.7/contextlib.py", line 119, in __exit__

    next(self.gen)

  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_smithy/utils.py", line 92, in update_conda_forge_config

    fh.write(yaml.dump(code))

  File "/home/travis/miniconda/lib/python3.7/site-packages/ruamel/yaml/main.py", line 448, in dump

    raise TypeError('Need a stream argument when not dumping from context manager')

TypeError: Need a stream argument when not dumping from context manager
```

cc @ocefpaf, @scopatz

**Comment by scopatz** [comment]
@conda-forge/core
