### ISSUE TITLE
Empty section is now an error

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#1153]
Appears that adding an empty section ([like `host` in this recipe]( https://github.com/conda-forge/binutils-feedstock/blob/3c4441c34423404d89b5a3652a4eab2f250019b1/recipe/meta.yaml#L25 )) is now an error. Though this is a valid construction for a recipe. Appears this may have been introduced by PR ( https://github.com/conda-forge/conda-smithy/pull/1133 ).

cc @isuruf @scopatz

**Comment by scopatz** [comment]
Should be a simple fix

**Comment by scopatz** [comment]
Do you have the traceback?

**Comment by jakirkham** [comment]
Great! Yep, here you go.

```python
$ conda smithy recipe-lint recipe/
Traceback (most recent call last):
  File "/Users/jkirkham/miniconda/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/Users/jkirkham/miniconda/lib/python3.7/site-packages/conda_smithy/cli.py", line 477, in main
    args.subcommand_func(args)
  File "/Users/jkirkham/miniconda/lib/python3.7/site-packages/conda_smithy/cli.py", line 372, in __call__
    return_hints=True,
  File "/Users/jkirkham/miniconda/lib/python3.7/site-packages/conda_smithy/lint_recipe.py", line 574, in main
    results, hints = lintify(meta, recipe_dir, conda_forge)
  File "/Users/jkirkham/miniconda/lib/python3.7/site-packages/conda_smithy/lint_recipe.py", line 392, in lintify
    for requirement in requirements:
TypeError: 'NoneType' object is not iterable
```
