### ISSUE TITLE
rerender config.variant python is ambiguous on osx-64

### ISSUE THREAD

**Issue by timsnyder** [conda-forge/conda-smithy#1258]
Issue:

I'm trying to rerender make-feedstock on osx-64 using latest released conda smithy, conda build and cf pinnings as a method of testing my changes in #1257 .  I had trouble rerendering and then backed out my changes to the point of starting from a fresh miniconda and rerendering inside a clean docker (of condaforge/linux-anvil-comp7)

I hit the following (slightly enhanced output due to my additional hacking to provide more logging):
```
[I] ✦ ➜ conda smithy rerender
Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
WARNING conda_build.config:platform(304): Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
WARNING conda_build.config:arch(290): Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
config.variant:
{'lua': '5.', 'numpy': '1.11', 'perl': '5.26', 'python': '3.7', 'r_base': '3.5'}
Adding in variants from internal_defaults
INFO conda_build.variants:_combine_spec_dictionaries(190): Adding in variants from internal_defaults
Adding in variants from /Users/timothys/miniconda3/conda_build_config.yaml
INFO conda_build.variants:_combine_spec_dictionaries(190): Adding in variants from /Users/timothys/miniconda3/conda_build_config.yaml
Adding in variants from config.variant
INFO conda_build.variants:_combine_spec_dictionaries(190): Adding in variants from config.variant
Adding in variants from argument_variants
INFO conda_build.variants:_combine_spec_dictionaries(190): Adding in variants from argument_variants
config.variant:
{'lua': '5.', 'numpy': '1.11', 'perl': '5.26', 'python': '3.7', 'r_base': '3.5'}
config.variant:
{'lua': '5.', 'numpy': '1.11', 'perl': '5.26', 'python': '3.7', 'r_base': '3.5'}
config.variant:
{'lua': '5.', 'numpy': '1.11', 'perl': '5.26', 'python': '3.7', 'r_base': '3.5'}
Traceback (most recent call last):
  File "/Users/timothys/miniconda3/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/Users/timothys/miniconda3/lib/python3.7/site-packages/conda_smithy/cli.py", line 554, in main
    args.subcommand_func(args)
  File "/Users/timothys/miniconda3/lib/python3.7/site-packages/conda_smithy/cli.py", line 373, in __call__
    check=args.check,
  File "/Users/timothys/miniconda3/lib/python3.7/site-packages/conda_smithy/configure_feedstock.py", line 1754, in main
    render_azure(env, config, forge_dir, return_metadata=True)
  File "/Users/timothys/miniconda3/lib/python3.7/site-packages/conda_smithy/configure_feedstock.py", line 1147, in render_azure
    return_metadata=return_metadata,
  File "/Users/timothys/miniconda3/lib/python3.7/site-packages/conda_smithy/configure_feedstock.py", line 569, in _render_ci_provider
    os.path.join(forge_dir, "recipe"), config=config
  File "/Users/timothys/miniconda3/lib/python3.7/site-packages/conda_build/variants.py", line 528, in get_package_combined_spec
    combined_spec = combine_specs(specs, log_output=config.verbose)
  File "/Users/timothys/miniconda3/lib/python3.7/site-packages/conda_build/variants.py", line 280, in combine_specs
    log_output=log_output)
  File "/Users/timothys/miniconda3/lib/python3.7/site-packages/conda_build/variants.py", line 255, in _combine_spec_dictionaries
    spec_source, subvalue, k, pprint.pformat(values[k])))
ValueError: variant config in config.variant is ambiguous because it does not fully implement all zipped keys, or specifies a subspace that is not fully implemented. at 3.7 not found for python in:
['2.7.* *_cpython', '3.6.* *_cpython', '3.7.* *_cpython']

```

The print of config.variant was added to [configure_feedstock._render_ci_provider at line 560](https://github.com/conda-forge/conda-smithy/blob/18b0c0da86bffa6ee2efba2b2115a1974abcf424/conda_smithy/configure_feedstock.py#L560) in v3.6.12.  Notice how `conda_build.config.get_or_merge_config()` is returning stuff in `config.variant` that has `python: 3.7`.

When I run on Linux, where I (and the cf-admin bot) are able to rerender the recipe just fine, the `config.variant` is empty.

If I'm remembering/understanding conda-build correctly, `config.variant` at that point in `_render_ci_provider` should be the default variant buried somewhere in conda-build (or the exclusive_config_file, which doesn't exist in this case).

I'm going to keep digging into this but I'm running out of time to look right now and thought I should ask to see if anyone else understands what's going on here.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
[I] ✦ ➜ conda list
# packages in environment at /Users/timothys/miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                1.3.0                    py37_0    conda-forge
beautifulsoup4            4.8.2                    py37_0    conda-forge
blinker                   1.4                        py_1    conda-forge
bzip2                     1.0.8                h0b31af3_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28       py37hc8dfbb8_1    conda-forge
cffi                      1.14.0           py37h356ff06_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
conda                     4.8.2                    py37_0    conda-forge
conda-build               3.19.0           py37hc8dfbb8_0    conda-forge
conda-forge-pinning       2020.03.10                    0    conda-forge
conda-package-handling    1.6.0            py37h0b31af3_1    conda-forge
conda-smithy              3.6.12                     py_0    conda-forge
cryptography              2.8              py37hafa8578_1    conda-forge
curl                      7.68.0               h8754def_0    conda-forge
deprecated                1.2.7                      py_0    conda-forge
expat                     2.2.9                h4a8c4bd_2    conda-forge
filelock                  3.0.10                     py_0    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
git                       2.25.0          pl526hdc91d69_0    conda-forge
gitdb                     4.0.2                      py_0    conda-forge
gitpython                 3.1.0                      py_0    conda-forge
glob2                     0.7                        py_0    conda-forge
icu                       64.2                 h6de7cb9_1    conda-forge
idna                      2.9                        py_1    conda-forge
isodate                   0.6.0                      py_1    conda-forge
jinja2                    2.11.1                     py_0    conda-forge
krb5                      1.16.4               h1752a42_0    conda-forge
libarchive                3.3.3             h8912c15_1007    conda-forge
libcurl                   7.68.0               h709d2b2_0    conda-forge
libcxx                    9.0.1                         1    conda-forge
libcxxabi                 4.0.1                hcfea43d_1    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
liblief                   0.9.0                h3e78482_1    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libxml2                   2.9.10               h53d96d6_0    conda-forge
lz4-c                     1.8.3             h6de7cb9_1001    conda-forge
lzo                       2.10              h1de35cc_1000    conda-forge
markupsafe                1.1.1            py37h9bfed18_1    conda-forge
msrest                    0.6.10                     py_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
oauthlib                  3.0.1                      py_0    conda-forge
openssl                   1.1.1d               h0b31af3_0    conda-forge
pcre                      8.44                 h4a8c4bd_0    conda-forge
perl                      5.26.2            haec8ef5_1006    conda-forge
pip                       20.0.2                     py_2    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
psutil                    5.7.0            py37h0b31af3_0    conda-forge
py-lief                   0.9.0            py37h0ceac7d_1    conda-forge
pycosat                   0.6.3           py37h9bfed18_1003    conda-forge
pycparser                 2.20                       py_0    conda-forge
pycrypto                  2.6.1           py37h0b31af3_1003    conda-forge
pygithub                  1.43.6                   py37_0    conda-forge
pyjwt                     1.7.1                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pysocks                   1.7.1                    py37_0    conda-forge
python                    3.7.6           hfa4aa89_4_cpython    conda-forge
python-libarchive-c       2.9                      py37_0    conda-forge
python.app                1.3              py37h0b31af3_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.3              py37h0b31af3_0    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
requests                  2.23.0                   py37_0    conda-forge
requests-oauthlib         1.2.0                      py_0    conda-forge
ripgrep                   11.0.2               h01d97ff_3    conda-forge
ruamel.yaml               0.16.6           py37h0b31af3_0    conda-forge
ruamel.yaml.clib          0.2.0            py37h0b31af3_0    conda-forge
ruamel_yaml               0.15.80         py37h0b31af3_1000    conda-forge
setuptools                46.0.0           py37hc8dfbb8_2    conda-forge
six                       1.14.0                     py_1    conda-forge
smmap                     3.0.1                      py_0    conda-forge
soupsieve                 1.9.4                    py37_0    conda-forge
sqlite                    3.30.1               h93121df_0    conda-forge
tk                        8.6.10               hbbe82c9_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tqdm                      4.43.0                     py_0    conda-forge
urllib3                   1.25.7                   py37_0    conda-forge
vsts-python-api           0.1.22                     py_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
wrapt                     1.12.1           py37h9bfed18_1    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
yaml                      0.2.2                h0b31af3_1    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge
zstd                      1.4.4                he7fca8b_1    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
[I] ✦ ➜ conda info

     active environment : base
    active env location : /Users/timothys/miniconda3
            shell level : 1
       user config file : /Users/timothys/.condarc
 populated config files : /Users/timothys/.condarc
          conda version : 4.8.2
    conda-build version : 3.19.0
         python version : 3.7.6.final.0
       virtual packages : __osx=10.15.3
       base environment : /Users/timothys/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/timothys/miniconda3/pkgs
                          /Users/timothys/.conda/pkgs
       envs directories : /Users/timothys/miniconda3/envs
                          /Users/timothys/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.2 requests/2.23.0 CPython/3.7.6 Darwin/19.3.0 OSX/10.15.3
                UID:GID : 503:20
             netrc file : None
           offline mode : False

```
</details>

**Comment by timsnyder** [comment]
This was user error on my part.  I had CONDA_PY set in my environment from sourcing something somewhere that I shouldn't have kept around.  It was probably a `conda_build_env_setup.sh` in a build I was debugging.  At least now I know where the config.variant was coming from.
