### ISSUE TITLE
conda-smithy rerender produces pathspec error

### ISSUE THREAD

**Issue by floschl** [conda-forge/conda-smithy#1266]
Issue:
conda-smithy rerender produces pathspec error

Following step 4 of this tutorial: https://conda-forge.org/docs/user/ci-skeleton.html
produces the error:

<br/>
<code>conda smithy rerender -c auto</code>
<details>
(levmarci) c:\repos\levmar>conda smithy rerender -c auto
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\Scripts\conda-smithy-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda_smithy\cli.py", line 554, in main
    args.subcommand_func(args)
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda_smithy\cli.py", line 373, in __call__
    check=args.check,
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda_smithy\configure_feedstock.py", line 1718, in main
    config = _load_forge_config(forge_dir, exclusive_config_file)
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda_smithy\configure_feedstock.py", line 1442, in _load_forge_config
    remove_file_or_dir(os.path.join(forge_dir, old_file))
  File "C:\ProgramData\Miniconda3\lib\site-packages\conda_smithy\feedstock_io.py", line 67, in remove_file_or_dir
    repo.index.remove([filename], r=True)
  File "C:\ProgramData\Miniconda3\lib\site-packages\git\index\util.py", line 58, in post_clear_cache_if_not_raised
    rval = func(self, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\git\index\util.py", line 76, in check_default_index
    return func(self, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\git\index\base.py", line 862, in remove
    removed_paths = self.repo.git.rm(args, paths, **kwargs).splitlines()
  File "C:\ProgramData\Miniconda3\lib\site-packages\git\cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\git\cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "C:\ProgramData\Miniconda3\lib\site-packages\git\cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git rm -r --cached -- __pycache__
  stderr: 'fatal: pathspec '__pycache__' did not match any files'
</details>

Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at C:\ProgramData\Miniconda3\envs\levmarci:
#
# Name                    Version                   Build  Channel
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : levmarci
    active env location : C:\ProgramData\Miniconda3\envs\levmarci
            shell level : 2
       user config file : C:\Users\floschl\.condarc
 populated config files :
          conda version : 4.8.3
    conda-build version : 3.19.1
         python version : 3.7.6.final.0
       virtual packages :
       base environment : C:\ProgramData\Miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Miniconda3\pkgs
                          C:\Users\floschl\.conda\pkgs
                          C:\Users\floschl\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Miniconda3\envs
                          C:\Users\floschl\.conda\envs
                          C:\Users\floschl\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Windows/10 Windows/10.0.18362
          administrator : True
             netrc file : None
           offline mode : False
```
</details>

**Comment by floschl** [comment]
Just solved it. I had to remove this dir from my $PATH environment variable:
C:\Users\floschl\miniconda3\Scripts

(this obviously has changed from past conda versions)

**Comment by floschl** [comment]
I looked a little bit more into detail here. In configure_feedstock.py there is an entry, which makes the __pycache__ dir  to be deleted. In case of a packaged src in a subfolder, this dir does not exist in the top-level folder.
It might make sense to remove the deletion at this point?
