### ISSUE TITLE
Linter raising `'CommentedSeq' object has no attribute 'get'`

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/conda-smithy#1316]
https://github.com/conda-forge/sqlitecpp-feedstock/pull/1

Conda-smithy fails to lint the recipe of sqlitecpp-feedstock... I noticed it with PR https://github.com/conda-forge/sqlitecpp-feedstock/pull/1, but the error occurs on master as well.

Running the linter locally yields:

```
Traceback (most recent call last):
  File "/home/sylvain/miniconda3/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/conda_smithy/cli.py", line 574, in main
    args.subcommand_func(args)
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/conda_smithy/cli.py", line 411, in __call__
    return_hints=True,
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/conda_smithy/lint_recipe.py", line 783, in main
    results, hints = lintify(meta, recipe_dir, conda_forge)
  File "/home/sylvain/miniconda3/lib/python3.7/site-packages/conda_smithy/lint_recipe.py", line 576, in lintify
    shellcheck_enabled = code.get("shellcheck", {}).get(
AttributeError: 'CommentedSeq' object has no attribute 'get'
```

**Comment by isuruf** [comment]
This was because of a buggy conda-smithy version that created the feedstock.
https://github.com/conda-forge/sqlitecpp-feedstock/blob/master/conda-forge.yml

Change that to `{}` instead of `[]`.

**Comment by beckermr** [comment]
We should write an admin migration to g through and fix this.

**Comment by jakirkham** [comment]
Was this handled already?

See [this logic]( https://github.com/conda-forge/admin-migrations/pull/82/files#diff-eccb2e8ceb4b5970ea0a2a55f1c7c318004367a303cd4451bc965e7875b12f0bR19-R20 ) for `.conda` migration

Tried searching for `[]` in feedstocks, but didn't see anything (though maybe my GitHub search missed things)
