### ISSUE TITLE
Azure smithy regenerate error for private forge

### ISSUE THREAD

**Issue by hadim** [conda-forge/conda-smithy#1329]
Following https://github.com/conda-forge/conda-forge.github.io/issues/1069

I am trying to setup a private conda-forge like forge using Azure only. I have generated an azure token with the full scopes but when running `conda smithy regenerate` I have the following error: 

```
Traceback (most recent call last):
  File "/home/hadim/local/conda/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/home/hadim/local/conda/lib/python3.7/site-packages/conda_smithy/cli.py", line 584, in main
    args.subcommand_func(args)
  File "/home/hadim/local/conda/lib/python3.7/site-packages/conda_smithy/cli.py", line 391, in __call__
    self._call(args, tmpdir)
  File "/home/hadim/local/conda/lib/python3.7/site-packages/conda_smithy/cli.py", line 402, in _call
    temporary_directory=temporary_directory,
  File "/home/hadim/local/conda/lib/python3.7/site-packages/conda_smithy/configure_feedstock.py", line 1878, in main
    render_README(env, config, forge_dir, render_info)
  File "/home/hadim/local/conda/lib/python3.7/site-packages/conda_smithy/configure_feedstock.py", line 1329, in render_README
    build_def = resp.json()["value"][0]
  File "/home/hadim/local/conda/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/hadim/local/conda/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/hadim/local/conda/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/hadim/local/conda/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 3 column 1 (char 4)
```

**Comment by hadim** [comment]
```python
    if forge_config["azure"].get("build_id") is None:
        # Try to retrieve the build_id from the interwebs
        try:
            import requests

            resp = requests.get(
                "https://dev.azure.com/{org}/{project_name}/_apis/build/definitions?name={repo}".format(
                    org=forge_config["azure"]["user_or_org"],
                    project_name=forge_config["azure"]["project_name"],
                    repo=forge_config["github"]["repo_name"],
                )
            )
            resp.raise_for_status()
            print(resp.text)
            build_def = resp.json()["value"][0]
            forge_config["azure"]["build_id"] = build_def["id"]
        except (IndexError, IOError):
            pass
```

I tried to print the response and it's an HTML text asking me to signin.

**Comment by hadim** [comment]
The response code is 203.

**Comment by hadim** [comment]
The token I use within Azure to grant GH access has the following permissions: admin:org, admin:org_hook, admin:repo_hook, repo

**Comment by hadim** [comment]
This PR fixes for me: https://github.com/conda-forge/conda-smithy/pull/1331
