### ISSUE TITLE
conda-build=3.20.5: explode_variants() got an unexpected keyword argument 'extend_keys'

### ISSUE THREAD

**Issue by mbargull** [conda-forge/conda-smithy#1415]
Issue:
After updating to `conda-build=3.20.5` I get
```
  File "/opt/conda/envs/tmp/lib/python3.9/site-packages/conda_smithy/configure_feedstock.py", line 357, in _collapse_subpackage_variants
    used_key_values = conda_build.variants.dict_of_lists_to_list_of_dicts(
TypeError: explode_variants() got an unexpected keyword argument 'extend_keys'
```
due to https://github.com/conda/conda-build/commit/a7dc4f90aea1d35d2f09a0f071978ec60c17195c#diff-ab3e639bcffb453109c8b994f783028c3fbfdf8dc16655bdfd1849385738bf42R440

Code refs:
- https://github.com/conda-forge/conda-smithy/blob/v3.8.2/conda_smithy/configure_feedstock.py#L357-L365
- https://github.com/conda/conda-build/blob/3.20.5/conda_build/variants.py#L519-520
- https://github.com/conda/conda-build/blob/3.20.5/conda_build/variants.py#L453

Stack trace:
```
Traceback (most recent call last):
  File "/opt/conda/envs/tmp/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/envs/tmp/lib/python3.9/site-packages/conda_smithy/cli.py", line 613, in main
    args.subcommand_func(args)
  File "/opt/conda/envs/tmp/lib/python3.9/site-packages/conda_smithy/cli.py", line 419, in __call__
    self._call(args, tmpdir)
  File "/opt/conda/envs/tmp/lib/python3.9/site-packages/conda_smithy/cli.py", line 424, in _call
    configure_feedstock.main(
  File "/opt/conda/envs/tmp/lib/python3.9/site-packages/conda_smithy/configure_feedstock.py", line 1946, in main
    render_azure(env, config, forge_dir, return_metadata=True)
  File "/opt/conda/envs/tmp/lib/python3.9/site-packages/conda_smithy/configure_feedstock.py", line 1202, in render_azure
    return _render_ci_provider(
  File "/opt/conda/envs/tmp/lib/python3.9/site-packages/conda_smithy/configure_feedstock.py", line 674, in _render_ci_provider
    dump_subspace_config_files(
  File "/opt/conda/envs/tmp/lib/python3.9/site-packages/conda_smithy/configure_feedstock.py", line 416, in dump_subspace_config_files
    configs, top_level_loop_vars = _collapse_subpackage_variants(
  File "/opt/conda/envs/tmp/lib/python3.9/site-packages/conda_smithy/configure_feedstock.py", line 357, in _collapse_subpackage_variants
    used_key_values = conda_build.variants.dict_of_lists_to_list_of_dicts(
TypeError: explode_variants() got an unexpected keyword argument 'extend_keys'
```
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /opt/conda/envs/tmp:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
beautifulsoup4            4.9.3              pyhb0f4dca_0    conda-forge
blinker                   1.4                        py_1    conda-forge
boolean.py                3.7                        py_0    conda-forge
brotlipy                  0.7.0           py39h38d8fee_1001    conda-forge
bzip2                     1.0.8                h516909a_3    conda-forge
c-ares                    1.16.1               h516909a_3    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py39h079e4ff_2    conda-forge
cffi                      1.14.3           py39h0da4893_1    conda-forge
chardet                   3.0.4           py39h079e4ff_1008    conda-forge
conda                     4.9.0            py39h079e4ff_1    conda-forge
conda-build               3.20.5           py39h079e4ff_0    conda-forge
conda-forge-pinning       2020.10.27.17.47.18               0    conda-forge
conda-package-handling    1.7.2            py39h38d8fee_0    conda-forge
conda-smithy              3.8.2                      py_0    conda-forge
cryptography              3.2              py39h3c970e7_0    conda-forge
curl                      7.71.1               he644dc0_8    conda-forge
deprecated                1.2.10             pyh9f0ad1d_0    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
gettext                   0.19.8.1          hf34092f_1004    conda-forge
git                       2.29.1          pl5262he3b78ea_0    conda-forge
gitdb                     4.0.5                      py_0    conda-forge
gitpython                 3.1.11                     py_0    conda-forge
glob2                     0.7                        py_0    conda-forge
icu                       67.1                 he1b5a44_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
isodate                   0.6.0                      py_1    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
krb5                      1.17.1               hfafb76e_3    conda-forge
ld_impl_linux-64          2.35                 h769bd43_9    conda-forge
libarchive                3.4.3                hf837322_0    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgomp                   9.3.0               h5dbcf3e_17    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblief                   0.10.1               he1b5a44_2    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
libxml2                   2.9.10               h68273f3_2    conda-forge
license-expression        1.2                        py_0    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
markupsafe                1.1.1            py39h38d8fee_2    conda-forge
msrest                    0.6.19             pyh9f0ad1d_0    conda-forge
ncurses                   6.2                  he1b5a44_2    conda-forge
oauthlib                  3.0.1                      py_0    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
patchelf                  0.11                 he1b5a44_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
pip                       20.2.4                     py_0    conda-forge
pkginfo                   1.6.1              pyh9f0ad1d_0    conda-forge
psutil                    5.7.3            py39h38d8fee_0    conda-forge
py-lief                   0.10.1           py39hfbd4741_2    conda-forge
pycosat                   0.6.3           py39h38d8fee_1005    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pycrypto                  2.6.1           py39h38d8fee_1005    conda-forge
pygithub                  1.53                       py_0    conda-forge
pyjwt                     1.7.1                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pysocks                   1.7.1            py39h079e4ff_2    conda-forge
python                    3.9.0           h2a148a8_4_cpython    conda-forge
python-libarchive-c       2.9              py39h079e4ff_2    conda-forge
python_abi                3.9                      1_cp39    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyyaml                    5.3.1            py39h38d8fee_1    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
requests-oauthlib         1.3.0              pyh9f0ad1d_0    conda-forge
ripgrep                   12.1.1               h516909a_1    conda-forge
ruamel.yaml               0.16.12          py39h07f9747_1    conda-forge
ruamel.yaml.clib          0.2.2            py39h07f9747_1    conda-forge
ruamel_yaml               0.15.80         py39h38d8fee_1003    conda-forge
scrypt                    0.8.17           py39hba1e1b8_1    conda-forge
setuptools                49.6.0           py39h079e4ff_2    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
smmap                     3.0.4              pyh9f0ad1d_0    conda-forge
soupsieve                 2.0.1                      py_1    conda-forge
sqlite                    3.33.0               h4cf870e_1    conda-forge
tk                        8.6.10               hed695b0_1    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tqdm                      4.51.0             pyh9f0ad1d_0    conda-forge
tzdata                    2020d                h516909a_0    conda-forge
urllib3                   1.25.11                    py_0    conda-forge
vsts-python-api           0.1.22                     py_0    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
wrapt                     1.11.2           py39h07f9747_1    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : tmp
    active env location : /opt/conda/envs/tmp
            shell level : 2
       user config file : /home/conda/.condarc
 populated config files : /home/conda/.condarc
          conda version : 4.8.3
    conda-build version : 3.19.2
         python version : 3.7.8.final.0
       virtual packages : __glibc=2.12
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/conda/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/conda/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.24.0 CPython/3.7.8 Linux/5.4.72-1-MANJARO centos/6.10 glibc/2.12
                UID:GID : 9001:9001
             netrc file : None
           offline mode : False


```
</details>

**Comment by mbargull** [comment]
I haven't looked at whether it makes sense to fix it in `conda-smithy` or `conda-build`.

**Comment by beckermr** [comment]
@isuruf didn't you put in a fix for this?

**Comment by isuruf** [comment]
Should be fixed in master now

**Comment by mbargull** [comment]
Business as usual... Isuru saving the day, that is :D. Thanks!
