### ISSUE TITLE
Trying to lint recipe results in AttributeError

### ISSUE THREAD

**Issue by marimeireles** [conda-forge/conda-smithy#1489]
I'm trying to lint my code locally and I get the following error:

```
Traceback (most recent call last):
  File "/home/mariana/miniconda3/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/home/mariana/miniconda3/lib/python3.8/site-packages/conda_smithy/cli.py", line 646, in main
    args.subcommand_func(args)
  File "/home/mariana/miniconda3/lib/python3.8/site-packages/conda_smithy/cli.py", line 479, in __call__
    lints, hints = lint_recipe.main(
  File "/home/mariana/miniconda3/lib/python3.8/site-packages/conda_smithy/lint_recipe.py", line 859, in main
    results, hints = lintify(meta, recipe_dir, conda_forge)
  File "/home/mariana/miniconda3/lib/python3.8/site-packages/conda_smithy/lint_recipe.py", line 430, in lintify
    req, _, _ = requirement.partition("#")
AttributeError: 'CommentedMap' object has no attribute 'partition'

```

I'm running on the following folder:

`(base) mariana@wintermute ~/dev/staged-recipes/recipes/xeus-octave (xeus-octave?) $ conda smithy recipe-lint .`

Fresh installation out of `conda-forge`.

**Comment by isuruf** [comment]
That's probably because there's something wrong with your recipe. Not that of conda-smithy.

**Comment by marimeireles** [comment]
But should a linting tool be affected by this kind of problem? Sorry, I don't mean to sound entitled, just curious.
I don't remember running into similar issues using other linting tools, as in, if my code is wrong smh the tool would stop working.

**Comment by dopplershift** [comment]
It's tricky in this case since conda-smithy is relying on the objects spit out by ruamel-yaml, which depend on the exact YAML syntax it has parsed. In this case it seems like some requirement is being parsed as a map.

**Comment by marimeireles** [comment]
And you were right, it was because of a mistake on my recipe. I'm just wondering because this is exactly the kind of error a linter should get.

**Comment by marimeireles** [comment]
> It's tricky in this case since conda-smithy is relying on the objects spit out by ruamel-yaml, which depend on the exact YAML syntax it has parsed. In this case it seems like some requirement is being parsed as a map.

Ah, I see.
I think the way to go would be using an AST? But then, I imagine it's a lot of work to do that.

**Comment by isuruf** [comment]
It's not a huge amount of work. For this case, we need to check that `requirement` is actually a string before calling `.partition` on it.

**Comment by isuruf** [comment]
Note that `conda-smithy`'s linter is not supposed to be a linter for a correct conda-build recipe, but it's a linter to give suggestions on making a correct recipe to be better and conform to conda-forge standards. That's why we don't have extensive checks to make sure the recipe is correct. PRs welcome though.
