### ISSUE TITLE
Calling conda smithy github-create with --user raises exception

### ISSUE THREAD

**Issue by mwcraig** [conda-forge/conda-smithy#15]
When I invoke `oncda smithy` to create a github repo (after setting the token correctly) I get this:

```python
$ conda smithy github-create --user mwcraig mrjob-feedstock/
Traceback (most recent call last):
  File "/Users/mcraig/miniconda/bin/conda-smithy", line 9, in <module>
    load_entry_point('conda-smithy==0.1.0.dev0', 'console_scripts', 'conda-smithy')()
  File "/Users/mcraig/miniconda/lib/python2.7/site-packages/conda_smithy-0.1.0.dev0-py2.7.egg/conda_smithy/conda_smithy.py", line 164, in main
    args.subcommand_func(args)
  File "/Users/mcraig/miniconda/lib/python2.7/site-packages/conda_smithy-0.1.0.dev0-py2.7.egg/conda_smithy/conda_smithy.py", line 94, in __call__
    user_or_org.get_user(args.user)
UnboundLocalError: local variable 'user_or_org' referenced before assignment
```

**Comment by pelson** [comment]
https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/conda_smithy.py#L94

I think that should read ```user_or_org = gh.get_user(args.user)```
