### ISSUE TITLE
Are git submodules supported?

### ISSUE THREAD

**Issue by sgbaird** [conda-forge/conda-smithy#1516]
This is related to https://github.com/conda-forge/conda-smithy/issues/437 and https://github.com/conda-forge/conda-smithy/issues/37. After reading these, it was a bit hard to tell if git submodules are supposed to be supported, or if that also falls into the category of "won't fix". A search for "submodule" in the docs also returned no results. I have a fork of a repo (not hosted via PyPI or conda) added as a submodule to my repo. I do not have write access to the parent of the fork. A PR may go through at some point, but the maintainer is busy for now.

```python
(mat_discover) PS C:\Users\sterg\Documents\GitHub\scratch\discover-size-check> conda smithy init .
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
Initialized empty Git repository in C:/Users/sterg/Documents/GitHub/scratch/discover-size-check/mat_discover-feedstock/.git/
Traceback (most recent call last):
  File "C:\Users\sterg\Anaconda3\envs\mat_discover\lib\site-packages\conda_smithy\cli.py", line 43, in generate_feedstock_content
    configure_feedstock.copytree(source_recipe_dir, target_recipe_dir)
  File "C:\Users\sterg\Anaconda3\envs\mat_discover\lib\site-packages\conda_smithy\configure_feedstock.py", line 73, in copytree
    copytree(s, d, ignore, root_dst=root_dst)
  File "C:\Users\sterg\Anaconda3\envs\mat_discover\lib\site-packages\conda_smithy\configure_feedstock.py", line 73, in copytree
    copytree(s, d, ignore, root_dst=root_dst)
  File "C:\Users\sterg\Anaconda3\envs\mat_discover\lib\site-packages\conda_smithy\configure_feedstock.py", line 73, in copytree
    copytree(s, d, ignore, root_dst=root_dst)
  [Previous line repeated 2 more times]
  File "C:\Users\sterg\Anaconda3\envs\mat_discover\lib\site-packages\conda_smithy\configure_feedstock.py", line 75, in copytree
    copy_file(s, d)
  File "C:\Users\sterg\Anaconda3\envs\mat_discover\lib\site-packages\conda_smithy\feedstock_io.py", line 105, in copy_file
    repo.index.add([dst])
  File "C:\Users\sterg\Anaconda3\envs\mat_discover\lib\site-packages\git\index\base.py", line 776, in add
    paths, entries = self._preprocess_add_items(items)
  File "C:\Users\sterg\Anaconda3\envs\mat_discover\lib\site-packages\git\index\base.py", line 612, in _preprocess_add_items
    paths.append(self._to_relative_path(item))
  File "C:\Users\sterg\Anaconda3\envs\mat_discover\lib\site-packages\git\index\base.py", line 598, in _to_relative_path 
    raise ValueError("Absolute path %r is not in git repository at %r" % (path, self.repo.working_tree_dir))
cipe\\.git\\modules\\CrabNet\\refs\\heads\\master' is not in git repository at '../../../mat_discover/CrabNet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sterg\Anaconda3\envs\mat_discover\Scripts\conda-smithy-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\sterg\Anaconda3\envs\mat_discover\lib\site-packages\conda_smithy\cli.py", line 681, in main
    args.subcommand_func(args)
  File "C:\Users\sterg\Anaconda3\envs\mat_discover\lib\site-packages\conda_smithy\cli.py", line 139, in __call__        
    generate_feedstock_content(feedstock_directory, args.recipe_directory)
  File "C:\Users\sterg\Anaconda3\envs\mat_discover\lib\site-packages\conda_smithy\cli.py", line 47, in generate_feedstock_content
    raise type(e)(
  File "C:\Users\sterg\Anaconda3\envs\mat_discover\lib\site-packages\conda_smithy\cli.py", line 43, in generate_feedstock_content
    configure_feedstock.copytree(source_recipe_dir, target_recipe_dir)
  File "C:\Users\sterg\Anaconda3\envs\mat_discover\lib\site-packages\conda_smithy\configure_feedstock.py", line 73, in copytree
    copytree(s, d, ignore, root_dst=root_dst)
  File "C:\Users\sterg\Anaconda3\envs\mat_discover\lib\site-packages\conda_smithy\configure_feedstock.py", line 73, in copytree
    copytree(s, d, ignore, root_dst=root_dst)
  File "C:\Users\sterg\Anaconda3\envs\mat_discover\lib\site-packages\conda_smithy\configure_feedstock.py", line 73, in copytree
    copytree(s, d, ignore, root_dst=root_dst)
  [Previous line repeated 2 more times]
  File "C:\Users\sterg\Anaconda3\envs\mat_discover\lib\site-packages\conda_smithy\configure_feedstock.py", line 75, in copytree
    copy_file(s, d)
  File "C:\Users\sterg\Anaconda3\envs\mat_discover\lib\site-packages\conda_smithy\feedstock_io.py", line 105, in copy_file
    repo.index.add([dst])
  File "C:\Users\sterg\Anaconda3\envs\mat_discover\lib\site-packages\git\index\base.py", line 776, in add
    paths, entries = self._preprocess_add_items(items)
  File "C:\Users\sterg\Anaconda3\envs\mat_discover\lib\site-packages\git\index\base.py", line 612, in _preprocess_add_items
    paths.append(self._to_relative_path(item))
  File "C:\Users\sterg\Anaconda3\envs\mat_discover\lib\site-packages\git\index\base.py", line 598, in _to_relative_path 
    raise ValueError("Absolute path %r is not in git repository at %r" % (path, self.repo.working_tree_dir))
ValueError: Absolute path 'C:\\Users\\sterg\\Documents\\GitHub\\scratch\\discover-size-check\\mat_discover-feedstock\\recipe\\.git\\modules\\CrabNet\\refs\\heads\\master' is not in git repository at '../../../mat_discover/CrabNet' while copying file .
```

- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at C:\Users\sterg\Anaconda3\envs\mat_discover:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
ase                       3.22.0             pyhd8ed1ab_0    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
beautifulsoup4            4.10.0             pyha770c72_0    conda-forge
black                     21.9b0                   pypi_0    pypi
blas                      2.108                       mkl    conda-forge
blas-devel                3.9.0                     8_mkl    conda-forge
blinker                   1.4                        py_1    conda-forge
boolean.py                3.7                        py_0    conda-forge
bounded-pool-executor     0.0.3                    pypi_0    pypi
brotlipy                  0.7.0           py38h294d835_1001    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.10.8            h5b45459_0    conda-forge
certifi                   2021.10.8        py38haa244fe_0    conda-forge
cffi                      1.14.6           py38hd8c33c5_1    conda-forge
cftime                    1.5.1            py38h6f4d8f0_0    conda-forge
chardet                   4.0.0            py38haa244fe_1    conda-forge
charset-normalizer        2.0.0              pyhd8ed1ab_0    conda-forge
click                     8.0.3            py38haa244fe_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda                     4.10.3           py38haa244fe_2    conda-forge
conda-build               3.21.4           py38haa244fe_0    conda-forge
conda-forge-pinning       2021.10.20.22.24.36      hd8ed1ab_0    conda-forge
conda-package-handling    1.7.3            py38h31c79cd_0    conda-forge
conda-smithy              3.13.0             pyhd8ed1ab_0    conda-forge
cryptography              35.0.0           py38hd7da0ea_0    conda-forge
cudatoolkit               11.1.1               heb2d755_9    conda-forge
curl                      7.79.1               h789b8ee_1    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.24                  pypi_0    pypi
dataclasses               0.8                pyhc8e2a94_3    conda-forge
decorator                 5.1.0              pyhd8ed1ab_0    conda-forge
deprecated                1.2.13             pyh6c4a22f_0    conda-forge
docopt                    0.6.2                      py_1    conda-forge
docutils                  0.17.1           py38haa244fe_0    conda-forge
double-conversion         3.1.5                h0e60522_2    conda-forge
eigen                     3.4.0                h2d74725_0    conda-forge
elm2d                     0.4.1                    pypi_0    pypi
elmd                      0.4.8                    pypi_0    pypi
expat                     2.4.1                h39d44d4_0    conda-forge
ffmpeg                    4.3.1                ha925a31_0    conda-forge
filelock                  3.3.1              pyhd8ed1ab_0    conda-forge
flake8                    4.0.1                    pypi_0    pypi
flask                     2.0.2              pyhd8ed1ab_0    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
future                    0.18.2           py38haa244fe_3    conda-forge
git                       2.33.1               h57928b3_0    conda-forge
gitdb                     4.0.7              pyhd8ed1ab_0    conda-forge
gitpython                 3.1.24             pyhd8ed1ab_0    conda-forge
gl2ps                     1.4.2                h0597ee9_0    conda-forge
glew                      2.1.0                h39d44d4_2    conda-forge
glob2                     0.7                        py_0    conda-forge
grayskull                 0.8.5              pyhd8ed1ab_0    conda-forge
hdbscan                   0.8.27           py38h347fdf6_0    conda-forge
hdf4                      4.2.15               h0e5069d_3    conda-forge
hdf5                      1.10.6          nompi_h5268f04_1114    conda-forge
icu                       68.1                 h0e60522_0    conda-forge
idna                      3.1                pyhd3deb0d_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
intel-openmp              2021.4.0          h57928b3_3556    conda-forge
isodate                   0.6.0                      py_1    conda-forge
itsdangerous              2.0.1              pyhd8ed1ab_0    conda-forge
jbig                      2.1               h8d14728_2003    conda-forge
jinja2                    3.0.2              pyhd8ed1ab_0    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
jsoncpp                   1.9.4                h2d74725_3    conda-forge
kaleido                   0.2.1                    pypi_0    pypi
kiwisolver                1.3.2            py38hbd9d945_0    conda-forge
krb5                      1.19.2               hbae68bd_2    conda-forge
latexcodec                2.0.1              pyh9f0ad1d_0    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libarchive                3.5.2                hb45042f_1    conda-forge
libblas                   3.9.0                     8_mkl    conda-forge
libcblas                  3.9.0                     8_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libcurl                   7.79.1               h789b8ee_1    conda-forge
libdeflate                1.8                  h8ffe710_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblapack                 3.9.0                     8_mkl    conda-forge
liblapacke                3.9.0                     8_mkl    conda-forge
liblief                   0.11.5               h0e60522_0    conda-forge
libnetcdf                 4.8.1           nompi_hf689e7d_100    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libssh2                   1.10.0               h680486a_2    conda-forge
libtheora                 1.1.1             h8d14728_1005    conda-forge
libtiff                   4.3.0                hd413186_2    conda-forge
libuv                     1.42.0               h8ffe710_0    conda-forge
libxml2                   2.9.12               hf5bbc77_0    conda-forge
libzip                    1.8.0                hfed4ece_1    conda-forge
libzlib                   1.2.11            h8ffe710_1013    conda-forge
license-expression        1.2                        py_0    conda-forge
llvmlite                  0.36.0           py38h57a6900_0    conda-forge
loguru                    0.5.3            py38haa244fe_2    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
lzo                       2.10              he774522_1000    conda-forge
m2-msys2-runtime          2.5.0.17080.65c939c               3    conda-forge
m2-patch                  2.7.5                         2    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                2.0.1            py38h294d835_0    conda-forge
mat-discover              1.1.1                    pypi_0    pypi
matplotlib                3.4.3            py38haa244fe_1    conda-forge
matplotlib-base           3.4.3            py38h1f000d6_1    conda-forge
mccabe                    0.6.1                    pypi_0    pypi
menuinst                  1.4.18           py38haa244fe_0    conda-forge
mkl                       2020.4             hb70f87d_311    conda-forge
mkl-devel                 2020.4             h57928b3_312    conda-forge
mkl-include               2020.4             hb70f87d_311    conda-forge
monty                     2021.8.17          pyhd8ed1ab_0    conda-forge
more-itertools            8.10.0             pyhd8ed1ab_0    conda-forge
mpmath                    1.2.1              pyhd8ed1ab_0    conda-forge
msrest                    0.6.21             pyh44b312d_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
mypy                      0.910                    pypi_0    pypi
mypy-extensions           0.4.3                    pypi_0    pypi
netcdf4                   1.5.7           nompi_py38hc1150aa_101    conda-forge
networkx                  2.5                        py_0    conda-forge
ninja                     1.10.2               h2d74725_1    conda-forge
numba                     0.53.1           py38h99fac5f_1    conda-forge
numpy                     1.21.2           py38h089cfbf_0    conda-forge
oauthlib                  3.1.1              pyhd8ed1ab_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openssl                   1.1.1l               h8ffe710_0    conda-forge
packaging                 21.0               pyhd8ed1ab_0    conda-forge
palettable                3.3.0                      py_0    conda-forge
pandas                    1.3.4            py38h5d928e2_0    conda-forge
pathspec                  0.9.0                    pypi_0    pypi
patsy                     0.5.2              pyhd8ed1ab_0    conda-forge
pillow                    8.3.2            py38h794f750_0    conda-forge
pip                       21.3               pyhd8ed1ab_0    conda-forge
pipreqs                   0.4.10                     py_0    conda-forge
pkginfo                   1.7.1              pyhd8ed1ab_0    conda-forge
platformdirs              2.4.0                    pypi_0    pypi
plotly                    5.3.1              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0            py38haa244fe_1    conda-forge
pqdm                      0.1.0                    pypi_0    pypi
progressbar2              3.53.1             pyh9f0ad1d_0    conda-forge
proj                      8.1.1                h1cfcee9_2    conda-forge
psutil                    5.8.0            py38h294d835_1    conda-forge
pugixml                   1.11.4               h0e60522_0    conda-forge
py                        1.10.0             pyhd3deb0d_0    conda-forge
py-lief                   0.11.5           py38h885f38d_0    conda-forge
pybtex                    0.24.0           py38haa244fe_0    conda-forge
pycodestyle               2.8.0                    pypi_0    pypi
pycosat                   0.6.3           py38h294d835_1006    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pycrypto                  2.6.1           py38hab1e662_1005    conda-forge
pydocstyle                6.1.1                    pypi_0    pypi
pyflakes                  2.4.0                    pypi_0    pypi
pygithub                  1.55               pyh6c4a22f_0    conda-forge
pygments                  2.10.0             pyhd8ed1ab_0    conda-forge
pyjwt                     2.3.0              pyhd8ed1ab_0    conda-forge
pymatgen                  2022.0.14        py38hbd9d945_0    conda-forge
pynacl                    1.4.0            py38h31c79cd_2    conda-forge
pynndescent               0.5.5              pyh6c4a22f_0    conda-forge
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py38haa244fe_7    conda-forge
pyqt-impl                 5.12.3           py38h885f38d_7    conda-forge
pyqt5-sip                 4.19.18          py38h885f38d_7    conda-forge
pyqtchart                 5.12             py38h885f38d_7    conda-forge
pyqtwebengine             5.12.1           py38h885f38d_7    conda-forge
pysocks                   1.7.1            py38haa244fe_3    conda-forge
pytest                    6.2.5            py38haa244fe_0    conda-forge
python                    3.8.12          h7840368_2_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-libarchive-c       3.1              py38haa244fe_0    conda-forge
python-utils              2.5.6              pyh44b312d_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.9.1           py3.8_cuda11.1_cudnn8_0    pytorch
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pywin32                   301              py38h294d835_0    conda-forge
pyyaml                    6.0              py38h294d835_0    conda-forge
qt                        5.12.9               h5909a2a_4    conda-forge
rapidfuzz                 0.12.5           py38hb99c5c2_0    conda-forge
regex                     2021.10.8                pypi_0    pypi
requests                  2.26.0             pyhd8ed1ab_0    conda-forge
requests-oauthlib         1.3.0              pyh9f0ad1d_0    conda-forge
ripgrep                   13.0.0               h7f3b576_1    conda-forge
ruamel.yaml               0.17.16          py38h294d835_0    conda-forge
ruamel.yaml.clib          0.2.2            py38h294d835_2    conda-forge
ruamel.yaml.jinja2        0.2.4                      py_1    conda-forge
ruamel_yaml               0.15.80         py38h294d835_1004    conda-forge
scikit-learn              1.0              py38h8224a6f_1    conda-forge
scipy                     1.7.1            py38ha1292f7_0    conda-forge
scrypt                    0.8.18           py38hd8c33c5_0    conda-forge
seaborn                   0.11.2               hd8ed1ab_0    conda-forge
seaborn-base              0.11.2             pyhd8ed1ab_0    conda-forge
setuptools                58.2.0           py38haa244fe_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     3.0.5              pyh44b312d_0    conda-forge
snowballstemmer           2.1.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.0.1                      py_1    conda-forge
spglib                    1.16.2           py38h6f4d8f0_0    conda-forge
sphinx                    4.2.0              pyh6c4a22f_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_0    conda-forge
sqlite                    3.36.0               h8ffe710_2    conda-forge
statsmodels               0.13.0           py38h6f4d8f0_0    conda-forge
stdlib-list               0.7.0                      py_2    conda-forge
sympy                     1.9              py38haa244fe_0    conda-forge
tabulate                  0.8.9              pyhd8ed1ab_0    conda-forge
tbb                       2020.2               h2d74725_4    conda-forge
tbb-devel                 2020.2               h2d74725_4    conda-forge
tenacity                  8.0.1              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.0.0              pyh8a188c0_0    conda-forge
tk                        8.6.11               h8ffe710_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     1.2.1                    pypi_0    pypi
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.1              py38h294d835_1    conda-forge
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
typing_extensions         3.10.0.2           pyha770c72_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
umap-learn                0.5.1            py38haa244fe_1    conda-forge
uncertainties             3.1.6              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
utfcpp                    3.2.1                h57928b3_0    conda-forge
vc                        14.2                 hb210afc_5    conda-forge
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
vsts-python-api           0.1.22                     py_0    conda-forge
vtk                       9.0.3           no_osmesa_py38hdd3d7f6_105    conda-forge
werkzeug                  2.0.1              pyhd8ed1ab_0    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
win32_setctime            1.0.3                      py_0    conda-forge
win_inet_pton             1.1.0            py38haa244fe_2    conda-forge
wrapt                     1.13.2           py38h294d835_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
yarg                      0.1.9                      py_1    conda-forge
zlib                      1.2.11            h8ffe710_1013    conda-forge
zstd                      1.5.0                h6255e5f_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : mat_discover
    active env location : C:\Users\sterg\Anaconda3\envs\mat_discover
            shell level : 4
       user config file : C:\Users\sterg\.condarc
 populated config files : C:\Users\sterg\.condarc
          conda version : 4.10.3
    conda-build version : 3.21.4
         python version : 3.8.12.final.0
       virtual packages : __cuda=11.4=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\sterg\Anaconda3  (writable)
      conda av data dir : C:\Users\sterg\Anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/pytorch/win-64
                          https://conda.anaconda.org/pytorch/noarch
                          https://conda.anaconda.org/numba/label/ci_llvmlite_0.38/win-64
                          https://conda.anaconda.org/numba/label/ci_llvmlite_0.38/noarch
                          https://conda.anaconda.org/numba/win-64
                          https://conda.anaconda.org/numba/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\sterg\Anaconda3\pkgs
                          C:\Users\sterg\.conda\pkgs
                          C:\Users\sterg\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\sterg\Anaconda3\envs
                          C:\Users\sterg\.conda\envs
                          C:\Users\sterg\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.8.12 Windows/10 Windows/10.0.19042
          administrator : False
             netrc file : None
           offline mode : False
```
</details>

**Comment by jakirkham** [comment]
Sorry for the slow reply here

Don't think `conda smithy init` would work (without changes)

`conda smithy rerender` should work (use this quite regularly personally)

Other `conda smithy` commands am less sure of

HTH
