### ISSUE TITLE
Rerendering fails on Bash on Windows

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/conda-smithy#1549]
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

The env was created with: 

```yaml
name: test
channels:
  - conda-forge
dependencies:
  - conda-smithy  # resulted in 3.14.3
  - python 3.7
  - pip
  - tomlkit
  - ruamel.yaml
  - anaconda-client
  - conda-build
  - conda-forge-ci-setup 3.*
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

Latest Miniconda for Windows (Conda 4.10.3 Python 3.9):

```
    environment location: C:\Miniconda3
  
    added / updated specs:
      - brotlipy==0.7.0=py39hb82d6ee_1001
      - ca-certificates==2021.10.8=h5b45459_0
      - certifi==2021.10.8=py39hcbf5309_0
      - cffi==1.14.6=py39h0878f49_1
      - chardet==4.0.0=py39hcbf5309_1
      - charset-normalizer==2.0.0=pyhd8ed1ab_0
      - colorama==0.4.4=pyh9f0ad1d_0
      - conda-package-handling==1.7.3=py39hb3671d1_0
      - conda==4.10.3=py39hcbf5309_2
      - cryptography==3.4.8=py39hd8d06c1_0
      - idna==3.1=pyhd3deb0d_0
      - menuinst==1.4.18=py39hcbf5309_0
      - miniforge_console_shortcut==1.0=h57928b3_0
      - openssl==1.1.1l=h8ffe710_0
      - pip==21.3=pyhd8ed1ab_0
      - pycosat==0.6.3=py39hb82d6ee_1006
      - pycparser==2.20=pyh9f0ad1d_2
      - pyopenssl==21.0.0=pyhd8ed1ab_0
      - pysocks==1.7.1=py39hcbf5309_3
      - python==3.9.7=h7840368_3_cpython
      - python_abi==3.9=2_cp39
      - pywin32==301=py39hb82d6ee_0
      - requests==2.26.0=pyhd8ed1ab_0
      - ruamel_yaml==0.15.80=py39hb82d6ee_1004
      - setuptools==58.2.0=py39hcbf5309_0
      - six==1.16.0=pyh6c4a22f_0
      - sqlite==3.36.0=h8ffe710_2
      - tqdm==4.62.3=pyhd8ed1ab_0
      - tzdata==2021c=he74cb21_0
      - ucrt==10.0.20348.0=h57928b3_0
      - urllib3==1.26.7=pyhd8ed1ab_0
      - vc==14.2=hb210afc_5
      - vs2015_runtime==14.29.30037=h902a5da_5
      - wheel==0.37.0=pyhd8ed1ab_1
      - win_inet_pton==1.1.0=py39hcbf5309_2
      - yaml==0.2.5=he774522_0
 ```

</details>

If one tries to rerender a feedstock on GitHub Actions using `shell: bash -l {0}` on Windows, rerendering fails with:

```
+ conda-smithy rerender
INFO:conda_smithy.configure_feedstock:Downloading conda-forge-pinning-2021.11.23.20.00.37
INFO:conda_smithy.configure_feedstock:Extracting conda-forge-pinning to C:\Users\RUNNER~1\AppData\Local\Temp\tmpvrg5xmur
Traceback (most recent call last):
  File "C:\Miniconda3\envs\test\Scripts\conda-smithy-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Miniconda3\envs\test\lib\site-packages\conda_smithy\cli.py", line 681, in main
    args.subcommand_func(args)
  File "C:\Miniconda3\envs\test\lib\site-packages\conda_smithy\cli.py", line 486, in __call__
    self._call(args, tmpdir)
  File "C:\Miniconda3\envs\test\lib\site-packages\conda_smithy\cli.py", line 498, in _call
    temporary_directory=temporary_directory,
  File "C:\Miniconda3\envs\test\lib\site-packages\conda_smithy\configure_feedstock.py", line 2150, in main
    config = _load_forge_config(forge_dir, exclusive_config_file, forge_yml)
  File "C:\Miniconda3\envs\test\lib\site-packages\conda_smithy\configure_feedstock.py", line 1828, in _load_forge_config
    remove_file_or_dir(os.path.join(forge_dir, old_file))
  File "C:\Miniconda3\envs\test\lib\site-packages\conda_smithy\feedstock_io.py", line 63, in remove_file_or_dir
    return remove_file(filename)
  File "C:\Miniconda3\envs\test\lib\site-packages\conda_smithy\feedstock_io.py", line 76, in remove_file
    repo.index.remove([filename])
  File "C:\Miniconda3\envs\test\lib\site-packages\git\index\util.py", line 70, in post_clear_cache_if_not_raised
    rval = func(self, *args, **kwargs)
  File "C:\Miniconda3\envs\test\lib\site-packages\git\index\util.py", line 88, in check_default_index
    return func(self, *args, **kwargs)
  File "C:\Miniconda3\envs\test\lib\site-packages\git\index\base.py", line 906, in remove
    removed_paths = self.repo.git.rm(args, paths, **kwargs).splitlines()
  File "C:\Miniconda3\envs\test\lib\site-packages\git\cmd.py", line 638, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "C:\Miniconda3\envs\test\lib\site-packages\git\cmd.py", line 1183, in _call_process
    return self.execute(call, **exec_kwargs)
  File "C:\Miniconda3\envs\test\lib\site-packages\git\cmd.py", line 983, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git rm --cached -- ci_support\upload_or_check_non_existence.py
  stderr: 'fatal: pathspec 'ci_support\upload_or_check_non_existence.py' did not match any files'
Error: Process completed with exit code 1.
```

Notably, `ci_support` is missing its starting `.`. @chrisburr adds:

> Yeah, I have a suspicion the backslash is the issue and this [line](https://github.com/conda-forge/conda-smithy/blob/569b09275586b1cddc1a485b5737378669f4103c/conda_smithy/feedstock_io.py#L67) should be changed to `repo.index.remove([filename.replace(os.sep, "/")], r=True)` but I have no way of testing on Windows.

I must add that switching to `shell: cmd /C CALL {0}` _does_ work as expected. It's just Bash on Windows.

**Comment by cNoNim** [comment]
Don't use Bash, but I get the same error:
```shell
(conda-smithy) (conda-smithy) PS E:\GitHub\cNoNim\sfml-feedstock> conda smithy rerender
INFO:conda_smithy.configure_feedstock:Downloading conda-forge-pinning-2024.01.29.16.06.26
INFO:conda_smithy.configure_feedstock:Extracting conda-forge-pinning to C:\Users\cnonim\AppData\Local\Temp\conda-smithy
Traceback (most recent call last):
  File "E:\mambaforge\envs\conda-smithy\Scripts\conda-smithy-script.py", line 9, in <module>
    sys.exit(main())
  File "E:\mambaforge\envs\conda-smithy\lib\site-packages\conda_smithy\cli.py", line 724, in main
    args.subcommand_func(args)
  File "E:\mambaforge\envs\conda-smithy\lib\site-packages\conda_smithy\cli.py", line 584, in __call__
    self._call(args, tmpdir)
  File "E:\mambaforge\envs\conda-smithy\lib\site-packages\conda_smithy\cli.py", line 589, in _call
    configure_feedstock.main(
  File "E:\mambaforge\envs\conda-smithy\lib\site-packages\conda_smithy\configure_feedstock.py", line 2506, in main
    config = _load_forge_config(forge_dir, exclusive_config_file, forge_yml)
  File "E:\mambaforge\envs\conda-smithy\lib\site-packages\conda_smithy\configure_feedstock.py", line 2114, in _load_forge_config
    remove_file_or_dir(os.path.join(forge_dir, old_file))
  File "E:\mambaforge\envs\conda-smithy\lib\site-packages\conda_smithy\feedstock_io.py", line 70, in remove_file_or_dir
    return remove_file(filename)
  File "E:\mambaforge\envs\conda-smithy\lib\site-packages\conda_smithy\feedstock_io.py", line 83, in remove_file
    repo.index.remove([filename])
  File "E:\mambaforge\envs\conda-smithy\lib\site-packages\git\index\util.py", line 79, in post_clear_cache_if_not_raised
    rval = func(self, *args, **kwargs)
  File "E:\mambaforge\envs\conda-smithy\lib\site-packages\git\index\util.py", line 101, in check_default_index
    return func(self, *args, **kwargs)
  File "E:\mambaforge\envs\conda-smithy\lib\site-packages\git\index\base.py", line 1001, in remove
    removed_paths = self.repo.git.rm(args, paths, **kwargs).splitlines()
  File "E:\mambaforge\envs\conda-smithy\lib\site-packages\git\cmd.py", line 800, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "E:\mambaforge\envs\conda-smithy\lib\site-packages\git\cmd.py", line 1386, in _call_process
    return self.execute(call, **exec_kwargs)
  File "E:\mambaforge\envs\conda-smithy\lib\site-packages\git\cmd.py", line 1183, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git rm --cached -- ci_support\upload_or_check_non_existence.py
  stderr: 'fatal: pathspec 'ci_support\upload_or_check_non_existence.py' did not match any files'
(conda-smithy) (conda-smithy) PS E:\GitHub\cNoNim\sfml-feedstock>
```
Incorrect slash used
```shell
(conda-smithy) (conda-smithy) PS E:\GitHub\cNoNim\sfml-feedstock> git rm --cached -- ci_support\upload_or_check_non_existence.py
fatal: pathspec 'ci_support\upload_or_check_non_existence.py' did not match any files
```
but 
```shell
(conda-smithy) (conda-smithy) PS E:\GitHub\cNoNim\sfml-feedstock> git rm --cached -- ci_support/upload_or_check_non_existence.py
rm 'ci_support/upload_or_check_non_existence.py'
```

**Comment by cNoNim** [comment]
There seems to be a problem in GitPython
I tried to replace the slash 
```py
replace(os.sep, "/")
```
after os.path.join, but got
```shell
(conda-smithy) (conda-smithy) PS E:\GitHub\cNoNim\sfml-feedstock> conda smithy rerender
Traceback (most recent call last):
  File "E:\mambaforge\envs\conda-smithy\Scripts\conda-smithy-script.py", line 9, in <module>
    sys.exit(main())
  File "E:\mambaforge\envs\conda-smithy\lib\site-packages\conda_smithy\cli.py", line 724, in main
    args.subcommand_func(args)
  File "E:\mambaforge\envs\conda-smithy\lib\site-packages\conda_smithy\cli.py", line 584, in __call__
    self._call(args, tmpdir)
  File "E:\mambaforge\envs\conda-smithy\lib\site-packages\conda_smithy\cli.py", line 589, in _call
    configure_feedstock.main(
  File "E:\mambaforge\envs\conda-smithy\lib\site-packages\conda_smithy\configure_feedstock.py", line 2506, in main
    config = _load_forge_config(forge_dir, exclusive_config_file, forge_yml)
  File "E:\mambaforge\envs\conda-smithy\lib\site-packages\conda_smithy\configure_feedstock.py", line 2114, in _load_forge_config
    remove_file_or_dir(os.path.join(forge_dir, old_file))
  File "E:\mambaforge\envs\conda-smithy\lib\site-packages\conda_smithy\feedstock_io.py", line 70, in remove_file_or_dir
    return remove_file(filename)
  File "E:\mambaforge\envs\conda-smithy\lib\site-packages\conda_smithy\feedstock_io.py", line 83, in remove_file
    repo.index.remove([filename.replace(os.sep, "/")])
  File "E:\mambaforge\envs\conda-smithy\lib\site-packages\git\index\util.py", line 79, in post_clear_cache_if_not_raised
    rval = func(self, *args, **kwargs)
  File "E:\mambaforge\envs\conda-smithy\lib\site-packages\git\index\util.py", line 101, in check_default_index
    return func(self, *args, **kwargs)
  File "E:\mambaforge\envs\conda-smithy\lib\site-packages\git\index\base.py", line 1000, in remove
    paths = self._items_to_rela_paths(items)
  File "E:\mambaforge\envs\conda-smithy\lib\site-packages\git\index\base.py", line 944, in _items_to_rela_paths
    paths.append(self._to_relative_path(item))
  File "E:\mambaforge\envs\conda-smithy\lib\site-packages\git\index\base.py", line 649, in _to_relative_path
    raise ValueError("Absolute path %r is not in git repository at %r" % (path, self.repo.working_tree_dir))
ValueError: Absolute path 'E:/GitHub/cNoNim/sfml-feedstock/disabled_appveyor.yml' is not in git repository at 'E:\\GitHub\\cNoNim\\sfml-feedstock'
(conda-smithy) (conda-smithy) PS E:\GitHub\cNoNim\sfml-feedstock>
```
