### ISSUE TITLE
conda smithy init fails on windows

### ISSUE THREAD

**Issue by melund** [conda-forge/conda-smithy#157]
I think this line https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/cli.py#L46 needs some commas ',' between the arguments. 

```
git: 'update-index--chmod=+xci_support/run_docker_build.sh' is not a git command. See 'git --help'.
Traceback (most recent call last):
  File "C:\Users\mel\Anaconda3\Scripts\conda-smithy-script.py", line 9, in <module>
    load_entry_point('conda-smithy==0.9.2', 'console_scripts', 'conda-smithy')()
  File "C:\Users\mel\Anaconda3\lib\site-packages\conda_smithy\cli.py", line 228, in main
    args.subcommand_func(args)
  File "C:\Users\mel\Anaconda3\lib\site-packages\conda_smithy\cli.py", line 103, in __call__
    create_git_repo(feedstock_directory, msg)
  File "C:\Users\mel\Anaconda3\lib\site-packages\conda_smithy\cli.py", line 46, in create_git_repo
    subprocess.check_call(['git', 'update-index' '--chmod=+x' 'ci_support/run_docker_build.sh'], cwd=target)
  File "C:\Users\mel\Anaconda3\lib\subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'update-index--chmod=+xci_support/run_docker_build.sh']' returned non-zero exit status 1
```

**Comment by janschulz** [comment]
yep. Wanne do the PR? :-)

**Comment by melund** [comment]
No problem. https://github.com/conda-forge/conda-smithy/pull/158
