### ISSUE TITLE
python 10 weirdness in ci-setup

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-smithy#1592]
Here is the rerendering error I get:

```
NFO:conda_smithy.configure_feedstock:Applying migrations: /tmp/tmp3ek1upcl/conda-forge-ci-setup-feedstock/.ci_support/migrations/cuda111_112.yaml,/tmp/tmp3ek1upcl/conda-forge-ci-setup-feedstock/.ci_support/migrations/windows_cuda111_112.yaml,/tmp/tmp14n6d994/share/conda-forge/migrations/python310.yaml
Traceback (most recent call last):
  File "/opt/conda/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/conda_smithy/cli.py", line 681, in main
    args.subcommand_func(args)
  File "/opt/conda/lib/python3.8/site-packages/conda_smithy/cli.py", line 486, in __call__
    self._call(args, tmpdir)
  File "/opt/conda/lib/python3.8/site-packages/conda_smithy/cli.py", line 491, in _call
    configure_feedstock.main(
  File "/opt/conda/lib/python3.8/site-packages/conda_smithy/configure_feedstock.py", line 2230, in main
    render_azure(env, config, forge_dir, return_metadata=True)
  File "/opt/conda/lib/python3.8/site-packages/conda_smithy/configure_feedstock.py", line 1365, in render_azure
    return _render_ci_provider(
  File "/opt/conda/lib/python3.8/site-packages/conda_smithy/configure_feedstock.py", line 632, in _render_ci_provider
    migrated_combined_variant_spec = migrate_combined_spec(
  File "/opt/conda/lib/python3.8/site-packages/conda_smithy/configure_feedstock.py", line 565, in migrate_combined_spec
    combined_spec = variant_add(combined_spec, migration)
  File "/opt/conda/lib/python3.8/site-packages/conda_smithy/variant_algebra.py", line [292](https://github.com/conda-forge/conda-forge-ci-setup-feedstock/runs/5266299108?check_suite_focus=true#step:3:292), in variant_add
    joint_variant[k] = variant_key_add(
  File "/opt/conda/lib/python3.8/site-packages/conda_smithy/variant_algebra.py", line 90, in variant_key_add
    if _version_order(e_l, ordering) < _version_order(e_r, ordering):
  File "/opt/conda/lib/python3.8/site-packages/conda_smithy/variant_algebra.py", line 66, in _version_order
    return ordering.index(v)
ValueError: '10' is not in list
```

xref: https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/186
xref: https://github.com/conda-forge/conda-forge-ci-setup-feedstock/runs/5266299108?check_suite_focus=true

**Comment by beckermr** [comment]
code versions:

```
 - conda-build                       3.21.7  py38h578d9bd_0  installed                      
  + conda-build                       3.21.8  py38h578d9bd_0  conda-forge/linux-64     573 KB
  - conda-forge-pinning  2021.12.11.20.48.53  hd8ed1ab_0      installed                      
  + conda-forge-pinning  2022.02.19.23.26.53  hd8ed1ab_0      conda-forge/noarch        19 KB
  - conda-smithy                      3.15.1  pyhd8ed1ab_0    installed                      
  + conda-smithy                      3.17.1  pyhd8ed1ab_0    conda-forge/noarch        79 KB
```

**Comment by gmarkall** [comment]
Is this the same issue as #1850?
