### ISSUE TITLE
token rotation on new feedstocks failing

### ISSUE THREAD

**Issue by mfansler** [conda-forge/conda-smithy#1595]
Feedstock generation is not working on `staged-recipes`. The `Create feedstocks` GHA runs show failure during the command

```
conda smithy rotate-binstar-token --without-appveyor --without-azure --token_name STAGING_BINSTAR_TOKEN
```

An example can be found [here](https://github.com/conda-forge/staged-recipes/runs/5266603387?check_suite_focus=true#step:6:1767) (step 6, line 1767). And here's a snippet, since that link doesn't always appear to leap to the anchor:

```
2022-02-20T20:36:09.9370514Z making the feedstock token and adding the staging binstar token
2022-02-20T20:36:10.6339380Z Updating the anaconda/binstar token. Can take up to ~30 seconds.
2022-02-20T20:36:10.6345228Z No appveyor token. Create a token at https://ci.appveyor.com/api-token and
2022-02-20T20:36:10.6345801Z Put one in ~/.conda-smithy/appveyor.token
2022-02-20T20:36:12.0918584Z Traceback (most recent call last):
2022-02-20T20:36:12.0919562Z   File "/home/runner/Mambaforge/bin/conda-smithy", line 10, in <module>
2022-02-20T20:36:12.0920117Z     sys.exit(main())
2022-02-20T20:36:12.0920783Z   File "/home/runner/Mambaforge/lib/python3.9/site-packages/conda_smithy/cli.py", line 681, in main
2022-02-20T20:36:12.0921314Z     args.subcommand_func(args)
2022-02-20T20:36:12.0921986Z   File "/home/runner/Mambaforge/lib/python3.9/site-packages/conda_smithy/cli.py", line 911, in __call__
2022-02-20T20:36:12.0922510Z     rotate_anaconda_token(
2022-02-20T20:36:12.0923258Z   File "/home/runner/Mambaforge/lib/python3.9/site-packages/conda_smithy/anaconda_token_rotation.py", line 192, in rotate_anaconda_token
2022-02-20T20:36:12.0923820Z     raise RuntimeError(err_msg)
2022-02-20T20:36:12.0924535Z RuntimeError: Failed to rotate token for conda-forge/openfermionpyscf-feedstock on github actions!
2022-02-20T20:36:12.1794427Z Traceback (most recent call last):
2022-02-20T20:36:12.1795851Z   File "/home/runner/work/staged-recipes/staged-recipes/.travis_scripts/create_feedstocks.py", line 313, in <module>
2022-02-20T20:36:12.1796152Z 
2022-02-20T20:36:12.1796589Z     subprocess.check_call(
2022-02-20T20:36:12.1799136Z   File "/home/runner/Mambaforge/lib/python3.9/subprocess.py", line 373, in check_call
2022-02-20T20:36:12.1799671Z     raise CalledProcessError(retcode, cmd)
2022-02-20T20:36:12.1802905Z subprocess.CalledProcessError: Command '['conda', 'smithy', 'rotate-binstar-token', '--without-appveyor', '--without-azure', '--token_name', 'STAGING_BINSTAR_TOKEN']' returned non-zero exit status 1.
2022-02-20T20:36:12.1805627Z 
```

- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

**Comment by beckermr** [comment]
Xref: https://github.com/conda-forge/staged-recipes/pull/18112
