### ISSUE TITLE
OSX conda-forge CI failing on installing 'python-libarchive'

### ISSUE THREAD

**Issue by artanokhov** [conda-forge/conda-smithy#1741]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Currently we observe issue with installing mamba packages on OSX platform
https://github.com/conda-forge/openvino-feedstock/runs/14789758256

Re-render doesn't help
https://github.com/conda-forge/openvino-feedstock/pull/8/checks?check_run_id=14790056392

```
+ mamba install --update-specs --quiet --yes --channel conda-forge conda-build pip boa conda-forge-ci-setup=3
critical libmamba Pathname can't be converted from UTF-8 to current locale.
error    libmamba Error opening for reading "/Users/runner/miniforge3/pkgs/python-libarchive-c-5.0-py310h2ec42d9_0/info/index.json": No such file or directory
error    libmamba Error when extracting package: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
Found incorrect download: python-libarchive-c. Aborting

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/runner/miniforge3/lib/python3.10/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "/Users/runner/miniforge3/lib/python3.10/site-packages/mamba/mamba.py", line 941, in exception_converter
        raise e
      File "/Users/runner/miniforge3/lib/python3.10/site-packages/mamba/mamba.py", line 934, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/Users/runner/miniforge3/lib/python3.10/site-packages/mamba/mamba.py", line 892, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/Users/runner/miniforge3/lib/python3.10/site-packages/mamba/mamba.py", line 754, in do_call
        exit_code = install(args, parser, "install")
      File "/Users/runner/miniforge3/lib/python3.10/site-packages/mamba/mamba.py", line 588, in install
        transaction.fetch_extract_packages()
    RuntimeError: Found incorrect download: python-libarchive-c. Aborting
```

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by ilya-lavrenov** [comment]
The same issue with xbyak https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=739910&view=logs&jobId=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b

**Comment by xhochy** [comment]
See https://github.com/conda-forge/status/issues/149 for the main issue.
