### ISSUE TITLE
conda-smithy fails to rerender for older feedstock (conda-forge/pyhf-feedstock)

### ISSUE THREAD

**Issue by matthewfeickert** [conda-forge/conda-smithy#1842]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

For https://github.com/conda-forge/pyhf-feedstock/ I want to be able to build locally to test with multiple cores (so not using `build-locally.py` which uses 1) using a Bash script like

```console
$ cat recipe/build_local.sh
```
```bash 
#!/bin/bash

docker system prune -f

# repository top level
cd ..

rm -rf \
    build_artifacts \
    build.log
mkdir -p build_artifacts/{noarch,linux-64}/

export CONFIG=linux64
export DOCKER_IMAGE=quay.io/condaforge/linux-anvil-cos7-x86_64
export AZURE=False
export CPU_COUNT="$(nproc --ignore 4)"

.scripts/run_docker_build.sh | tee build.log
```

However, when I do so I realize that the feedstock is old enough that there is no `.ci_support/linux64.yaml` but instead [`.ci_support/linux_64_.yaml`](https://github.com/conda-forge/pyhf-feedstock/blob/d655e7955c7ad90c796d7604334cea668559fd12/.ci_support/linux_64_.yaml) and all of `.ci_support` has failed to get automatically updated over the years in rerenders.

If I clone the repository

```console
$ git clone git@github.com:conda-forge/pyhf-feedstock.git
$ cd pyhf-feedstock
```

make a new `micromamba` env with `conda-smithy` in it

```console
$ micromamba env create --name conda-smithy-rerender conda-smithy
$ micromamba activate conda-smithy-rerender
$ micromamba list | grep conda-smithy
List of packages in environment: "/home/feickert/micromamba/envs/conda-smithy-rerender"
  conda-smithy               3.30.4               pyhd8ed1ab_0        conda-forge
```

and then try to rerender the whole feedstock to update the CI support configs this fails

```
$ conda smithy rerender -c auto
```
```pytb
Traceback (most recent call last):
  File "/home/feickert/micromamba/envs/conda-smithy-rerender/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/feickert/micromamba/envs/conda-smithy-rerender/lib/python3.11/site-packages/conda_smithy/cli.py", line 724, in main
    args.subcommand_func(args)
  File "/home/feickert/micromamba/envs/conda-smithy-rerender/lib/python3.11/site-packages/conda_smithy/cli.py", line 584, in __call__
    self._call(args, tmpdir)
  File "/home/feickert/micromamba/envs/conda-smithy-rerender/lib/python3.11/site-packages/conda_smithy/cli.py", line 589, in _call
    configure_feedstock.main(
  File "/home/feickert/micromamba/envs/conda-smithy-rerender/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py", line 2506, in main
    config = _load_forge_config(forge_dir, exclusive_config_file, forge_yml)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/feickert/micromamba/envs/conda-smithy-rerender/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py", line 2114, in _load_forge_config
    remove_file_or_dir(os.path.join(forge_dir, old_file))
  File "/home/feickert/micromamba/envs/conda-smithy-rerender/lib/python3.11/site-packages/conda_smithy/feedstock_io.py", line 70, in remove_file_or_dir
    return remove_file(filename)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/feickert/micromamba/envs/conda-smithy-rerender/lib/python3.11/site-packages/conda_smithy/feedstock_io.py", line 79, in remove_file
    touch_file(filename)
  File "/home/feickert/micromamba/envs/conda-smithy-rerender/lib/python3.11/site-packages/conda_smithy/feedstock_io.py", line 64, in touch_file
    with write_file(filename) as fh:
  File "/home/feickert/micromamba/envs/conda-smithy-rerender/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/feickert/micromamba/envs/conda-smithy-rerender/lib/python3.11/site-packages/conda_smithy/feedstock_io.py", line 60, in write_file
    repo.index.add([filename])
  File "/home/feickert/micromamba/envs/conda-smithy-rerender/lib/python3.11/site-packages/git/index/base.py", line 921, in add
    self.entries[(entry.path, 0)] = IndexEntry.from_base(entry)
    ^^^^^^^^^^^^
  File "/home/feickert/micromamba/envs/conda-smithy-rerender/lib/python3.11/site-packages/gitdb/util.py", line 253, in __getattr__
    self._set_cache_(attr)
  File "/home/feickert/micromamba/envs/conda-smithy-rerender/lib/python3.11/site-packages/git/index/base.py", line 179, in _set_cache_
    self._deserialize(stream)
  File "/home/feickert/micromamba/envs/conda-smithy-rerender/lib/python3.11/site-packages/git/index/base.py", line 208, in _deserialize
    self.version, self.entries, self._extension_data, _conten_sha = read_cache(stream)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/home/feickert/micromamba/envs/conda-smithy-rerender/lib/python3.11/site-packages/git/index/fun.py", line 244, in read_cache
    version, num_entries = read_header(stream)
                           ^^^^^^^^^^^^^^^^^^^
  File "/home/feickert/micromamba/envs/conda-smithy-rerender/lib/python3.11/site-packages/git/index/fun.py", line 208, in read_header
    assert version in (1, 2)
           ^^^^^^^^^^^^^^^^^
AssertionError
```

How should I rerender the feedstock to get around this? I ask for `@conda-forge-admin, please rerender` in each version update PR (c.f. https://github.com/conda-forge/pyhf-feedstock/pull/24#issuecomment-1879223262) but this isn't updating the `.ci_support`.

I've checked https://conda-forge.org/docs/user/ci-skeleton/#keeping-up-to-date and am following the instructions.

### Installed packages

```shell
List of packages in environment: "/home/feickert/micromamba/envs/conda-smithy-rerender"

  Name                       Version              Build               Channel    
───────────────────────────────────────────────────────────────────────────────────
  _libgcc_mutex              0.1                  conda_forge         conda-forge
  _openmp_mutex              4.5                  2_gnu               conda-forge
  anyio                      4.2.0                pyhd8ed1ab_0        conda-forge
  archspec                   0.2.2                pyhd8ed1ab_0        conda-forge
  attrs                      23.2.0               pyh71513ae_0        conda-forge
  beautifulsoup4             4.12.3               pyha770c72_0        conda-forge
  blinker                    1.7.0                pyhd8ed1ab_0        conda-forge
  boltons                    23.1.1               pyhd8ed1ab_0        conda-forge
  boolean.py                 4.0                  pyhd8ed1ab_0        conda-forge
  brotli-python              1.1.0                py311hb755f60_1     conda-forge
  bzip2                      1.0.8                hd590300_5          conda-forge
  c-ares                     1.26.0               hd590300_0          conda-forge
  ca-certificates            2024.2.2             hbcca054_0          conda-forge
  certifi                    2024.2.2             pyhd8ed1ab_0        conda-forge
  cffi                       1.16.0               py311hb3a22ac_0     conda-forge
  chardet                    5.2.0                py311h38be061_1     conda-forge
  charset-normalizer         3.3.2                pyhd8ed1ab_0        conda-forge
  cirun                      0.30                 pyhd8ed1ab_0        conda-forge
  click                      8.1.7                unix_pyh707e725_0   conda-forge
  colorama                   0.4.6                pyhd8ed1ab_0        conda-forge
  conda                      24.1.1               py311h38be061_0     conda-forge
  conda-build                24.1.2               py311h38be061_0     conda-forge
  conda-forge-pinning        2024.02.18.16.07.42  hd8ed1ab_0          conda-forge
  conda-index                0.4.0                pyhd8ed1ab_0        conda-forge
  conda-libmamba-solver      24.1.0               pyhd8ed1ab_0        conda-forge
  conda-package-handling     2.2.0                pyh38be061_0        conda-forge
  conda-package-streaming    0.9.0                pyhd8ed1ab_0        conda-forge
  conda-smithy               3.30.4               pyhd8ed1ab_0        conda-forge
  cryptography               42.0.3               py311h63ff55d_0     conda-forge
  curl                       8.5.0                hca28451_0          conda-forge
  dbus                       1.13.6               h5008d03_3          conda-forge
  deprecated                 1.2.14               pyh1a96a4e_0        conda-forge
  distlib                    0.3.8                pyhd8ed1ab_0        conda-forge
  distro                     1.9.0                pyhd8ed1ab_0        conda-forge
  editables                  0.5                  pyhd8ed1ab_0        conda-forge
  exceptiongroup             1.2.0                pyhd8ed1ab_2        conda-forge
  expat                      2.5.0                hcb278e6_1          conda-forge
  filelock                   3.13.1               pyhd8ed1ab_0        conda-forge
  fmt                        10.2.1               h00ab1b0_0          conda-forge
  gettext                    0.21.1               h27087fc_0          conda-forge
  git                        2.43.0               pl5321h7bc287a_0    conda-forge
  gitdb                      4.0.11               pyhd8ed1ab_0        conda-forge
  gitpython                  3.1.42               pyhd8ed1ab_0        conda-forge
  gmp                        6.3.0                h59595ed_0          conda-forge
  h11                        0.14.0               pyhd8ed1ab_0        conda-forge
  h2                         4.1.0                pyhd8ed1ab_0        conda-forge
  hatch                      1.9.2                pyhd8ed1ab_0        conda-forge
  hatchling                  1.21.1               pyhd8ed1ab_0        conda-forge
  hpack                      4.0.0                pyh9f0ad1d_0        conda-forge
  httpcore                   1.0.3                pyhd8ed1ab_0        conda-forge
  httpx                      0.26.0               pyhd8ed1ab_0        conda-forge
  hyperframe                 6.0.1                pyhd8ed1ab_0        conda-forge
  hyperlink                  21.0.0               pyhd3deb0d_0        conda-forge
  icu                        73.2                 h59595ed_0          conda-forge
  idna                       3.6                  pyhd8ed1ab_0        conda-forge
  importlib-metadata         7.0.1                pyha770c72_0        conda-forge
  importlib_metadata         7.0.1                hd8ed1ab_0          conda-forge
  importlib_resources        6.1.1                pyhd8ed1ab_0        conda-forge
  isodate                    0.6.1                pyhd8ed1ab_0        conda-forge
  jaraco.classes             3.3.1                pyhd8ed1ab_0        conda-forge
  jeepney                    0.8.0                pyhd8ed1ab_0        conda-forge
  jinja2                     3.1.3                pyhd8ed1ab_0        conda-forge
  jsonpatch                  1.33                 pyhd8ed1ab_0        conda-forge
  jsonpointer                2.4                  py311h38be061_3     conda-forge
  jsonschema                 4.21.1               pyhd8ed1ab_0        conda-forge
  jsonschema-specifications  2023.12.1            pyhd8ed1ab_0        conda-forge
  keyring                    24.3.0               py311h38be061_0     conda-forge
  keyutils                   1.6.1                h166bdaf_0          conda-forge
  krb5                       1.21.2               h659d440_0          conda-forge
  ld_impl_linux-64           2.40                 h41732ed_0          conda-forge
  libarchive                 3.7.2                h2aa1ff5_1          conda-forge
  libcurl                    8.5.0                hca28451_0          conda-forge
  libedit                    3.1.20191231         he28a2e2_2          conda-forge
  libev                      4.33                 hd590300_2          conda-forge
  libexpat                   2.5.0                hcb278e6_1          conda-forge
  libffi                     3.4.2                h7f98852_5          conda-forge
  libgcc-ng                  13.2.0               h807b86a_5          conda-forge
  libglib                    2.78.4               h783c2da_0          conda-forge
  libgomp                    13.2.0               h807b86a_5          conda-forge
  libiconv                   1.17                 hd590300_2          conda-forge
  liblief                    0.12.3               h27087fc_0          conda-forge
  libmamba                   1.5.6                had39da4_0          conda-forge
  libmambapy                 1.5.6                py311hf2555c7_0     conda-forge
  libnghttp2                 1.58.0               h47da74e_1          conda-forge
  libnsl                     2.0.1                hd590300_0          conda-forge
  libsodium                  1.0.18               h36c2ea0_1          conda-forge
  libsolv                    0.7.28               hfc55251_0          conda-forge
  libsqlite                  3.45.1               h2797004_0          conda-forge
  libssh2                    1.11.0               h0841786_0          conda-forge
  libstdcxx-ng               13.2.0               h7e041cc_5          conda-forge
  libuuid                    2.38.1               h0b41bf4_0          conda-forge
  libxcrypt                  4.4.36               hd590300_1          conda-forge
  libxml2                    2.12.5               h232c23b_0          conda-forge
  libzlib                    1.2.13               hd590300_5          conda-forge
  license-expression         30.1.1               pyhd8ed1ab_0        conda-forge
  lz4-c                      1.9.4                hcb278e6_0          conda-forge
  lzo                        2.10                 h516909a_1000       conda-forge
  markdown-it-py             3.0.0                pyhd8ed1ab_0        conda-forge
  markupsafe                 2.1.5                py311h459d7ec_0     conda-forge
  mdurl                      0.1.2                pyhd8ed1ab_0        conda-forge
  menuinst                   2.0.2                py311h38be061_0     conda-forge
  more-itertools             10.2.0               pyhd8ed1ab_0        conda-forge
  msrest                     0.6.21               pyh44b312d_0        conda-forge
  ncurses                    6.4                  h59595ed_2          conda-forge
  oauthlib                   3.2.2                pyhd8ed1ab_0        conda-forge
  openssl                    3.2.1                hd590300_0          conda-forge
  packaging                  23.2                 pyhd8ed1ab_0        conda-forge
  patch                      2.7.6                h7f98852_1002       conda-forge
  patchelf                   0.17.2               h58526e2_0          conda-forge
  pathspec                   0.12.1               pyhd8ed1ab_0        conda-forge
  pcre2                      10.42                hcad00b1_0          conda-forge
  perl                       5.32.1               7_hd590300_perl5    conda-forge
  pexpect                    4.9.0                pyhd8ed1ab_0        conda-forge
  pip                        24.0                 pyhd8ed1ab_0        conda-forge
  pkginfo                    1.9.6                pyhd8ed1ab_0        conda-forge
  pkgutil-resolve-name       1.3.10               pyhd8ed1ab_1        conda-forge
  platformdirs               4.2.0                pyhd8ed1ab_0        conda-forge
  pluggy                     1.4.0                pyhd8ed1ab_0        conda-forge
  psutil                     5.9.8                py311h459d7ec_0     conda-forge
  ptyprocess                 0.7.0                pyhd3deb0d_0        conda-forge
  py-lief                    0.12.3               py311ha362b79_0     conda-forge
  pybind11-abi               4                    hd8ed1ab_3          conda-forge
  pycosat                    0.6.6                py311h459d7ec_0     conda-forge
  pycparser                  2.21                 pyhd8ed1ab_0        conda-forge
  pycryptodome               3.20.0               py311h6601440_0     conda-forge
  pygithub                   2.2.0                pyhd8ed1ab_0        conda-forge
  pygments                   2.17.2               pyhd8ed1ab_0        conda-forge
  pyjwt                      2.8.0                pyhd8ed1ab_1        conda-forge
  pynacl                     1.5.0                py311h459d7ec_3     conda-forge
  pysocks                    1.7.1                pyha2e5f31_6        conda-forge
  python                     3.11.8               hab00c5b_0_cpython  conda-forge
  python-dateutil            2.8.2                pyhd8ed1ab_0        conda-forge
  python-libarchive-c        5.0                  py311h38be061_2     conda-forge
  python_abi                 3.11                 4_cp311             conda-forge
  pytz                       2024.1               pyhd8ed1ab_0        conda-forge
  pyyaml                     6.0.1                py311h459d7ec_1     conda-forge
  readline                   8.2                  h8228510_1          conda-forge
  referencing                0.33.0               pyhd8ed1ab_0        conda-forge
  reproc                     14.2.4.post0         hd590300_1          conda-forge
  reproc-cpp                 14.2.4.post0         h59595ed_1          conda-forge
  requests                   2.31.0               pyhd8ed1ab_0        conda-forge
  requests-oauthlib          1.3.1                pyhd8ed1ab_0        conda-forge
  rich                       13.7.0               pyhd8ed1ab_0        conda-forge
  ripgrep                    14.1.0               he8a937b_0          conda-forge
  rpds-py                    0.18.0               py311h46250e7_0     conda-forge
  ruamel.yaml                0.18.6               py311h459d7ec_0     conda-forge
  ruamel.yaml.clib           0.2.8                py311h459d7ec_0     conda-forge
  scrypt                     0.8.20               py311h6965a6d_1     conda-forge
  secretstorage              3.3.3                py311h38be061_2     conda-forge
  setuptools                 69.1.0               pyhd8ed1ab_0        conda-forge
  shellingham                1.5.4                pyhd8ed1ab_0        conda-forge
  six                        1.16.0               pyh6c4a22f_0        conda-forge
  smmap                      5.0.0                pyhd8ed1ab_0        conda-forge
  sniffio                    1.3.0                pyhd8ed1ab_0        conda-forge
  soupsieve                  2.5                  pyhd8ed1ab_1        conda-forge
  tk                         8.6.13               noxft_h4845f30_101  conda-forge
  tomli                      2.0.1                pyhd8ed1ab_0        conda-forge
  tomli-w                    1.0.0                pyhd8ed1ab_0        conda-forge
  tomlkit                    0.12.3               pyha770c72_0        conda-forge
  toolz                      0.12.1               pyhd8ed1ab_0        conda-forge
  tqdm                       4.66.2               pyhd8ed1ab_0        conda-forge
  trove-classifiers          2024.1.31            pyhd8ed1ab_0        conda-forge
  truststore                 0.8.0                pyhd8ed1ab_0        conda-forge
  typer                      0.9.0                pyhd8ed1ab_0        conda-forge
  typing-extensions          4.9.0                hd8ed1ab_0          conda-forge
  typing_extensions          4.9.0                pyha770c72_0        conda-forge
  tzdata                     2024a                h0c530f3_0          conda-forge
  urllib3                    2.2.1                pyhd8ed1ab_0        conda-forge
  userpath                   1.7.0                pyhd8ed1ab_0        conda-forge
  virtualenv                 20.25.0              pyhd8ed1ab_0        conda-forge
  vsts-python-api            0.1.25               pyhd8ed1ab_1        conda-forge
  wheel                      0.42.0               pyhd8ed1ab_0        conda-forge
  wrapt                      1.16.0               py311h459d7ec_0     conda-forge
  xz                         5.2.6                h166bdaf_0          conda-forge
  yaml                       0.2.5                h7f98852_2          conda-forge
  yaml-cpp                   0.8.0                h59595ed_0          conda-forge
  zipp                       3.17.0               pyhd8ed1ab_0        conda-forge
  zstandard                  0.22.0               py311haa97af0_0     conda-forge
  zstd                       1.5.5                hfc55251_0          conda-forge
```

### Environment info

```shell
libmamba version : 1.5.6
     micromamba version : 1.5.6
           curl version : libcurl/8.5.0 OpenSSL/3.2.0 zlib/1.2.13 zstd/1.5.5 libssh2/1.11.0 nghttp2/1.58.0
     libarchive version : libarchive 3.7.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.5
       envs directories : /home/feickert/micromamba/envs
          package cache : /home/feickert/micromamba/pkgs
                          /home/feickert/.mamba/pkgs
            environment : conda-smithy-rerender (active)
           env location : /home/feickert/micromamba/envs/conda-smithy-rerender
      user config files : /home/feickert/.mambarc
 populated config files : /home/feickert/.condarc
       virtual packages : __unix=0=0
                          __linux=6.5.0=0
                          __glibc=2.35=0
                          __archspec=1=x86_64-v3
                          __cuda=12.2=0
               channels : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/nodefaults/linux-64
                          https://conda.anaconda.org/nodefaults/noarch
       base environment : /home/feickert/micromamba
               platform : linux-64
```

**Comment by matthewfeickert** [comment]
cc @chrisburr in the event you see me doing something obviously wrong.

**Comment by matthewfeickert** [comment]
:wave: @h-vetinari @beckermr @isuruf While I know that you're all busy with a multitude of other things, if you have any thoughts on this, or suggestions of other docs to read that might point me towards the right direction that would be useful.

**Comment by jakirkham** [comment]
Let's see what happens if we we ask the bot to try: https://github.com/conda-forge/pyhf-feedstock/issues/25

**Comment by jakirkham** [comment]
What is the result of these two commands (note `-` in 2nd case)?

```sh
conda smithy --version
conda-smithy --version
```

If these differ, it would suggest there is a `conda-smithy` installed in `base` (that may be fairly out-of-date). Using the `-` would ensure it comes from the active environment

**Comment by matthewfeickert** [comment]
> What is the result of these two commands (note `-` in 2nd case)?
> 
> ```shell
> conda smithy --version
> conda-smithy --version
> ```

```console
$ micromamba activate conda-smithy-rerender
$ command -v conda
/home/feickert/micromamba/envs/conda-smithy-rerender/bin/conda
$ command -v conda-smithy
/home/feickert/micromamba/envs/conda-smithy-rerender/bin/conda-smithy
$ conda smithy --version
3.30.4
$ conda-smithy --version
3.30.4
```



I get the same error that I originally posted about if I also try to use `conda-smithy` via `pixi global`

```console
$ pixi global upgrade conda-smithy
Nothing to upgrade
$ command -v conda-smithy
/home/feickert/.pixi/bin/conda-smithy
$ conda-smithy --version
3.35.0
```

> Let's see what happens if we we ask the bot to try: [conda-forge/pyhf-feedstock#25](https://github.com/conda-forge/pyhf-feedstock/issues/25)
> 
> Edit: Looks like the bot was able to re-render: [conda-forge/pyhf-feedstock#26](https://github.com/conda-forge/pyhf-feedstock/pull/26)

Indeed! Thanks @jakirkham! I didn't know that I could do this via opening a new Issue with the command, as this isn't mentioned anywhere in the [Using conda-smithy to manage your CI section of the conda-forge docs](https://conda-forge.org/docs/user/ci-skeleton/). Is this documented anywhere?

**Comment by matthewfeickert** [comment]
> I didn't know that I could do this via opening a new Issue with the command, as this isn't mentioned anywhere in the [Using conda-smithy to manage your CI section of the conda-forge docs](https://conda-forge.org/docs/user/ci-skeleton/). Is this documented anywhere?

Ah yes: https://conda-forge.org/docs/maintainer/infrastructure/#conda-forge-admin-please-rerender

**Comment by matthewfeickert** [comment]
So this particular issue is addressed in now resolved by https://github.com/conda-forge/pyhf-feedstock/pull/26, though it still seems like there was some bug or subtle environmental issue that wasn't made clear from the errors. That being said, I think that this is probably not worth time chasing down given that things like https://github.com/conda-forge/pyhf-feedstock/issues/25 are possible, so I'm going to close this.

If the `conda-smithy` maintainers disagree and would prefer for this to stay open that's fine. Thanks very much for the help. :+1:

**Comment by jakirkham** [comment]
Thanks Matthew! 🙏

This is good feedback

Honestly this section "Using conda-smithy to manage your CI" arguably doesn't even belong in "User Documentation". It is really targeting a user that wants to configure feedstocks outside of conda-forge, which is an advanced use case. Will make a note of this

Yeah we do cover re-rendring in the docs. Typically we point users to [this doc on re-rendering]( https://conda-forge.org/docs/maintainer/updating_pkgs/#rerendering-feedstocks ), which explains how to use the bot (with a link to the page you found) and how to re-render locally)

We try to add links to that re-rendering page in various other places (issue & PR templates, linter comments, etc.). However as you have kindly demonstrated, this still isn't quite as discoverable for the new user. So we still have work to do on improving discoverability (tbh I think this is almost always true with docs). Fortunately we have been doing a lot of doc grooming (maybe you have noticed? 😉) so this is good timing. Hopefully we can make this better with your feedback 🙂
