### ISSUE TITLE
Overnight fail of `setup_conda_rc`

### ISSUE THREAD

**Issue by MementoRC** [conda-forge/conda-smithy#1980]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Now, when running `python build-locally.py` for a recipe I am working on (worked 10hrs ago), `setup_conda_rc` fails with:
```
Configuring conda
+ export PYTHONUNBUFFERED=1
+ PYTHONUNBUFFERED=1
+ export RECIPE_ROOT=/home/conda/recipe_root
+ RECIPE_ROOT=/home/conda/recipe_root
+ export CI_SUPPORT=/home/conda/feedstock_root/.ci_support
+ CI_SUPPORT=/home/conda/feedstock_root/.ci_support
+ export CONFIG_FILE=/home/conda/feedstock_root/.ci_support/linux_64_.yaml
+ CONFIG_FILE=/home/conda/feedstock_root/.ci_support/linux_64_.yaml
+ cat
+ export CONDA_LIBMAMBA_SOLVER_NO_CHANNELS_FROM_INSTALLED=1
+ CONDA_LIBMAMBA_SOLVER_NO_CHANNELS_FROM_INSTALLED=1
+ mamba install --update-specs --yes --quiet --channel conda-forge --strict-channel-priority pip mamba conda-build conda-forge-ci-setup=4 'conda-build>=24.1'
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
+ mamba update --update-specs --yes --quiet --channel conda-forge --strict-channel-priority pip mamba conda-build conda-forge-ci-setup=4 'conda-build>=24.1'
+ setup_conda_rc /home/conda/feedstock_root /home/conda/recipe_root /home/conda/feedstock_root/.ci_support/linux_64_.yaml
Traceback (most recent call last):
  File "/opt/conda/bin/setup_conda_rc", line 7, in <module>
    from conda_forge_ci_setup.build_utils import setup_conda_rc
  File "/opt/conda/lib/python3.10/site-packages/conda_forge_ci_setup/build_utils.py", line 15, in <module>
    from conda_forge_ci_setup.upload_or_check_non_existence import retry_upload_or_check
  File "/opt/conda/lib/python3.10/site-packages/conda_forge_ci_setup/upload_or_check_non_existence.py", line 18, in <module>
    import rattler_build_conda_compat.render
  File "/opt/conda/lib/python3.10/site-packages/rattler_build_conda_compat/render.py", line 23, in <module>
    from rattler_build_conda_compat.loader import parse_recipe_config_file
  File "/opt/conda/lib/python3.10/site-packages/rattler_build_conda_compat/loader.py", line 4, in <module>
    from typing import TYPE_CHECKING, Any, Iterator, Self
ImportError: cannot import name 'Self' from 'typing' (/opt/conda/lib/python3.10/typing.py)
```

### Installed packages

```shell
Used: `Status: Downloaded newer image for quay.io/condaforge/linux-anvil-alma-x86_64:8`
```

### Environment info

```shell
active environment : python-3.11
    active env location : /home/memento/.conda/envs/python-3.11
            shell level : 2
       user config file : /home/memento/.condarc
 populated config files : /home/memento/.condarc
          conda version : 24.1.2
    conda-build version : not installed
         python version : 3.10.13.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=zen2
                          __conda=24.1.2=0
                          __glibc=2.31=0
                          __linux=5.18.0=0
                          __unix=0=0
       base environment : /opt/conda  (read only)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/memento/.conda/pkgs
       envs directories : /home/memento/.conda/envs
                          /opt/conda/envs
               platform : linux-64
             user-agent : conda/24.1.2 requests/2.31.0 CPython/3.10.13 Linux/5.18.0-0.deb11.4-amd64 debian/11.7 glibc/2.31 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.6
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by MementoRC** [comment]
This seems to be resolved with a `conda update -n base conda`

**Comment by jakirkham** [comment]
Sounds like this org wide issue ( https://github.com/conda-forge/status/issues/183 ), which was recently resolved
