### ISSUE TITLE
No CircleCI Token

### ISSUE THREAD

**Issue by scopatz** [conda-forge/conda-smithy#2]
When trying to get smithy help on the command line, I see the following:

```console
scopatz@athenaie ~ $ conda smithy -h
Traceback (most recent call last):
  File "/home/scopatz/.local/bin/conda-smithy", line 4, in <module>
    __import__('pkg_resources').run_script('conda-smithy==0.1.0.dev0', 'conda-smithy')
  File "/home/scopatz/miniconda3/lib/python3.4/site-packages/setuptools-18.0.1-py3.4.egg/pkg_resources/__init__.py", line 735, in run_script
  File "/home/scopatz/miniconda3/lib/python3.4/site-packages/setuptools-18.0.1-py3.4.egg/pkg_resources/__init__.py", line 1652, in run_script
  File "/home/scopatz/.local/lib/python3.4/site-packages/conda_smithy-0.1.0.dev0-py3.4.egg/EGG-INFO/scripts/conda-smithy", line 10, in <module>
    import conda_smithy.configure_circle_ci as configure_circle_ci
  File "/home/scopatz/.local/lib/python3.4/site-packages/conda_smithy-0.1.0.dev0-py3.4.egg/conda_smithy/configure_circle_ci.py", line 13, in <module>
    with open(os.path.expanduser('~/.conda-smithy/circle.token'), 'r') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/scopatz/.conda-smithy/circle.token'
```

It would be ideal if smithy could ask for the CircleCI username and password and then put the token in the right place.

**Comment by scopatz** [comment]
Same thing happens with appveyor

**Comment by pelson** [comment]
Yep. They were pretty hacky solutions to avoid including my passwords in the repo. Interested in tidying this bit up?

Incidentally I've made a few issues under the umbrella repo https://github.com/conda-forge/conda-forge.github.io. One of those is to take on the auto-registration functionality https://github.com/conda-forge/conda-forge.github.io/issues/4.

**Comment by pelson** [comment]
Incidentally, I don't know if it is because I have a huge backlog of notifications, but I didn't get a notification about this issue, so please ping me via email if I don't reply to others.

**Comment by scopatz** [comment]
Weird.  It says that you are watching the repo...

**Comment by pelson** [comment]
Got a notification this time. Maybe I did get it late last night... :beer: :wink:

**Comment by scopatz** [comment]
Go home, GitHub, you're drunk ;)
