### ISSUE TITLE
v1 recipe linting broken

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-smithy#2067]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Recipe linting for v1 recipes is broken.

```zsh
% pwd                                                
staged-recipes/recipes/example-v1
% conda smithy lint --conda-forge .
Traceback (most recent call last):
  File "/Users/beckermr/mambaforge/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/beckermr/mambaforge/lib/python3.11/site-packages/conda_smithy/cli.py", line 758, in main
    args.subcommand_func(args)
  File "/Users/beckermr/mambaforge/lib/python3.11/site-packages/conda_smithy/cli.py", line 636, in __call__
    lints, hints = linter.main(
                   ^^^^^^^^^^^^
  File "/Users/beckermr/mambaforge/lib/python3.11/site-packages/conda_smithy/lint_recipe.py", line 605, in main
    results, hints = lintify_meta_yaml(
                     ^^^^^^^^^^^^^^^^^^
  File "/Users/beckermr/mambaforge/lib/python3.11/site-packages/conda_smithy/lint_recipe.py", line 213, in lintify_meta_yaml
    conda_recipe_v1_linter.lint_recipe_name(meta, lints)
  File "/Users/beckermr/mambaforge/lib/python3.11/site-packages/conda_smithy/linter/conda_recipe_v1_linter.py", line 133, in lint_recipe_name
    name = get_recipe_name(recipe_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beckermr/mambaforge/lib/python3.11/site-packages/conda_smithy/linter/conda_recipe_v1_linter.py", line 108, in get_recipe_name
    rendered_context_recipe = render_recipe_with_context(recipe_content)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beckermr/mambaforge/lib/python3.11/site-packages/rattler_build_conda_compat/jinja/jinja.py", line 116, in render_recipe_with_context
    template = env.from_string(_dump_yaml_to_string(recipe_content))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beckermr/mambaforge/lib/python3.11/site-packages/jinja2/environment.py", line 1108, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
                               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/beckermr/mambaforge/lib/python3.11/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/Users/beckermr/mambaforge/lib/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 9, in template
jinja2.exceptions.TemplateSyntaxError: Expected an expression, got 'end of print statement'
```

### Installed packages

```shell
# packages in environment at /Users/beckermr/mambaforge:
#
# Name                    Version                   Build  Channel
ads                       0.12.6             pyhd8ed1ab_0    conda-forge
adstex                    0.5.3              pyhd8ed1ab_0    conda-forge
aiofiles                  24.1.0             pyhd8ed1ab_0    conda-forge
aiosqlite                 0.20.0             pyhd8ed1ab_0    conda-forge
anaconda-client           1.12.3             pyhd8ed1ab_1    conda-forge
anaconda-project          0.11.1             pyhd8ed1ab_0    conda-forge
annotated-types           0.7.0              pyhd8ed1ab_0    conda-forge
anyio                     4.5.0              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
appnope                   0.1.4              pyhd8ed1ab_0    conda-forge
archspec                  0.2.3              pyhd8ed1ab_0    conda-forge
argon2-cffi               23.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py311h460d6c5_5    conda-forge
arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
async-lru                 2.0.4              pyhd8ed1ab_0    conda-forge
attrs                     24.2.0             pyh71513ae_0    conda-forge
autoconf                  2.71            pl5321hcd07c0c_1    conda-forge
automake                  1.17            pl5321hce30654_0    conda-forge
azure-core                1.31.0             pyhd8ed1ab_0    conda-forge
babel                     2.14.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_4    conda-forge
backports.functools_lru_cache 2.0.0              pyhd8ed1ab_0    conda-forge
backports.strenum         1.2.8              pyhd8ed1ab_0    conda-forge
backports.tarfile         1.0.0              pyhd8ed1ab_1    conda-forge
beautifulsoup4            4.12.3             pyha770c72_0    conda-forge
bfg                       1.14.0               hce30654_1    conda-forge
bibtexparser              1.4.1              pyhd8ed1ab_0    conda-forge
black                     24.8.0          py311h267d04e_1    conda-forge
bleach                    6.1.0              pyhd8ed1ab_0    conda-forge
blinker                   1.8.2              pyhd8ed1ab_0    conda-forge
boltons                   24.0.0             pyhd8ed1ab_0    conda-forge
boolean.py                4.0                pyhd8ed1ab_0    conda-forge
brotli-python             1.1.0           py311h3f08180_2    conda-forge
brotlipy                  0.7.0           py311h460d6c5_1007    conda-forge
bzip2                     1.0.8                h99b78c6_7    conda-forge
c-ares                    1.33.1               hd74edd7_0    conda-forge
c-compiler                1.7.0                h6aa9301_1    conda-forge
ca-certificates           2024.8.30            hf0a4a13_0    conda-forge
cachecontrol              0.14.0             pyhd8ed1ab_1    conda-forge
cachecontrol-with-filecache 0.14.0             pyhd8ed1ab_1    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachy                     0.3.0              pyhd8ed1ab_1    conda-forge
cctools                   1010.6               h4faf515_1    conda-forge
cctools_osx-arm64         1010.6               h4f2c9d0_1    conda-forge
certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
cffi                      1.17.1          py311h3a79f62_0    conda-forge
cfgv                      3.3.1              pyhd8ed1ab_0    conda-forge
chardet                   5.2.0           py311h267d04e_2    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
cirun                     0.30               pyhd8ed1ab_0    conda-forge
clang                     16.0.6          default_h675cc0c_13    conda-forge
clang-16                  16.0.6          default_h5c12605_13    conda-forge
clang_impl_osx-arm64      16.0.6              hc421ffc_19    conda-forge
clang_osx-arm64           16.0.6              h54d7cd3_19    conda-forge
clangxx                   16.0.6          default_h675cc0c_13    conda-forge
clangxx_impl_osx-arm64    16.0.6              hcd7bac0_19    conda-forge
clangxx_osx-arm64         16.0.6              h54d7cd3_19    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
click-default-group       1.2.4              pyhd8ed1ab_0    conda-forge
clikit                    0.6.2              pyhd8ed1ab_2    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.2.2              pyhd8ed1ab_0    conda-forge
compiler-rt               16.0.6               h3808999_2    conda-forge
compiler-rt_osx-arm64     16.0.6               h3808999_2    conda-forge
compilers                 1.7.0                hce30654_1    conda-forge
conda                     24.7.1          py311h267d04e_0    conda-forge
conda-build               24.7.1          py311h267d04e_0    conda-forge
conda-forge-conda-plugins 0.0.0                    pypi_0    pypi
conda-forge-metadata      0.9.2              pyhd8ed1ab_0    conda-forge
conda-forge-pinning       2024.09.21.07.11.35      hd8ed1ab_0    conda-forge
conda-index               0.5.0              pyhd8ed1ab_0    conda-forge
conda-libmamba-solver     24.7.0             pyhd8ed1ab_0    conda-forge
conda-lock                2.5.7              pyhd8ed1ab_0    conda-forge
conda-oci-mirror          0.1.0              pyhd8ed1ab_0    conda-forge
conda-pack                0.8.0              pyhd8ed1ab_0    conda-forge
conda-package-handling    2.3.0              pyh7900ff3_0    conda-forge
conda-package-streaming   0.10.0             pyhd8ed1ab_0    conda-forge
conda-recipe-manager      0.2.1              pyhd8ed1ab_0    conda-forge
conda-smithy              3.40.1          unix_pyh707e725_0    conda-forge
conda-souschef            2.2.3              pyhd8ed1ab_0    conda-forge
crashtest                 0.4.1              pyhd8ed1ab_0    conda-forge
cryptography              43.0.1          py311h47c44cf_0    conda-forge
curl                      8.10.1               h13a7ad3_0    conda-forge
cxx-compiler              1.7.0                h2ffa867_1    conda-forge
debugpy                   1.8.5           py311h3f08180_1    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
depfinder                 2.10.0          py311h267d04e_2    conda-forge
deprecated                1.2.14             pyh1a96a4e_0    conda-forge
distlib                   0.3.8              pyhd8ed1ab_0    conda-forge
distro                    1.9.0              pyhd8ed1ab_0    conda-forge
editables                 0.5                pyhd8ed1ab_0    conda-forge
ensureconda               1.4.4              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.2              pyhd8ed1ab_0    conda-forge
executing                 2.1.0              pyhd8ed1ab_0    conda-forge
filelock                  3.16.1             pyhd8ed1ab_0    conda-forge
flake8                    7.1.1              pyhd8ed1ab_0    conda-forge
flake8-pyproject          1.2.3              pyhd8ed1ab_0    conda-forge
flit-core                 3.9.0              pyhd8ed1ab_1    conda-forge
fmt                       10.2.1               h2ffa867_0    conda-forge
fortran-compiler          1.7.0                hafb19e3_1    conda-forge
fqdn                      1.5.1              pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               hadb7bae_2    conda-forge
frozendict                2.4.4           py311hd3f4193_0    conda-forge
gettext                   0.22.5               h8414b35_3    conda-forge
gettext-tools             0.22.5               h8414b35_3    conda-forge
gfortran                  12.3.0               h1ca8e4b_1    conda-forge
gfortran_impl_osx-arm64   12.3.0               h53ed385_3    conda-forge
gfortran_osx-arm64        12.3.0               h57527a5_1    conda-forge
git                       2.46.0          pl5321h41514c7_0    conda-forge
gitdb                     4.0.11             pyhd8ed1ab_0    conda-forge
gitpython                 3.1.43             pyhd8ed1ab_0    conda-forge
glob2                     0.7                        py_0    conda-forge
globus-cli                3.30.1             pyhd8ed1ab_0    conda-forge
globus-sdk                3.44.0             pyhd8ed1ab_0    conda-forge
gmp                       6.3.0                h7bae524_2    conda-forge
grayskull                 2.7.1              pyhd8ed1ab_0    conda-forge
h11                       0.14.0             pyhd8ed1ab_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
hatch                     1.12.0             pyhd8ed1ab_0    conda-forge
hatchling                 1.25.0             pyhd8ed1ab_0    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
html5lib                  1.1                pyh9f0ad1d_0    conda-forge
httpcore                  1.0.5              pyhd8ed1ab_0    conda-forge
httpx                     0.27.2             pyhd8ed1ab_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
hyperlink                 21.0.0             pyhd3deb0d_0    conda-forge
icu                       75.1                 hfee45f7_0    conda-forge
identify                  2.6.1              pyhd8ed1ab_0    conda-forge
idna                      3.10               pyhd8ed1ab_0    conda-forge
importlib-metadata        8.5.0              pyha770c72_0    conda-forge
importlib_metadata        8.5.0                hd8ed1ab_0    conda-forge
importlib_resources       6.4.5              pyhd8ed1ab_0    conda-forge
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.29.5             pyh57ce528_0    conda-forge
ipython                   8.27.0             pyh707e725_0    conda-forge
ipython_genutils          0.2.0              pyhd8ed1ab_1    conda-forge
ipywidgets                8.1.5              pyhd8ed1ab_0    conda-forge
isl                       0.26            imath32_h347afa1_101    conda-forge
isodate                   0.6.1              pyhd8ed1ab_0    conda-forge
isoduration               20.11.0            pyhd8ed1ab_0    conda-forge
jaraco.classes            3.4.0              pyhd8ed1ab_1    conda-forge
jaraco.context            5.3.0              pyhd8ed1ab_1    conda-forge
jaraco.functools          4.0.0              pyhd8ed1ab_0    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
jmespath                  1.0.1              pyhd8ed1ab_0    conda-forge
joblib                    1.4.2              pyhd8ed1ab_0    conda-forge
jq                        1.7.1                h93a5062_0    conda-forge
json5                     0.9.25             pyhd8ed1ab_0    conda-forge
jsonpatch                 1.33               pyhd8ed1ab_0    conda-forge
jsonpointer               3.0.0           py311h267d04e_1    conda-forge
jsonschema                4.23.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.12.1          pyhd8ed1ab_0    conda-forge
jsonschema-with-format-nongpl 4.23.0               hd8ed1ab_0    conda-forge
jupyter                   1.1.1              pyhd8ed1ab_0    conda-forge
jupyter-lsp               2.2.5              pyhd8ed1ab_0    conda-forge
jupyter_client            8.6.3              pyhd8ed1ab_0    conda-forge
jupyter_console           6.6.3              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2           py311h267d04e_0    conda-forge
jupyter_events            0.10.0             pyhd8ed1ab_0    conda-forge
jupyter_server            2.14.2             pyhd8ed1ab_0    conda-forge
jupyter_server_fileid     0.9.2              pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.5.3              pyhd8ed1ab_0    conda-forge
jupyter_server_ydoc       0.1.4              pyhd8ed1ab_0    conda-forge
jupyter_ydoc              2.1.1              pyhd8ed1ab_0    conda-forge
jupyterlab                4.2.5              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.3.0              pyhd8ed1ab_1    conda-forge
jupyterlab_server         2.27.3             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.13             pyhd8ed1ab_0    conda-forge
keyring                   25.4.0             pyh534df25_0    conda-forge
krb5                      1.21.3               h237132a_0    conda-forge
lcms2                     2.16                 ha0e7c42_0    conda-forge
ld64                      951.9                h634c8be_1    conda-forge
ld64_osx-arm64            951.9                h0605c9f_1    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libarchive                3.7.4                h83d404f_0    conda-forge
libasprintf               0.22.5               h8414b35_3    conda-forge
libasprintf-devel         0.22.5               h8414b35_3    conda-forge
libblas                   3.9.0           24_osxarm64_openblas    conda-forge
libcblas                  3.9.0           24_osxarm64_openblas    conda-forge
libclang-cpp16            16.0.6          default_h5c12605_13    conda-forge
libcurl                   8.10.1               h13a7ad3_0    conda-forge
libcxx                    19.1.0               ha82da77_0    conda-forge
libcxx-devel              16.0.6               h86353a2_2    conda-forge
libdeflate                1.21                 h99b78c6_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h93a5062_2    conda-forge
libexpat                  2.6.3                hf9b8971_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgettextpo              0.22.5               h8414b35_3    conda-forge
libgettextpo-devel        0.22.5               h8414b35_3    conda-forge
libgfortran               5.0.0           13_2_0_hd922786_3    conda-forge
libgfortran-devel_osx-arm64 12.3.0               hc62be1c_3    conda-forge
libgfortran5              13.2.0               hf226fd6_3    conda-forge
libiconv                  1.17                 h0d3ecfb_2    conda-forge
libintl                   0.22.5               h8414b35_3    conda-forge
libintl-devel             0.22.5               h8414b35_3    conda-forge
libjpeg-turbo             3.0.0                hb547adb_1    conda-forge
liblapack                 3.9.0           24_osxarm64_openblas    conda-forge
liblief                   0.14.1               hf9b8971_2    conda-forge
libllvm15                 15.0.7               h2621b3d_4    conda-forge
libllvm16                 16.0.6               haab561b_3    conda-forge
libllvm18                 18.1.8               h5090b49_2    conda-forge
libmamba                  1.5.9                hbfbf5c4_0    conda-forge
libmambapy                1.5.9           py311h671292d_0    conda-forge
libnghttp2                1.58.0               ha4dd798_1    conda-forge
libopenblas               0.3.27          openmp_h517c56d_1    conda-forge
libpng                    1.6.44               hc14010f_0    conda-forge
libsodium                 1.0.20               h99b78c6_0    conda-forge
libsolv                   0.7.30               h6c9b7f8_0    conda-forge
libsqlite                 3.46.1               hc14010f_0    conda-forge
libssh2                   1.11.0               h7a5bd25_0    conda-forge
libtiff                   4.7.0                h9c1d414_0    conda-forge
libwebp-base              1.4.0                h93a5062_0    conda-forge
libxcb                    1.16                 hc9fafa5_1    conda-forge
libxml2                   2.12.7               h01dff8b_4    conda-forge
libzlib                   1.3.1                hfb2fe0b_1    conda-forge
license-expression        30.1.1             pyhd8ed1ab_0    conda-forge
llvm-openmp               18.1.8               hde57baf_1    conda-forge
llvm-tools                16.0.6               haab561b_3    conda-forge
lz4-c                     1.9.4                hb7217d7_0    conda-forge
lzo                       2.10              h93a5062_1001    conda-forge
m4                        1.4.18            h642e427_1001    conda-forge
markdown-it-py            3.0.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.5           py311h460d6c5_1    conda-forge
matplotlib-inline         0.1.7              pyhd8ed1ab_0    conda-forge
mccabe                    0.7.0              pyhd8ed1ab_0    conda-forge
mdurl                     0.1.2              pyhd8ed1ab_0    conda-forge
menuinst                  2.1.2           py311h267d04e_1    conda-forge
micromamba                1.5.10                        0    conda-forge
mistune                   3.0.2              pyhd8ed1ab_0    conda-forge
mock                      5.1.0              pyhd8ed1ab_0    conda-forge
more-itertools            10.5.0             pyhd8ed1ab_0    conda-forge
mpc                       1.3.1                h8f1351a_1    conda-forge
mpfr                      4.2.1                hb693164_3    conda-forge
msgpack-python            1.1.0           py311h2c37856_0    conda-forge
msrest                    0.7.1              pyhd8ed1ab_0    conda-forge
mypy_extensions           1.0.0              pyha770c72_0    conda-forge
nb_conda_kernels          2.5.1              pyh707e725_2    conda-forge
nbclassic                 1.1.0              pyhd8ed1ab_0    conda-forge
nbclient                  0.10.0             pyhd8ed1ab_0    conda-forge
nbconvert                 7.16.4               hd8ed1ab_1    conda-forge
nbconvert-core            7.16.4             pyhd8ed1ab_1    conda-forge
nbconvert-pandoc          7.16.4               hd8ed1ab_1    conda-forge
nbformat                  5.10.4             pyhd8ed1ab_0    conda-forge
ncurses                   6.5                  h7bae524_1    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
networkx                  3.3                pyhd8ed1ab_1    conda-forge
nodeenv                   1.9.1              pyhd8ed1ab_0    conda-forge
notebook                  7.2.2              pyhd8ed1ab_0    conda-forge
notebook-shim             0.2.4              pyhd8ed1ab_0    conda-forge
numpy                     2.1.1           py311h6de8079_0    conda-forge
oauthlib                  3.2.2              pyhd8ed1ab_0    conda-forge
oniguruma                 6.9.9                h93a5062_0    conda-forge
openjdk                   22.0.1               h363fedd_1    conda-forge
openjpeg                  2.5.2                h9f1df11_0    conda-forge
openssl                   3.3.2                h8359307_0    conda-forge
oras                      1.2.0                h75b854d_0    conda-forge
oras-py                   0.1.14             pyhd8ed1ab_0    conda-forge
overrides                 7.7.0              pyhd8ed1ab_0    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandoc                    3.4                  hce30654_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.4              pyhd8ed1ab_0    conda-forge
pastel                    0.2.1              pyhd8ed1ab_0    conda-forge
patch                     2.7.6             h27ca646_1002    conda-forge
pathspec                  0.12.1             pyhd8ed1ab_0    conda-forge
pcre2                     10.44                h297a79d_2    conda-forge
perl                      5.32.1          7_h4614cfb_perl5    conda-forge
pexpect                   4.9.0              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.4.0          py311hc903d1b_1    conda-forge
pip                       24.2               pyh8b19718_1    conda-forge
pkginfo                   1.11.1             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              4.3.6              pyhd8ed1ab_0    conda-forge
pluggy                    1.5.0              pyhd8ed1ab_0    conda-forge
pre-commit                3.8.0              pyha770c72_1    conda-forge
progressbar2              4.5.0              pyhd8ed1ab_0    conda-forge
prometheus_client         0.21.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.47             pyha770c72_0    conda-forge
prompt_toolkit            3.0.47               hd8ed1ab_0    conda-forge
psutil                    6.0.0           py311h460d6c5_1    conda-forge
pthread-stubs             0.4               hd74edd7_1002    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.3              pyhd8ed1ab_0    conda-forge
py-lief                   0.14.1          py311h3f08180_2    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycodestyle               2.12.1             pyhd8ed1ab_0    conda-forge
pycosat                   0.6.6           py311heffc1b2_0    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pycrdt                    0.9.11          py311h481aa64_1    conda-forge
pycryptodome              3.20.0          py311h7939e9c_0    conda-forge
pydantic                  2.9.2              pyhd8ed1ab_0    conda-forge
pydantic-core             2.23.4          py311h481aa64_0    conda-forge
pyflakes                  3.2.0              pyhd8ed1ab_0    conda-forge
pygithub                  2.4.0              pyhd8ed1ab_0    conda-forge
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pyjwt                     2.9.0              pyhd8ed1ab_1    conda-forge
pylev                     1.4.0              pyhd8ed1ab_0    conda-forge
pynacl                    1.5.0           py311h460d6c5_4    conda-forge
pyobjc-core               10.3.1          py311h09e6bbd_1    conda-forge
pyobjc-framework-cocoa    10.3.1          py311h09e6bbd_1    conda-forge
pyopenssl                 24.2.1             pyhd8ed1ab_2    conda-forge
pyparsing                 3.1.4              pyhd8ed1ab_0    conda-forge
pyperclip                 1.9.0              pyh534df25_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytest                    8.3.3              pyhd8ed1ab_0    conda-forge
python                    3.11.9          h932a869_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.20.0             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python-libarchive-c       5.1             py311h267d04e_1    conda-forge
python-utils              3.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.11                    5_cp311    conda-forge
pytz                      2024.2             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.2           py311h460d6c5_1    conda-forge
pyzmq                     26.2.0          py311h137d824_2    conda-forge
qtconsole-base            5.6.0              pyha770c72_0    conda-forge
qtpy                      2.4.1              pyhd8ed1ab_0    conda-forge
rapidfuzz                 3.9.7           py311h3f08180_0    conda-forge
rattler-build             0.21.0               h3336b41_0    conda-forge
rattler-build-conda-compat 1.2.1              pyhd8ed1ab_0    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
referencing               0.35.1             pyhd8ed1ab_0    conda-forge
reproc                    14.2.4.post0         h93a5062_1    conda-forge
reproc-cpp                14.2.4.post0         h965bd2d_1    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
requests-oauthlib         2.0.0              pyhd8ed1ab_0    conda-forge
requests-toolbelt         1.0.0              pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rich                      13.8.1             pyhd8ed1ab_0    conda-forge
ripgrep                   14.1.0               h5ef7bb8_0    conda-forge
rpds-py                   0.20.0          py311h481aa64_1    conda-forge
ruamel.yaml               0.18.6          py311h05b510d_0    conda-forge
ruamel.yaml.clib          0.2.8           py311h05b510d_0    conda-forge
ruamel.yaml.jinja2        0.2.7              pyhd8ed1ab_0    conda-forge
ruamel_yaml               0.15.80         py311heffc1b2_1009    conda-forge
ruff                      0.6.5           py311h2cf8269_0    conda-forge
scrypt                    0.8.24          py311h874ab8a_1    conda-forge
semver                    3.0.2              pyhd8ed1ab_0    conda-forge
send2trash                1.8.3              pyh31c8845_0    conda-forge
setuptools                74.1.2             pyhd8ed1ab_0    conda-forge
shellingham               1.5.4              pyhd8ed1ab_0    conda-forge
sigtool                   0.1.3                h44b9a77_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     5.0.0              pyhd8ed1ab_0    conda-forge
sniffio                   1.3.1              pyhd8ed1ab_0    conda-forge
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
stdlib-list               0.10.0             pyhd8ed1ab_0    conda-forge
tapi                      1300.6.5             h03f4b80_0    conda-forge
terminado                 0.18.1             pyh31c8845_0    conda-forge
tinycss2                  1.3.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h5083fa2_1    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomli-w                   1.0.0              pyhd8ed1ab_0    conda-forge
tomlkit                   0.13.2             pyha770c72_0    conda-forge
toolz                     0.12.1             pyhd8ed1ab_0    conda-forge
tornado                   6.4.1           py311h460d6c5_1    conda-forge
tqdm                      4.66.5             pyhd8ed1ab_0    conda-forge
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
trove-classifiers         2024.9.12          pyhd8ed1ab_0    conda-forge
truststore                0.9.2              pyhd8ed1ab_0    conda-forge
typer                     0.12.5             pyhd8ed1ab_0    conda-forge
typer-slim                0.12.5             pyhd8ed1ab_0    conda-forge
typer-slim-standard       0.12.5               hd8ed1ab_0    conda-forge
types-python-dateutil     2.9.0.20240906     pyhd8ed1ab_0    conda-forge
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
tzdata                    2024a                h8827d51_1    conda-forge
ukkonen                   1.0.1           py311h2c37856_5    conda-forge
uri-template              1.3.0              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.19            pyhd8ed1ab_0    conda-forge
userpath                  1.7.0              pyhd8ed1ab_0    conda-forge
uv                        0.4.14               hd3a8144_0    conda-forge
virtualenv                20.26.5            pyhd8ed1ab_0    conda-forge
vsts-python-api           0.1.22                     py_0    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
webcolors                 24.8.0             pyhd8ed1ab_0    conda-forge
webencodings              0.5.1              pyhd8ed1ab_2    conda-forge
websocket-client          1.8.0              pyhd8ed1ab_0    conda-forge
werkzeug                  3.0.4              pyhd8ed1ab_0    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.13             pyhd8ed1ab_0    conda-forge
wrapt                     1.16.0          py311h460d6c5_1    conda-forge
xorg-libxau               1.0.11               hb547adb_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
y-py                      0.6.2           py311h481aa64_1    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
yaml-cpp                  0.8.0                h13dd4ca_0    conda-forge
ypy-websocket             0.12.4             pyhd8ed1ab_0    conda-forge
zeromq                    4.3.5                h64debc3_5    conda-forge
zipp                      3.20.2             pyhd8ed1ab_0    conda-forge
zlib                      1.3.1                hfb2fe0b_1    conda-forge
zstandard                 0.23.0          py311ha60cc69_1    conda-forge
zstd                      1.5.6                hb46c0d2_0    conda-forge
```

### Environment info

```shell
active environment : base
    active env location : /Users/beckermr/mambaforge
            shell level : 1
       user config file : /Users/beckermr/.condarc
 populated config files : /Users/beckermr/mambaforge/.condarc
                          /Users/beckermr/.condarc
          conda version : 24.7.1
    conda-build version : 24.7.1
         python version : 3.11.9.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m2
                          __conda=24.7.1=0
                          __osx=13.6.9=0
                          __unix=0=0
       base environment : /Users/beckermr/mambaforge  (writable)
      conda av data dir : /Users/beckermr/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/beckermr/mambaforge/pkgs
                          /Users/beckermr/.conda/pkgs
       envs directories : /Users/beckermr/mambaforge/envs
                          /Users/beckermr/.conda/envs
               platform : osx-arm64
             user-agent : conda/24.7.1 requests/2.32.3 CPython/3.11.9 Darwin/22.6.0 OSX/13.6.9 solver/libmamba conda-libmamba-solver/24.7.0 libmambapy/1.5.9
                UID:GID : 501:20
             netrc file : /Users/beckermr/.netrc
           offline mode : False
```

**Comment by beckermr** [comment]
cc @wolfv @nichmor

**Comment by wolfv** [comment]
Right now I am afk but I can look later if you don't get to it.

**Comment by beckermr** [comment]
no rush from me - just an FYI

**Comment by beckermr** [comment]
Thanks for the pr but shouldn't the linter be robust to this or is this an expected failure of the code?

**Comment by wolfv** [comment]
What does the current linter do if you have invalid YAML in there?

**Comment by wolfv** [comment]
I just tried with a v0 recipe. _Exactly_ the same error :)

**Comment by beckermr** [comment]
Perfect. We can close this.
