### ISSUE TITLE
Travis CI API key undefined?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#232]
Seeing this everytime I merge something at staged-recipes of late. Restarting the build fixes the issue reliably. Maybe we need a brief timeout or something? Not sure why this is just now cropping up.

```
Repository registered at github, now call 'conda smithy register-ci'
CI Summary for conda-forge/metafone-feedstock (can take ~30s):
 * Travis doesn't know about the repo, synching (takes a few seconds).
 * Registered on travis-ci
404 Client Error: Not Found for url: https://api.travis-ci.org/repos/conda-forge/metafone-feedstock/key
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 186, in <module>
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/Users/travis/miniconda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', '/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmpdwekouwi__feedstocks/metafone-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1
```

**Comment by jakirkham** [comment]
After discussion with @pelson in issue ( ), we suspect this is caused by a lack of headers in [this]( https://github.com/conda-forge/conda-smithy/blob/73ff327c9716dc87c551ad81d9f94dff46d44c43/conda_smithy/vendored/travis_encrypt.py#L44-L46 ) Travis CI API call.

**Comment by pelson** [comment]
Thanks @jakirkham.
