### ISSUE TITLE
Error during registering CI

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#233]
Not sure if this is worth looking into further. This happened once. Saw this while trying to enable the Travis CI setting "Build only if .travis.yml is present". Other info can be found in the log along with the error at the end.

```
$ conda smithy --version
No circle token.  Create a token at https://circleci.com/account/api and
put it in ~/.conda-smithy/circle.token
No appveyor token. Create a token at https://ci.appveyor.com/api-token and
Put one in ~/.conda-smithy/appveyor.token
1.0.1
$ conda info
Current conda install:

             platform : osx-64
        conda version : 4.1.8
    conda-env version : 2.5.2
  conda-build version : 1.21.6
       python version : 2.7.12.final.0
     requests version : 2.10.0
     root environment : /zopt/conda2  (writable)
  default environment : /zopt/conda2/envs/nanshenv
     envs directories : /zopt/conda2/envs
        package cache : /zopt/conda2/pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/conda-forge/osx-64/
                        https://conda.anaconda.org/t/<TOKEN>/conda-forge/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/nanshe/osx-64/
                        https://conda.anaconda.org/t/<TOKEN>/nanshe/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/jakirkham/osx-64/
                        https://conda.anaconda.org/t/<TOKEN>/jakirkham/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/javascript/osx-64/
                        https://conda.anaconda.org/t/<TOKEN>/javascript/noarch/
          config file : /Users/kirkhamj/.condarc
         offline mode : False
    is foreign system : False
$ conda smithy register-ci --feedstock_directory=check-feedstock --org  conda-forge
No circle token.  Create a token at https://circleci.com/account/api and
put it in ~/.conda-smithy/circle.token
No appveyor token. Create a token at https://ci.appveyor.com/api-token and
Put one in ~/.conda-smithy/appveyor.token
CI Summary for conda-forge/check-feedstock (can take ~30s):
Traceback (most recent call last):
  File "/zopt/conda2/bin/conda-smithy", line 9, in <module>
    load_entry_point('conda-smithy==1.0.1', 'console_scripts', 'conda-smithy')()
  File "/zopt/conda2/lib/python2.7/site-packages/conda_smithy/cli.py", line 236, in main
    args.subcommand_func(args)
  File "/zopt/conda2/lib/python2.7/site-packages/conda_smithy/cli.py", line 158, in __call__
    ci_register.add_project_to_travis(owner, repo)
  File "/zopt/conda2/lib/python2.7/site-packages/conda_smithy/ci_register.py", line 177, in add_project_to_travis
    content = response.json()
  File "/zopt/conda2/lib/python2.7/site-packages/requests/models.py", line 812, in json
    return complexjson.loads(self.text, **kwargs)
  File "/zopt/conda2/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/zopt/conda2/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/zopt/conda2/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by jakirkham** [comment]
Another case occurred with `dask`.

**Comment by jakirkham** [comment]
Also, `csa`. Missed that in my log before.

**Comment by jakirkham** [comment]
...and `esmpy`.

**Comment by jakirkham** [comment]
... and `fabio`. First one of these I had to enable manually.

**Comment by jakirkham** [comment]
... and `flask-sqlalchemy`. Was already enabled though.

**Comment by jakirkham** [comment]
FWIW none of the failures were reproducible from run to run on the same feedstock. Though they did occur again.
