### ISSUE TITLE
dict is actually a list during ci_register?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#235]
Sort of a strange error that occurred during conversion.

```
CI support files regenerated. These need to be pushed to github!
[master b611602] Re-render the feedstock after CI registration.
 2 files changed, 10 insertions(+), 2 deletions(-)
 rewrite conda-forge.yml (100%)
rm 'recipes/coloredlogs/meta.yaml'
CI Summary for conda-forge/humanfriendly-feedstock (can take ~30s):
 * Registered on travis-ci
 * conda-forge/humanfriendly-feedstock enabled on CircleCI
 * conda-forge/humanfriendly-feedstock has been enabled on appveyor
humanfriendly-feedstock       : Current setting for skipBranchesWithoutAppveyorYml = False.
Traceback (most recent call last):
  File "/Users/travis/miniconda/bin/conda-smithy", line 9, in <module>
    load_entry_point('conda-smithy==1.0.1', 'console_scripts', 'conda-smithy')()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 236, in main
    args.subcommand_func(args)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 167, in __call__
    ci_register.add_conda_linting(owner, repo)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/ci_register.py", line 284, in add_conda_linting
    hook_by_url = {hook['config'].get('url'): hook for hook in registered
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/ci_register.py", line 285, in <dictcomp>
    if 'url' in hook['config']}
TypeError: string indices must be integers
Traceback (most recent call last):
  File ".CI/create_feedstocks.py", line 186, in <module>
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/Users/travis/miniconda/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', '/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/tmpi3v8juvf__feedstocks/humanfriendly-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1
```

cc @ocefpaf

**Comment by jakirkham** [comment]
I think I have seen this one other time. Normally this is not the case, but maybe some sort of error is being propagated to us from the API.
