### ISSUE TITLE
AttributeError: 'module' object has no attribute 'cc'

### ISSUE THREAD

**Issue by jschueller** [conda-forge/conda-smithy#259]
I reinstalled conda and I cannot rerender my feedstock since:

```
[11:33] schueller@bx-l64: ~/projects/conda-forge/hmat-oss-feedstock $ conda smithy rerender
No circle token.  Create a token at https://circleci.com/account/api and
put it in ~/.conda-smithy/circle.token
No appveyor token. Create a token at https://ci.appveyor.com/api-token and
Put one in ~/.conda-smithy/appveyor.token
Traceback (most recent call last):
  File "/home/schueller/miniconda/bin/conda-smithy", line 9, in <module>
    load_entry_point('conda-smithy==1.0.3', 'console_scripts', 'conda-smithy')()
  File "/home/schueller/miniconda/lib/python2.7/site-packages/conda_smithy/cli.py", line 236, in main
    args.subcommand_func(args)
  File "/home/schueller/miniconda/lib/python2.7/site-packages/conda_smithy/cli.py", line 185, in __call__
    configure_feedstock.main(args.feedstock_directory)
  File "/home/schueller/miniconda/lib/python2.7/site-packages/conda_smithy/configure_feedstock.py", line 361, in main
    render_run_docker_build(env, config, forge_dir)
  File "/home/schueller/miniconda/lib/python2.7/site-packages/conda_smithy/configure_feedstock.py", line 24, in render_run_docker_build
    with fudge_subdir('linux-64'):
  File "/home/schueller/miniconda/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/schueller/miniconda/lib/python2.7/site-packages/conda_smithy/configure_feedstock.py", line 103, in fudge_subdir
    orig = conda_build.metadata.cc.subdir
AttributeError: 'module' object has no attribute 'cc'
```

Here are my installed packages:
```
# packages in environment at /home/schueller/miniconda:
#
Using Anaconda API: https://api.anaconda.org
anaconda-client           1.5.1                    py27_0  
clyent                    1.2.2                    py27_0  
conda                     4.1.11                   py27_0  
conda-build               1.21.12                  py27_0  
conda-env                 2.5.2                    py27_0  
conda-build-all           0.13.2                   py27_0    conda-forge
conda-smithy              1.0.3                    py27_0    conda-forge
gitdb                     0.6.4                    py27_0    conda-forge
gitpython                 1.0.1                    py27_0    conda-forge
pygithub                  1.27.1                   py27_0    conda-forge
ruamel.ordereddict        0.4.6                    py27_0    conda-forge
ruamel.yaml               0.11.11                  py27_1    conda-forge
smmap                     0.9.0                    py27_0    conda-forge
funcsigs                  1.0.2                    py27_0  
jinja2                    2.8                      py27_1  
markupsafe                0.23                     py27_2  
mock                      2.0.0                    py27_0  
openssl                   1.0.2h                        1  
patchelf                  0.9                           0  
pbr                       1.10.0                   py27_0  
pip                       8.1.2                    py27_0  
pycosat                   0.6.1                    py27_1  
pycrypto                  2.6.1                    py27_4  
python                    2.7.12                        1  
python-dateutil           2.5.3                    py27_0  
pytz                      2016.6.1                 py27_0  
pyyaml                    3.11                     py27_4  
readline                  6.2                           2  
requests                  2.10.0                   py27_0  
ruamel_yaml               0.11.14                  py27_0  
setuptools                25.1.6                   py27_0  
six                       1.10.0                   py27_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py27_0  
yaml                      0.1.6                         0  
zlib                      1.2.8                         3
```

**Comment by jakirkham** [comment]
I think this is the same as issue ( https://github.com/conda-forge/conda-smithy/issues/260 ) except that it is occurring on Python 2.7. Going to preemptively close it out under the belief that this is true in order to consolidate the discussion. Thanks for the report, @jschueller.

**Comment by jschueller** [comment]
thanks, downgrading: ```conda install conda-build=1.21.11```
