### ISSUE TITLE
Failed uploads on Travis CI don't error out properly

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#267]
If a package fails to upload on CircleCI or AppVeyor, the build will fail making it easy to identify something has gone wrong and start trying to address it. However, Travis CI appears to exit with a passing status if it fails to upload.

As an example, please see this [build]( https://travis-ci.org/conda-forge/line_profiler-feedstock/jobs/153992253#L589 ) and related issue ( https://github.com/conda-forge/line_profiler-feedstock/issues/6 ). Snippet of the error shown below. This should be recognizable as the common uploading issue we have seen recently and is documented in issue ( https://github.com/conda-forge/status/issues/4  ).

In spite of this error, the build still passed even though it should have failed just like the CircleCI and AppVeyor upload issues. So there is something we need to fix here.

```
$ ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
Using Anaconda API: https://api.anaconda.org
Traceback (most recent call last):
  File "./ci_support/upload_or_check_non_existence.py", line 124, in <module>
    main()
  File "./ci_support/upload_or_check_non_existence.py", line 106, in main
    on_channel = distribution_exists_on_channel(cli, meta, owner, channel)
  File "./ci_support/upload_or_check_non_existence.py", line 69, in distribution_exists_on_channel
    binstar_cli.show_channel(owner=owner, channel=channel)['files']]
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/binstar_client/mixins/channels.py", line 29, in show_channel
    self._check_response(res, [200])
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/binstar_client/__init__.py", line 200, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.NotFound: ('Not Found: Nothing matches the given URI ([GET] https://api.anaconda.org/channels/conda-forge/main -> 404)', 404)
```

**Comment by jakirkham** [comment]
Turns out the cause here is quite simple. We use [`after_success`]( https://github.com/conda-forge/conda-smithy/blob/3f49bcea082d55b638f36bef2435b30ff6259c67/conda_smithy/templates/travis.yml.tmpl#L57-L60 ) to do the uploads. However, `after_success` will not break the build as [documented]( https://docs.travis-ci.com/user/customizing-the-build#Breaking-the-Build ). There's also a fair bit of discussion about this and how surprising it is in issue ( https://github.com/travis-ci/travis-ci/issues/758 ). It seems like a simple fix to not use `after_success`.

**Comment by jakirkham** [comment]
I've tried working on a way to combine these two phases, but it isn't pretty. Part of the reason is we want to ensure we don't upload broken builds. So we have to check if the build failed. Unfortunately doing this is not trivial as [`$?` is out]( https://docs.travis-ci.com/user/customizing-the-build/#Note-on-%24%3F ).

Assuming we stick with our existing model, this requires us either to have a new script to wrap up the build and upload calls, which begins to feel ridiculous as we are duplicating existing `conda-build` functionality. See issue ( https://github.com/conda-forge/conda-smithy/issues/268 ). Alternatively, we can try to do hacky things like store `$?` from the build step, which doesn't seem to work great. Failing that we can try to do messy things with `&&`. No matter which strategy we pick it hurts readability and makes the Travis CI build more complicated.

The much easier solution is actually to use in-built `conda-build` functionality to solve this problem and drop `upload_or_check_non_existence.py` as described in issue ( https://github.com/conda-forge/conda-smithy/issues/268 ). This drastically simplifies our maintenance work here. It also allows us to have one command that causes a proper failure if the upload balks on Travis CI as intended.

**Comment by jakirkham** [comment]
See PR ( https://github.com/conda-forge/conda-smithy/pull/272 ).
