### ISSUE TITLE
Cannot upload packages from Circle

### ISSUE THREAD

**Issue by scopatz** [conda-forge/conda-smithy#27]
Hello Again, 

On Circle CI, I set my `BINSTAR_TOKEN` variable and I see the following error when it goes to update a package:

```console
BUILD END: xz-5.2.2-0
# If you want to upload this package to anaconda.org later, type:
#
# $ anaconda upload /feedstock_root/build_artefacts/linux-64/xz-5.2.2-0.tar.bz2
#
# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

Current conda install:

             platform : linux-64
        conda version : 3.18.1
  conda-build version : 1.18.0
       python version : 3.4.3.final.0
     requests version : 2.8.0
     root environment : /opt/conda  (writable)
  default environment : /opt/conda
     envs directories : /opt/conda/envs
        package cache : /opt/conda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /root/.condarc
    is foreign system : False

Nothing to test for: xz-5.2.2-0
Traceback (most recent call last):
  File "/feedstock_root/ci_support/upload_or_check_non_existence.py", line 99, in <module>
    on_channel = distribution_exists_on_channel(cli, meta, owner, channel)
  File "/feedstock_root/ci_support/upload_or_check_non_existence.py", line 65, in distribution_exists_on_channel
    binstar_cli.show_channel(owner=owner, channel=channel)['files']]
  File "/opt/conda/lib/python3.4/site-packages/binstar_client/mixins/channels.py", line 29, in show_channel
    self._check_response(res, [200])
  File "/opt/conda/lib/python3.4/site-packages/binstar_client/__init__.py", line 159, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.NotFound: ('The user [] does not exist', 404)
lxc-start: lxc_start.c: main: 342 The container failed to start.

lxc-start: lxc_start.c: main: 346 Additional information can be obtained by setting the --logfile and --logpriority options. ./ci_support/run_docker_build.sh returned exit code 1
```

The full run can be found here: https://circleci.com/gh/scopatz/xz-feedstock/7 Note that this does work without the `BINSTAR_TOKEN` variable set. Any ideas?

**Comment by pelson** [comment]
I think this has probably been solved now, but I may be wrong. Please re-open if you see this again.
