### ISSUE TITLE
`conda smithy register-ci` error

### ISSUE THREAD

**Issue by shadowwalkersb** [conda-forge/conda-smithy#287]
Here is the command and its traceback:
```
$ conda smithy register-ci --organization GorgonCryoEM --feedstock_directory gorgon-legacy-feedstock/
CI Summary for GorgonCryoEM/gorgon-legacy-feedstock (can take ~30s):
 * GorgonCryoEM/gorgon-legacy-feedstock already enabled on travis-ci
 * GorgonCryoEM/gorgon-legacy-feedstock enabled on CircleCI
 * GorgonCryoEM/gorgon-legacy-feedstock already enabled on appveyor
Traceback (most recent call last):
  File "/Users/shadow_walker/anaconda/bin/conda-smithy", line 9, in <module>
    load_entry_point('conda-smithy==1.1.2', 'console_scripts', 'conda-smithy')()
  File "/Users/shadow_walker/anaconda/lib/python2.7/site-packages/conda_smithy/cli.py", line 236, in main
    args.subcommand_func(args)
  File "/Users/shadow_walker/anaconda/lib/python2.7/site-packages/conda_smithy/cli.py", line 166, in __call__
    ci_register.appveyor_configure(owner, repo)
  File "/Users/shadow_walker/anaconda/lib/python2.7/site-packages/conda_smithy/ci_register.py", line 149, in appveyor_configure
    raise ValueError(response)
ValueError: <Response [404]>
```

Also, partial `conda info` output:
```
$ conda info
Current conda install:

             platform : osx-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 1.21.14+0.g4dfebe9.dirty
       python version : 2.7.12.final.0
     requests version : 2.10.0
...
```

**Comment by shadowwalkersb** [comment]
Anyone?
