### ISSUE TITLE
Build failure on master

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#289]
We are seeing a build failure on `master`. Here is a snippet from one [build](https://travis-ci.org/conda-forge/conda-smithy/jobs/156757548) below.

```
$ conda install --file requirements.txt nose mock python=${PYTHON} ${CONDA_PKGS} --yes --quiet -c conda-forge
Fetching package metadata .........
Solving package specifications: ..........
Package plan for installation in environment /home/travis/conda:
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    ncurses-5.9                |                8         954 KB  conda-forge
    patchelf-0.9               |                1         349 KB  conda-forge
    python-3.5.2               |                2        31.4 MB  conda-forge
    certifi-2016.8.2           |           py35_0         219 KB  conda-forge
    filelock-2.0.6             |           py35_0           8 KB  conda-forge
    markupsafe-0.23            |           py35_0          33 KB  conda-forge
    pycrypto-2.6.1             |           py35_0         449 KB  conda-forge
    pygithub-1.27.1            |           py35_0         2.0 MB  conda-forge
    pytz-2016.6.1              |           py35_0         162 KB  conda-forge
    requests-2.11.0            |           py35_0         847 KB  conda-forge
    six-1.10.0                 |           py35_0          18 KB  conda-forge
    smmap-0.9.0                |           py35_0          30 KB  conda-forge
    conda-4.1.11               |           py35_1         390 KB  conda-forge
    gitdb-0.6.4                |           py35_0         113 KB  conda-forge
    python-dateutil-2.5.3      |           py35_0         237 KB  conda-forge
    setuptools-26.1.0          |           py35_0         353 KB  conda-forge
    clyent-1.2.1               |           py35_0          14 KB  conda-forge
    gitpython-2.0.8            |           py35_0         654 KB  conda-forge
    jinja2-2.8                 |           py35_1         278 KB  conda-forge
    nose-1.3.7                 |           py35_2         389 KB  conda-forge
    ruamel.yaml-0.11.11        |           py35_1         563 KB  conda-forge
    anaconda-client-1.5.1      |           py35_0         112 KB  conda-forge
    conda-build-2.0.0          |           py35_0         260 KB
    pbr-1.10.0                 |           py35_0          99 KB  conda-forge
    mock-2.0.0                 |           py35_0         101 KB  conda-forge
    conda-build-all-1.0.0rc1   |           py35_0         239 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        40.1 MB
The following NEW packages will be INSTALLED:
    anaconda-client: 1.5.1-py35_0    conda-forge
    certifi:         2016.8.2-py35_0 conda-forge
    clyent:          1.2.1-py35_0    conda-forge
    conda-build:     2.0.0-py35_0               
    conda-build-all: 1.0.0rc1-py35_0 conda-forge
    filelock:        2.0.6-py35_0    conda-forge
    gitdb:           0.6.4-py35_0    conda-forge
    gitpython:       2.0.8-py35_0    conda-forge
    jinja2:          2.8-py35_1      conda-forge
    markupsafe:      0.23-py35_0     conda-forge
    mock:            2.0.0-py35_0    conda-forge
    ncurses:         5.9-8           conda-forge
    nose:            1.3.7-py35_2    conda-forge
    patchelf:        0.9-1           conda-forge
    pbr:             1.10.0-py35_0   conda-forge
    pygithub:        1.27.1-py35_0   conda-forge
    python-dateutil: 2.5.3-py35_0    conda-forge
    pytz:            2016.6.1-py35_0 conda-forge
    ruamel.yaml:     0.11.11-py35_1  conda-forge
    six:             1.10.0-py35_0   conda-forge
    smmap:           0.9.0-py35_0    conda-forge
The following packages will be UPDATED:
    conda:           4.1.11-py35_0               --> 4.1.11-py35_1 conda-forge
    python:          3.5.2-0                     --> 3.5.2-2       conda-forge
    requests:        2.10.0-py35_0               --> 2.11.0-py35_0 conda-forge
    setuptools:      23.0.0-py35_0               --> 26.1.0-py35_0 conda-forge
The following packages will be SUPERCEDED by a higher-priority channel:
    pycrypto:        2.6.1-py35_4                --> 2.6.1-py35_0  conda-forge
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:
    https://github.com/conda/conda/issues
Include the output of the command 'conda info' in your report.
Traceback (most recent call last):
  File "/home/travis/conda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/home/travis/conda/lib/python3.5/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/home/travis/conda/lib/python3.5/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/home/travis/conda/lib/python3.5/site-packages/conda/cli/main_install.py", line 78, in execute
    install(args, parser, 'install')
  File "/home/travis/conda/lib/python3.5/site-packages/conda/cli/install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "/home/travis/conda/lib/python3.5/site-packages/conda/plan.py", line 599, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/travis/conda/lib/python3.5/site-packages/conda/instructions.py", line 135, in execute_instructions
    cmd(state, arg)
  File "/home/travis/conda/lib/python3.5/site-packages/conda/instructions.py", line 78, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'])
  File "/home/travis/conda/lib/python3.5/site-packages/conda/install.py", line 1108, in link
    create_meta(prefix, dist, info_dir, meta_dict)
  File "/home/travis/conda/lib/python3.5/site-packages/conda/install.py", line 489, in create_meta
    load_linked_data(prefix, dist, meta)
  File "/home/travis/conda/lib/python3.5/site-packages/conda/install.py", line 903, in load_linked_data
    channel, schannel = url_channel(url)
  File "/home/travis/conda/lib/python3.5/site-packages/conda/config.py", line 361, in url_channel
    schannel = canonical_channel_name(channel)
  File "/home/travis/conda/lib/python3.5/site-packages/conda/config.py", line 337, in canonical_channel_name
    elif any(channel.startswith(i) for i in get_local_urls(clear_cache=False)):
  File "/home/travis/conda/lib/python3.5/site-packages/conda/config.py", line 181, in get_local_urls
    from conda_build.config import croot
  File "/home/travis/conda/lib/python3.5/site-packages/conda_build/config.py", line 14, in <module>
    from .conda_interface import string_types, binstar_upload
  File "/home/travis/conda/lib/python3.5/site-packages/conda_build/conda_interface.py", line 5, in <module>
    from pkg_resources import parse_version
  File "/home/travis/conda/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2976, in <module>
    @_call_aside
  File "/home/travis/conda/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2962, in _call_aside
    f(*args, **kwargs)
  File "/home/travis/conda/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2989, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/travis/conda/lib/python3.5/site-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws = cls()
  File "/home/travis/conda/lib/python3.5/site-packages/pkg_resources/__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "/home/travis/conda/lib/python3.5/site-packages/pkg_resources/__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "/home/travis/conda/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1945, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/home/travis/conda/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/home/travis/conda/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/home/travis/conda/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/home/travis/conda/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/conda/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg'
```

**Comment by jakirkham** [comment]
This suggests that there is some reference to `setuptools` version `23.0.0` in the `conda` package. However, there really shouldn't be. When I extracted the Linux `conda` package, here is the directory structure I see. Sure enough it is including the `__pycache__` directories for `setuptools` and `pkg_resources`. Not entirely sure why these are showing up, but am fairly certain this is the problem. However, I noticed this same issue with other packages the other day.

```
$ ls -R linux-64_conda-4.1.11-py35_1 
bin  etc  exec info lib

linux-64_conda-4.1.11-py35_1/bin:
activate   conda      deactivate

linux-64_conda-4.1.11-py35_1/etc:
fish

linux-64_conda-4.1.11-py35_1/etc/fish:
conf.d

linux-64_conda-4.1.11-py35_1/etc/fish/conf.d:
conda.fish

linux-64_conda-4.1.11-py35_1/exec:
activate   conda      deactivate

linux-64_conda-4.1.11-py35_1/info:
about.json files      has_prefix index.json recipe

linux-64_conda-4.1.11-py35_1/info/recipe:
bld.bat            build.sh           meta.yaml          meta.yaml.rendered

linux-64_conda-4.1.11-py35_1/lib:
python3.5

linux-64_conda-4.1.11-py35_1/lib/python3.5:
site-packages

linux-64_conda-4.1.11-py35_1/lib/python3.5/site-packages:
conda                       conda-4.1.11-py3.5.egg-info pkg_resources               setuptools

linux-64_conda-4.1.11-py35_1/lib/python3.5/site-packages/conda:
__init__.py      bundle.py        config.pyc       egg_info.pyc     history.pyc      lock.pyc         packup.pyc       signature.py     version.py
__init__.pyc     bundle.pyc       connection.py    exceptions.py    install.py       logic.py         plan.py          signature.pyc    version.pyc
__main__.py      cli              connection.pyc   exceptions.pyc   install.pyc      logic.pyc        plan.pyc         toposort.py
__main__.pyc     compat.py        console.py       fetch.py         instructions.py  misc.py          progressbar      toposort.pyc
api.py           compat.pyc       console.pyc      fetch.pyc        instructions.pyc misc.pyc         resolve.py       utils.py
api.pyc          config.py        egg_info.py      history.py       lock.py          packup.py        resolve.pyc      utils.pyc

linux-64_conda-4.1.11-py35_1/lib/python3.5/site-packages/conda/cli:
__init__.py        conda_argparse.py  install.py         main_clean.py      main_help.py       main_install.py    main_remove.py
__init__.pyc       conda_argparse.pyc install.pyc        main_clean.pyc     main_help.pyc      main_install.pyc   main_remove.pyc
activate.py        find_commands.py   main.py            main_config.py     main_info.py       main_list.py       main_search.py
activate.pyc       find_commands.pyc  main.pyc           main_config.pyc    main_info.pyc      main_list.pyc      main_search.pyc
common.py          help.py            main_bundle.py     main_create.py     main_init.py       main_package.py    main_update.py
common.pyc         help.pyc           main_bundle.pyc    main_create.pyc    main_init.pyc      main_package.pyc   main_update.pyc

linux-64_conda-4.1.11-py35_1/lib/python3.5/site-packages/conda/progressbar:
__init__.py  __init__.pyc compat.py    compat.pyc   widgets.py   widgets.pyc

linux-64_conda-4.1.11-py35_1/lib/python3.5/site-packages/conda-4.1.11-py3.5.egg-info:
PKG-INFO             SOURCES.txt          dependency_links.txt entry_points.txt     not-zip-safe         requires.txt         top_level.txt

linux-64_conda-4.1.11-py35_1/lib/python3.5/site-packages/pkg_resources:
__pycache__ _vendor     extern

linux-64_conda-4.1.11-py35_1/lib/python3.5/site-packages/pkg_resources/__pycache__:
__init__.cpython-35.pyc

linux-64_conda-4.1.11-py35_1/lib/python3.5/site-packages/pkg_resources/_vendor:
__pycache__ packaging

linux-64_conda-4.1.11-py35_1/lib/python3.5/site-packages/pkg_resources/_vendor/__pycache__:
__init__.cpython-35.pyc  pyparsing.cpython-35.pyc six.cpython-35.pyc

linux-64_conda-4.1.11-py35_1/lib/python3.5/site-packages/pkg_resources/_vendor/packaging:
__pycache__

linux-64_conda-4.1.11-py35_1/lib/python3.5/site-packages/pkg_resources/_vendor/packaging/__pycache__:
__about__.cpython-35.pyc    _compat.cpython-35.pyc      markers.cpython-35.pyc      specifiers.cpython-35.pyc
__init__.cpython-35.pyc     _structures.cpython-35.pyc  requirements.cpython-35.pyc version.cpython-35.pyc

linux-64_conda-4.1.11-py35_1/lib/python3.5/site-packages/pkg_resources/extern:
__pycache__

linux-64_conda-4.1.11-py35_1/lib/python3.5/site-packages/pkg_resources/extern/__pycache__:
__init__.cpython-35.pyc

linux-64_conda-4.1.11-py35_1/lib/python3.5/site-packages/setuptools:
__pycache__ command     extern

linux-64_conda-4.1.11-py35_1/lib/python3.5/site-packages/setuptools/__pycache__:
__init__.cpython-35.pyc        extension.cpython-35.pyc       py26compat.cpython-35.pyc      ssl_support.cpython-35.pyc     windows_support.cpython-35.pyc
archive_util.cpython-35.pyc    lib2to3_ex.cpython-35.pyc      py27compat.cpython-35.pyc      unicode_utils.cpython-35.pyc
depends.cpython-35.pyc         msvc.cpython-35.pyc            py31compat.cpython-35.pyc      utils.cpython-35.pyc
dist.cpython-35.pyc            package_index.cpython-35.pyc   sandbox.cpython-35.pyc         version.cpython-35.pyc

linux-64_conda-4.1.11-py35_1/lib/python3.5/site-packages/setuptools/command:
__pycache__

linux-64_conda-4.1.11-py35_1/lib/python3.5/site-packages/setuptools/command/__pycache__:
__init__.cpython-35.pyc         easy_install.cpython-35.pyc     install_lib.cpython-35.pyc      test.cpython-35.pyc
bdist_egg.cpython-35.pyc        egg_info.cpython-35.pyc         install_scripts.cpython-35.pyc
bdist_wininst.cpython-35.pyc    install.cpython-35.pyc          sdist.cpython-35.pyc
build_py.cpython-35.pyc         install_egg_info.cpython-35.pyc setopt.cpython-35.pyc

linux-64_conda-4.1.11-py35_1/lib/python3.5/site-packages/setuptools/extern:
__pycache__

linux-64_conda-4.1.11-py35_1/lib/python3.5/site-packages/setuptools/extern/__pycache__:
__init__.cpython-35.pyc
```

**Comment by jakirkham** [comment]
cc @pelson @msarahan

**Comment by msarahan** [comment]
That looks like a bug with the conda package.  Is it Conda-forge's package, or Continuum's?

**Comment by jakirkham** [comment]
So that is the challenge right. I want to say it is `conda-forge`'s, but this happening during the upgrade from `defaults`.

**Comment by jakirkham** [comment]
In any event, what I'm a bit more worried about is the fact that the `conda` package is including pieces of `setuptools` and `packaging`. I noticed this the other day with a Jupyter package (unfortunately I can't remember the name ATM).

This inclusion of the `__pycache__` directories from dependencies seems like a `conda-build` bug to me though. Would you agree?

**Comment by jakirkham** [comment]
Should add I don't see the same behavior with the Python 2.7 `conda` package. So this is something special about `__pycache__` I think.

**Comment by msarahan** [comment]
> This inclusion of the __pycache__ directories from dependencies seems like a conda-build bug to me though. Would you agree?

Yes.  This happens when packages are shipped without pyc files, but they are then compiled during compilation of a package using the first.  This should not be an issue in conda-build 2.0 (I think 1.21.12+ has it, too), because we only compile files that are created by the build itself.  Moreover, recent versions of conda-build remove files from the __pycache__ folder, strip the mangling from the filename, and put the files alongside their source.

Please update conda-build and rebuild these packages.  Before that, I'm hesitant to call it a conda-build bug.

> So that is the challenge right. I want to say it is conda-forge's, but this happening during the upgrade from defaults.

It is certainly in conda-forge's package.  There is no build 1 of conda 4.1.11 in defaults.

**Comment by jakirkham** [comment]
> Yes.  This happens when packages are shipped without pyc files, but they are then compiled during compilation of a package using the first.  This should not be an issue in conda-build 2.0 (I think 1.21.12+ has it, too), because we only compile files that are created by the build itself.  Moreover, recent versions of conda-build remove files from the __pycache__ folder, strip the mangling from the filename, and put the files alongside their source.

Ah ok, it was a bug, but it is now fixed in `1.21.12+` then. Do you recall the PR(s) that fixed it?

> Please update conda-build and rebuild these packages. Before that, I'm hesitant to call it a conda-build bug.

Tried rebuilding locally and am still running into this issue. See PR ( https://github.com/conda-forge/conda-feedstock/pull/5 ) for the changes used.

Haven't tried 2.0 yet though.

> > So that is the challenge right. I want to say it is conda-forge's, but this happening during the upgrade from defaults.

> It is certainly in conda-forge's package.  There is no build 1 of conda 4.1.11 in defaults.

Are you referring to the file I manually downloaded and extracted in [comment]( https://github.com/conda-forge/conda-smithy/issues/289#issuecomment-244087341 )? Yes, that is definitely from `conda-forge`. That is not the unclear part.

Instead the upgrade process in the OP is the unclear part. In any event, my suspicion is also that is the `conda-forge` package.

**Comment by jakirkham** [comment]
So I have started peering into the `setuptools` package and have found something rather unusual. It appears to be shipping `.pyc` files instead of `__pycache__` on Python 3 builds. 😱 Not really sure why it is doing that, but I suspect that is the beginning of this problem.

**Comment by jakirkham** [comment]
I can reproduce this behavior reliably with `conda-build`. However, if I am not using `conda-build` then it does not generate `.pyc` files and instead generates `__pycache__` directories. So this is not a `setuptools` bug.

**Comment by jakirkham** [comment]
Attempted to build with `conda-build` version `2.0.0` as well, but am unable to due to this error.

```
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/opt/conda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 234, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 226, in execute
    already_built=None, config=config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/api.py", line 81, in build
    need_source_download=need_source_download, config=config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/build.py", line 942, in build_tree
    config=config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/build.py", line 700, in build
    croot=config.croot)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/post.py", line 370, in post_build
    fix_shebang(f, prefix=prefix, build_python=build_python, osx_is_app=osx_is_app)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/post.py", line 62, in fix_shebang
    mm = mmap.mmap(fi.fileno(), 0)
OSError: [Errno 22] Invalid argument
```

**Comment by jakirkham** [comment]
While we get this sorted out, maybe we can just pin `setuptools` in the CI scripts as proposed in PR ( https://github.com/conda-forge/conda-smithy/pull/294 ). That seems to be a simple and effective workaround.

**Comment by jakirkham** [comment]
Appears to be resolved. See PR ( https://github.com/conda-forge/conda-smithy/pull/356 ).
