### ISSUE TITLE
feedstock_content not found

### ISSUE THREAD

**Issue by scopatz** [conda-forge/conda-smithy#3]
Is the following error message because  the  `feedstock_content/` dir is not installed anywhere and I am running outside of the conda-smithy dir?

```console
scopatz@athenaie ~ $ conda smithy init xonsh/recipe --feedstock-directory xonsh-feedstock
Traceback (most recent call last):
  File "/home/scopatz/.local/bin/conda-smithy", line 4, in <module>
    __import__('pkg_resources').run_script('conda-smithy==0.1.0.dev0', 'conda-smithy')
  File "/home/scopatz/miniconda3/lib/python3.4/site-packages/setuptools-18.0.1-py3.4.egg/pkg_resources/__init__.py", line 735, in run_script
  File "/home/scopatz/miniconda3/lib/python3.4/site-packages/setuptools-18.0.1-py3.4.egg/pkg_resources/__init__.py", line 1652, in run_script
  File "/home/scopatz/.local/lib/python3.4/site-packages/conda_smithy-0.1.0.dev0-py3.4.egg/EGG-INFO/scripts/conda-smithy", line 161, in <module>
    args.subcommand_func(args)
  File "/home/scopatz/.local/lib/python3.4/site-packages/conda_smithy-0.1.0.dev0-py3.4.egg/EGG-INFO/scripts/conda-smithy", line 64, in __call__
    generate_feedstock_content(feedstock_directory, args.recipe_directory)
  File "/home/scopatz/.local/lib/python3.4/site-packages/conda_smithy-0.1.0.dev0-py3.4.egg/EGG-INFO/scripts/conda-smithy", line 24, in generate_feedstock_content
    configure_feedstock.main(target_directory)
  File "/home/scopatz/.local/lib/python3.4/site-packages/conda_smithy-0.1.0.dev0-py3.4.egg/conda_smithy/configure_feedstock.py", line 179, in main
    copy_feedstock_content(forge_dir)
  File "/home/scopatz/.local/lib/python3.4/site-packages/conda_smithy-0.1.0.dev0-py3.4.egg/conda_smithy/configure_feedstock.py", line 77, in copy_feedstock_content
    copytree(feedstock_content, forge_dir, 'README')
  File "/home/scopatz/.local/lib/python3.4/site-packages/conda_smithy-0.1.0.dev0-py3.4.egg/conda_smithy/configure_feedstock.py", line 61, in copytree
    for item in os.listdir(src):
FileNotFoundError: [Errno 2] No such file or directory: '/home/scopatz/.local/lib/python3.4/site-packages/conda_smithy-0.1.0.dev0-py3.4.egg/feedstock_content'
scopatz@athenaie ~ $ ls xonsh-feedstock/
conda-forge.yml  recipe
```

**Comment by pelson** [comment]
Yeah. I'd guess the content isn't being installed with the package. Ironically, I try to avoid setup.py stuff as much as possible... :wink: 
I suspect the content needs to be listed in the manifest for this to work.

**Comment by scopatz** [comment]
I think that I know how to do this.
