### ISSUE TITLE
Unhelpful error message on register-ci

### ISSUE THREAD

**Issue by amueller** [conda-forge/conda-smithy#303]
Hey.
I got this error
```
CI Summary for scikit-learn/scikit-learn-feedstock (can take ~30s):
 * scikit-learn/scikit-learn-feedstock already enabled on travis-ci
 * scikit-learn/scikit-learn-feedstock enabled on CircleCI
 * scikit-learn/scikit-learn-feedstock already enabled on appveyor
Traceback (most recent call last):
  File "/home/andy/anaconda3/bin/conda-smithy", line 11, in <module>
    load_entry_point('conda-smithy==1.2.0', 'console_scripts', 'conda-smithy')()
  File "/home/andy/anaconda3/lib/python3.5/site-packages/conda_smithy/cli.py", line 236, in main
    args.subcommand_func(args)
  File "/home/andy/anaconda3/lib/python3.5/site-packages/conda_smithy/cli.py", line 166, in __call__
    ci_register.appveyor_configure(owner, repo)
  File "/home/andy/anaconda3/lib/python3.5/site-packages/conda_smithy/ci_register.py", line 149, in appveyor_configure
    raise ValueError(response)
ValueError: <Response [404]>
```
when trying to push an rc into our own channel.
I guess it's a permission problem on some level, but it would be nice to have a better error message.

**Comment by jakirkham** [comment]
cc @shadowwalkersb

**Comment by sodre** [comment]
I am having the same issue here. Please let me know if you need a guinea pig.
