### ISSUE TITLE
Unusual upload error

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#312]
Had some very odd, but likely spurious upload error. Figured I would note it here and move on for the moment.

```
$ ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
Using Anaconda API: https://api.anaconda.org
Traceback (most recent call last):
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 447, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 228, in _error_catcher
    yield
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 498, in read_chunked
    self._update_chunk_length()
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 451, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/requests/models.py", line 664, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 349, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 526, in read_chunked
    self._original_response.close()
  File "/Users/travis/miniconda3/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 246, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "./ci_support/upload_or_check_non_existence.py", line 124, in <module>
    main()
  File "./ci_support/upload_or_check_non_existence.py", line 106, in main
    on_channel = distribution_exists_on_channel(cli, meta, owner, channel)
  File "./ci_support/upload_or_check_non_existence.py", line 69, in distribution_exists_on_channel
    binstar_cli.show_channel(owner=owner, channel=channel)['files']]
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/binstar_client/mixins/channels.py", line 28, in show_channel
    res = self.session.get(url)
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/requests/sessions.py", line 617, in send
    r.content
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/requests/models.py", line 741, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/Users/travis/miniconda3/lib/python3.5/site-packages/requests/models.py", line 667, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

**Comment by jakirkham** [comment]
Have seen the above error many times, but seem to have forgotten the xref. Here is a recent [example]( https://circleci.com/gh/conda-forge/pandas-summary-feedstock/1 ).
