### ISSUE TITLE
Was there a recent change to where recipes are built?

### ISSUE THREAD

**Issue by danielballan** [conda-forge/conda-smithy#32]
Conda-smithy seems to put the built package at

```
/feedstock_root/build_artefacts/linux-64/tifffile-0.3.1-np19py34_0.tar.bz2
```

but then look to upload it from the path

```
dist/conda-forge/tifffile/0.3.1/linux-64/tifffile-0.3.1-np18py27_0.tar.bz2
```

See these excerpts from [the full log](https://circleci.com/gh/danielballan/tifffile-feedstock/14).

```
# If you want to upload this package to anaconda.org later, type:
#
# $ anaconda upload /feedstock_root/build_artefacts/linux-64/tifffile-0.3.1-np19py34_0.tar.bz2
#
# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes
```

```
Using anaconda-server api site https://api.anaconda.org
[warning] Distribution linux-64/tifffile-0.3.1-np18py27_0.tar.bz2 already exists ... removing 
[NotFound] The path u'/dist/conda-forge/tifffile/0.3.1/linux-64/tifffile-0.3.1-np18py27_0.tar.bz2' could not be found 
Traceback (most recent call last):
  File "/opt/conda/bin/anaconda", line 6, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.4/site-packages/binstar_client/scripts/cli.py", line 93, in main
    description=__doc__, version=version)
  File "/opt/conda/lib/python3.4/site-packages/binstar_client/scripts/cli.py", line 75, in binstar_main
    return args.main(args)
  File "/opt/conda/lib/python3.4/site-packages/binstar_client/commands/upload.py", line 194, in main
    if remove_existing_file(binstar, args, username, package_name, version, file_attrs):
  File "/opt/conda/lib/python3.4/site-packages/binstar_client/commands/upload.py", line 135, in remove_existing_file
    binstar.remove_dist(username, package_name, version, file_attrs['basename'])
  File "/opt/conda/lib/python3.4/site-packages/binstar_client/__init__.py", line 345, in remove_dist
    self._check_response(res)
  File "/opt/conda/lib/python3.4/site-packages/binstar_client/__init__.py", line 161, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.NotFound: ("The path u'/dist/conda-forge/tifffile/0.3.1/linux-64/tifffile-0.3.1-np18py27_0.tar.bz2' could not be found", 404)
 
Traceback (most recent call last):
  File "/feedstock_root/ci_support/upload_or_check_non_existence.py", line 101, in <module>
    upload(cli, meta, owner, channel)
  File "/feedstock_root/ci_support/upload_or_check_non_existence.py", line 51, in upload
    env=os.environ)
  File "/opt/conda/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command '['anaconda', '--quiet', '-t', 'binstar.token', 'upload', '--force', '/feedstock_root/build_artefacts/linux-64/tifffile-0.3.1-np18py27_0.tar.bz2', '--user=conda-forge', '--channel=main']' returned non-zero exit status 1 ./ci_support/run_docker_build.sh returned exit code 1
```

(You might notice I added the `--force` argument to `anaconda upload`, but I can't think this could be related to the problem.)

**Comment by pelson** [comment]
Could you check what version of conda[-build] you have. I have seen things like this in the past (not recently though) and it was a pretty smooth operation to get obvious-ci-feedstock running.

If all else fails, ensure you have conda-smithy from master, and run the following from the feedstock directory:

```
python -m conda_smithy.configure_feedstock
```

This will ensure your feedstock is up to scratch.

**Comment by danielballan** [comment]
Thanks again for the quick support. I hope I can contribute some helpful PRs out of this to streamline the process for others.

Latest conda:
```
$ conda-build --version
conda-build 1.18.1
```

Clean installation from conda-smithy master:
```
$ conda-smithy
-bash: /Users/dallan/miniconda/bin/conda-smithy: No such file or directory
Daniels-Air:conda-smithy dallan$ git log | head
commit b1f69aaeea08cfc3fc57f2696caa92ac1f3b947d
Merge: 84ead45 4767248
Author: Phil Elson <pelson.pub@gmail.com>
Date:   Fri Nov 6 06:48:54 2015 +0000

    Merge pull request #31 from pelson/refinement
    
    Fixed anaconda-client usage.

commit 476724806ec6b916477ab9f4662cc3a58d53aa8c
Daniels-Air:conda-smithy dallan$ python setup.py install
(...)
Finished processing dependencies for conda-smithy==0.1.0.dev0
```

Issue with `configure_feedstock`:

```
$ python -m conda_smithy.configure_feedstock tifffile-feedstock
Traceback (most recent call last):
  File "/Users/dallan/miniconda/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/dallan/miniconda/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/dallan/miniconda/lib/python3.5/site-packages/conda_smithy-0.1.0.dev0-py3.5.egg/conda_smithy/configure_feedstock.py", line 204, in <module>
    main(args.forge_file_directory)
  File "/Users/dallan/miniconda/lib/python3.5/site-packages/conda_smithy-0.1.0.dev0-py3.5.egg/conda_smithy/configure_feedstock.py", line 185, in main
    render_travis(env, config, forge_dir)
  File "/Users/dallan/miniconda/lib/python3.5/site-packages/conda_smithy-0.1.0.dev0-py3.5.egg/conda_smithy/configure_feedstock.py", line 39, in render_travis
    fh.write(template.render(**forge_config))
  File "/Users/dallan/miniconda/lib/python3.5/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/dallan/miniconda/lib/python3.5/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dallan/miniconda/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/dallan/miniconda/lib/python3.5/site-packages/conda_smithy-0.1.0.dev0-py3.5.egg/conda_smithy/templates/travis.yml.tmpl", line 10, in top-level template code
    {% block env %}
  File "/Users/dallan/miniconda/lib/python3.5/site-packages/conda_smithy-0.1.0.dev0-py3.5.egg/conda_smithy/templates/travis.yml.tmpl", line 11, in block "env"
    {% if matrix[0] or travis.secure %}
  File "/Users/dallan/miniconda/lib/python3.5/site-packages/jinja2/environment.py", line 389, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'matrix' is undefined
```

**Comment by pelson** [comment]
This looks like a usability bug. I suspect you have a ```conda-forge.yml``` which doesn't play nice with the template. What does your template look like?

One thing this could be: https://github.com/conda-forge/conda-smithy/pull/29/files#diff-3a2c4a048580db27ad9db93e2780b511R146 - this is changed the default template for docker to one which can handle multiple builds.

**Comment by danielballan** [comment]
My `conda-forge.yml` is an empty list:

```
[]
```

Did I miss a step? I did:

```shell
$ conda smithy init ~/Documents/Repos/conda-recipes/tifffile/
$ cat tifffile-feedstock/conda-forge.yml 
[]
```

**Comment by pelson** [comment]
I suspect this has been addressed, give me a should @danielballan if it crops up again. Thanks
