### ISSUE TITLE
AttributeError: module 'conda_build.config' has no attribute 'subdir'

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-smithy#327]
When trying to rerender a feedstock, I get this,

``` Python
Traceback (most recent call last):
  File "/home/isuru/miniconda3/bin/conda-smithy", line 6, in <module>
    sys.exit(conda_smithy.cli.main())
  File "/home/isuru/miniconda3/lib/python3.5/site-packages/conda_smithy/cli.py", line 239, in main
    args.subcommand_func(args)
  File "/home/isuru/miniconda3/lib/python3.5/site-packages/conda_smithy/cli.py", line 185, in __call__
    configure_feedstock.main(args.feedstock_directory)
  File "/home/isuru/miniconda3/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 444, in main
    render_run_docker_build(env, config, forge_dir)
  File "/home/isuru/miniconda3/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 37, in render_run_docker_build
    with fudge_subdir('linux-64', build_config=meta_config(meta)):
  File "/home/isuru/miniconda3/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/isuru/miniconda3/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 131, in fudge_subdir
    cb_orig = build_config.subdir
AttributeError: module 'conda_build.config' has no attribute 'subdir'
```

`conda list -n root` gives

```
anaconda-client           1.4.0                    py35_0    defaults
bzip2                     1.0.6                         3    defaults
clyent                    1.2.2                    py35_0    defaults
conda-build               2.0.4                    py35_0    defaults
backports.shutil_get_terminal_size 1.0.0                    py35_0    conda-forge
ca-certificates           2016.2.28                     0    conda-forge
certifi                   2016.2.28                py35_0    conda-forge
cmake                     3.6.1                         0    conda-forge
conda                     4.1.11                   py35_1    conda-forge
conda-build-all           0.12.0                   py35_1    conda-forge
conda-env                 2.5.2                    py35_0    conda-forge
conda-smithy              1.3.2                    py35_0    conda-forge
curl                      7.49.1                        1    conda-forge
cycler                    0.10.0                   py35_0    conda-forge
decorator                 4.0.10                   py35_0    conda-forge
entrypoints               0.2.2                    py35_0    conda-forge
expat                     2.1.0                         2    conda-forge
ffmpeg                    2.8.6                         2    conda-forge
filelock                  2.0.6                    py35_0    conda-forge
fontconfig                2.11.1                        3    conda-forge
freetype                  2.6.3                         0    conda-forge
future                    0.15.2                   py35_0    conda-forge
gitdb                     0.6.4                    py35_0    conda-forge
gitpython                 1.0.1                    py35_0    conda-forge
gmp                       6.1.1                         0    conda-forge
gmpy2                     2.0.7                    py35_0    conda-forge
icu                       56.1                          4    conda-forge
ipython                   5.0.0                    py35_0    conda-forge
ipywidgets                5.1.5                    py35_0    conda-forge
jpeg                      9b                            0    conda-forge
jsoncpp                   0.10.6                        1    conda-forge
jsonschema                2.5.1                    py35_0    conda-forge
jupyter_client            4.3.0                    py35_0    conda-forge
jupyter_console           5.0.0                    py35_0    conda-forge
jupyter_core              4.1.0                    py35_0    conda-forge
jupyterlab                0.2.0                    py35_1    conda-forge
libarchive                3.2.1                         2    conda-forge
libiconv                  1.14                          2    conda-forge
libpng                    1.6.21                        1    conda-forge
libsodium                 1.0.10                        0    conda-forge
libtiff                   4.0.6                         6    conda-forge
libxml2                   2.9.4                         0    conda-forge
matplotlib                1.5.2               np110py35_4    conda-forge
mistune                   0.7.3                    py35_0    conda-forge
mock                      2.0.0                    py35_0    conda-forge
mpc                       1.0.3                         1    conda-forge
mpfr                      3.1.4                         1    conda-forge
mpmath                    0.19                     py35_0    conda-forge
nbconvert                 4.2.0                    py35_0    conda-forge
nbformat                  4.0.1                    py35_0    conda-forge
ncurses                   5.9                           8    conda-forge
nose                      1.3.7                    py35_0    conda-forge
notebook                  4.2.1                    py35_0    conda-forge
pandas                    0.18.1              np110py35_0    conda-forge
patchelf                  0.9                           0    conda-forge
pexpect                   4.1.0                    py35_0    conda-forge
pickleshare               0.7.2                    py35_0    conda-forge
pillow                    3.2.0                    py35_2    conda-forge
pkginfo                   1.2.1                    py35_0    conda-forge
prompt_toolkit            1.0.3                    py35_0    conda-forge
psutil                    4.1.0                    py35_0    conda-forge
ptyprocess                0.5.1                    py35_0    conda-forge
pygithub                  1.26.0                   py35_0    conda-forge
pygments                  1.6                      py35_0    conda-forge
pyparsing                 2.1.1                    py35_0    conda-forge
pytest                    2.9.2                    py35_0    conda-forge
python                    3.5.2                         2    conda-forge
pyzmq                     14.7.0                   py35_0    conda-forge
qtconsole                 4.2.1                    py35_0    conda-forge
readline                  6.2                           0    conda-forge
ruamel.yaml               0.11.11                  py35_1    conda-forge
simplegeneric             0.8.1                    py35_0    conda-forge
sip                       4.18                     py35_0    conda-forge
smmap                     0.9.0                    py35_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
terminado                 0.6                      py35_0    conda-forge
tk                        8.5.19                        0    conda-forge
tornado                   4.2.1                    py35_0    conda-forge
traitlets                 4.2.2                    py35_0    conda-forge
wcwidth                   0.1.7                    py35_0    conda-forge
widgetsnbextension        1.2.3                    py35_1    conda-forge
x264                      20131217                      0    conda-forge
xerces-c                  3.1.4                         2    conda-forge
xz                        5.2.2                         0    conda-forge
zeromq                    4.1.5                         0    conda-forge
zlib                      1.2.8                         3    conda-forge
cython                    0.23.5                   py35_0    defaults
fastcache                 1.0.2                    py35_1    defaults
ipykernel                 4.3.1                    py35_0    defaults
ipython_genutils          0.1.0                    py35_0    defaults
jbig                      2.1                           0    defaults
jinja2                    2.8                      py35_1    defaults
jupyter                   1.0.0                    py35_3    defaults
libgfortran               3.0.0                         1    defaults
markupsafe                0.23                     py35_2    defaults
mkl                       11.3.3                        0    defaults
numpy                     1.10.4                   py35_2    defaults
openssl                   1.0.2h                        0    defaults
pbr                       1.8.0                    py35_0    defaults
pip                       8.1.1                    py35_1    defaults
py                        1.4.31                   py35_0    defaults
pycosat                   0.6.1                    py35_0    defaults
pycrypto                  2.6.1                    py35_0    defaults
pyqt                      4.11.4                   py35_3    defaults
python-dateutil           2.5.3                    py35_0    defaults
pytz                      2016.4                   py35_0    defaults
pyyaml                    3.11                     py35_1    defaults
qt                        4.8.7                         3    defaults
requests                  2.10.0                   py35_0    defaults
autograd                  1.1.1                    py35_0    richardotis
pycalphad                 0.3.6                    py35_0    richardotis
tinydb                    2.4                      py35_0    richardotis
tqdm                      3.8.0                    py35_0    richardotis
ruamel_yaml               0.11.7                   py35_0    defaults
scipy                     0.17.1              np110py35_1    defaults
setuptools                21.2.1                   py35_0    defaults
six                       1.10.0                   py35_0    defaults
sympy                     0.7.6.1                  py35_0    defaults
theano                    0.7.0               np110py35_0    defaults
wheel                     0.29.0                   py35_0    defaults
xarray                    0.7.2                    py35_0    defaults
yaml                      0.1.6                         0    defaults
```

**Comment by jakirkham** [comment]
xref: https://gitter.im/conda-forge/conda-forge.github.io?at=57fe4020a9a0a3337530607d

**Comment by jakirkham** [comment]
As mentioned on gitter, I would be very curious to know if a fresh Miniconda install fixes this. There were some `conda-build` 1 vs 2 compatibility issues, but I thought we had fixed them awhile back. This looks like such an issue. So am wondering if there are some old `*.pyc` or `__pycache__` floating around that are causing us problems somehow.

**Comment by isuruf** [comment]
It does work with a fresh Miniconda install. Removing and installing conda-build didn't work in the old install though.

**Comment by jakirkham** [comment]
So then I would think removing and reinstalling `conda-smithy` might fix it. Though I don't know if there might still be some `*.pyc` or `__pycache__` stuff that needs to be manually removed.

**Comment by isuruf** [comment]
Reinstalling conda-smithy doesn't work. When I removed conda-build, conda-smithy was also removed.

**Comment by jakirkham** [comment]
Yeah, though maybe there were some old `*.pyc`s or `__pycache__`s that weren't removed in the process. Could you please double check manually that there is nothing like this hanging around from `conda-smithy` in that install.

**Comment by isuruf** [comment]
@jakirkham, I checked and there's nothing like that.

**Comment by jakirkham** [comment]
Is this still an issue, @isuruf?

**Comment by isuruf** [comment]
I removed my Miniconda installation with a fresh one because of this issue, so can't reproduce now.

**Comment by dfm** [comment]
You all might have noticed this already, but I just wanted to note that I got this error again with `conda-build==3.0.4` and I was only able to fix it by downgrading to `conda-build<3`. Perhaps this will save others some headache!

**Comment by jakirkham** [comment]
Could you please open that in a new issue, @dfm, as it is not related to this issue? Thanks.

**Comment by dfm** [comment]
Sure. Done: #545 Thanks!
