### ISSUE TITLE
AppVeyor VS2008 slow startup/memory issues

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#351]
Seems there is a rather strange issue happening on the VS2008 builds unrelated to the recipe here. They seem to be taking a really long time to run and may be running out of memory as this build shows. Not sure if this is a `conda` problem (infinite recursion and so on) or a VM memory problem.

xref: https://ci.appveyor.com/project/conda-forge/iteration-utilities-feedstock/build/1.0.10/job/m42dxwpke0i6e5pt#L128
xref: https://ci.appveyor.com/project/conda-forge/conda-smithy-feedstock/build/1.0.89/job/1xvlseif9w9se8tr#L120

cc @conda-forge/core

**Comment by jakirkham** [comment]
Should add the setup time for these VS2008 builds is right now ~10mins which is really going to hurt us on the larger scale. This is exceeding our ~2min or less startup time by 5-fold. It is really going to start costing us on the AppVeyor queue soon.

**Comment by MSeifert04** [comment]
@jakirkham I have a Job already running for 50 minutes (a bit longer than the mentioned 10 minutes): https://ci.appveyor.com/project/conda-forge/iteration-utilities-feedstock/build/1.0.11.

The queue is empty right now so I haven't cancelled it. But if it holds up other jobs feel free to cancel it.

**Comment by mwcraig** [comment]
FWIW, I am not seeing delays in python 2.7 jobs in other (non-conda-forge-related) appveyor jobs...

**Comment by MSeifert04** [comment]
@jakirkham Here's the copy you asked for (https://github.com/conda-forge/iteration_utilities-feedstock/pull/3):

See for example (today):
- https://ci.appveyor.com/project/conda-forge/pytest-mock-feedstock/build/1.0.15
- https://ci.appveyor.com/project/conda-forge/hpc05-feedstock/build/1.0.10
- https://ci.appveyor.com/project/conda-forge/ipycache-feedstock/build/1.0.10

2 days ago:
- https://ci.appveyor.com/project/conda-forge/sentinels-feedstock/build/1.0.2

4 days ago:
- https://ci.appveyor.com/project/conda-forge/keepalive-feedstock/build/1.0.1

9 days ago:
- https://ci.appveyor.com/project/conda-forge/django-grappelli-feedstock/build/1.0.9

And those are just those I've looked into. So far a 100% hit rate.

11 days ago (**>>>no delay<<<**):
- https://ci.appveyor.com/project/conda-forge/exec-wrappers-feedstock/build/1.0.14

So at some point 10 or 11 days ago something changed/broke.

**Comment by jakirkham** [comment]
These are all good data points. This suggests that maybe adding the workaround for AppVeyor failures in PR ( https://github.com/conda-forge/conda-smithy/pull/329 ) is having some inadvertent consequences.

**Comment by jakirkham** [comment]
Also @MSeifert04 I stopped and restarted that build. Not because it is occupying the queue, but because it looks like it was going to timeout anyways (AppVeyor has a 1hr limit). As all the other builds passed and deployed, this should make sure that one build should too. Hope that is ok.

**Comment by jakirkham** [comment]
Looking at staged-recipes, I'm not seeing the same issue. As staged-recipes uses the AppVeyor included Miniconda, this may be an acceptable solution here too.

This was proposed to be done for feedstocks in issue ( https://github.com/conda-forge/conda-smithy/issues/176 ). However, the requester backed off due to the time spent upgrading the often out-of-date copies of Miniconda on AppVeyor. Unless someone has a better idea of the problem and how to fix it, I think we should go ahead with switching to AppVeyor's Miniconda.

Won't be able to do this in the near term personally, but may get to it later in the week. If someone can get to it sooner, please feel free to submit a PR. Basically it is a matter of porting this PR ( https://github.com/conda-forge/staged-recipes/pull/982 ) over here. There may be a few tricks with the Jinja code here, but it should all be doable. As this feels like a bigger change, would rather bump the minor version than the patch for the release. So am thinking this could be `1.5.0`.

**Comment by jakirkham** [comment]
Some more examples.

* https://ci.appveyor.com/project/conda-forge/oslo-config-feedstock/build/1.0.2
* https://ci.appveyor.com/project/conda-forge/wincertstore-feedstock/build/1.0.2
* https://ci.appveyor.com/project/conda-forge/mkdocs-bootswatch-feedstock/build/1.0.3

**Comment by MSeifert04** [comment]
So I've analyzed several failures and got this (shortened) collection:

<details>

x86 - https://ci.appveyor.com/project/conda-forge/geos-feedstock/build/job/9x5h2eia9jddmcx7
```
run_conda_forge_build_setup
Traceback (most recent call last):
  File "C:\conda\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\conda\lib\site-packages\conda\cli\main.py", line 61, in main
    from conda.cli import conda_argparse
  File "C:\conda\lib\site-packages\conda\cli\conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "C:\conda\lib\site-packages\conda\cli\common.py", line 15, in <module>
    from ..install import dist2quad
  File "C:\conda\lib\site-packages\conda\install.py", line 100, in <module>
    import ctypes
  File "C:\conda\lib\ctypes\__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: DLL load failed: The paging file is too small for this operation to complete.
Using Anaconda API: https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications: ..........
```
x64 - https://ci.appveyor.com/project/conda-forge/lapack-feedstock/build/job/8ms091p1ckfbxmiv
```
run_conda_forge_build_setup
no mem for new parser
Traceback (most recent call last):
  File "C:\conda\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\conda\lib\site-packages\conda\cli\main.py", line 94, in main
    imported = importlib.import_module(module)
  File "C:\conda\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\conda\lib\site-packages\conda\cli\main_list.py", line 18, in <module>
    from ..egg_info import get_egg_info
  File "C:\conda\lib\site-packages\conda\egg_info.py", line 15, in <module>
    from .misc import rel_path
  File "C:\conda\lib\site-packages\conda\misc.py", line 18, in <module>
    from .instructions import RM_FETCHED, FETCH, RM_EXTRACTED, EXTRACT, UNLINK, LINK, SYMLINK_CONDA
  File "C:\conda\lib\site-packages\conda\instructions.py", line 7, in <module>
    from .fetch import fetch_pkg
  File "C:\conda\lib\site-packages\conda\fetch.py", line 13, in <module>
    import requests
  File "C:\conda\lib\site-packages\requests\__init__.py", line 53, in <module>
    
  File "C:\conda\lib\site-packages\requests\packages\__init__.py", line 27, in <module>
    
  File "C:\conda\lib\site-packages\requests\packages\urllib3\__init__.py", line 8, in <module>
    
  File "C:\conda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 35, in <module>
    
  File "C:\conda\lib\site-packages\requests\packages\urllib3\connection.py", line 43, in <module>
    
  File "C:\conda\lib\site-packages\requests\packages\urllib3\util\__init__.py", line 20, in <module>
    
  File "C:\conda\lib\site-packages\requests\packages\urllib3\util\url.py", line 10, in <module>
    
  File "C:\conda\lib\collections.py", line 386, in namedtuple
    
MemoryError
```
x64 - https://ci.appveyor.com/project/conda-forge/lapack-feedstock/build/job/92l095wih05go1uc
```
run_conda_forge_build_setup
Traceback (most recent call last):
  File "C:\conda\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\conda\lib\site-packages\conda\cli\main.py", line 61, in main
    from conda.cli import conda_argparse
  File "C:\conda\lib\site-packages\conda\cli\conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "C:\conda\lib\site-packages\conda\cli\common.py", line 12, in <module>
    from ..config import (envs_dirs, default_prefix, platform, update_dependencies,
  File "C:\conda\lib\site-packages\conda\config.py", line 475, in <module>
    load_condarc(rc_path)
  File "C:\conda\lib\site-packages\conda\config.py", line 391, in load_condarc
    rc = load_condarc_(path)
  File "C:\conda\lib\site-packages\conda\config.py", line 129, in load_condarc_
    return yaml_load(f) or {}
  File "C:\conda\lib\site-packages\conda\utils.py", line 296, in yaml_load
    yaml = get_yaml()
  File "C:\conda\lib\site-packages\conda\utils.py", line 43, in __call__
    value = self.func(*args, **kw)
  File "C:\conda\lib\site-packages\conda\utils.py", line 282, in get_yaml
    import ruamel_yaml as yaml
  File "C:\conda\lib\site-packages\ruamel_yaml\__init__.py", line 13, in <module>
    from .cyaml import *                               # NOQA
  File "C:\conda\lib\site-packages\ruamel_yaml\cyaml.py", line 5, in <module>
    from ruamel_yaml.ext._ruamel_yaml import CParser, CEmitter
  File "ruamel_yaml\ext\_ruamel_yaml.pyx", line 18, in init ruamel_yaml.ext._ruamel_yaml (ruamel_yaml/ext/_ruamel_yaml.c:23219)
  File "C:\conda\lib\site-packages\ruamel_yaml\reader.py", line 58, in <module>
    class Reader(object):
  File "C:\conda\lib\site-packages\ruamel_yaml\reader.py", line 152, in Reader
    u'[^\x09\x0A\x0D\x20-\x7E\x85\xA0-\uD7FF\uE000-\uFFFD]')
  File "C:\conda\lib\re.py", line 194, in compile
    return _compile(pattern, flags)
  File "C:\conda\lib\re.py", line 249, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\conda\lib\sre_compile.py", line 576, in compile
    code = _code(p, flags)
  File "C:\conda\lib\sre_compile.py", line 561, in _code
    _compile(code, p.data, flags)
  File "C:\conda\lib\sre_compile.py", line 107, in _compile
    _compile_charset(av, flags, code, fixup, fixes)
  File "C:\conda\lib\sre_compile.py", line 232, in _compile_charset
    flags & SRE_FLAG_UNICODE):
  File "C:\conda\lib\sre_compile.py", line 274, in _optimize_charset
    r = range(av[0], av[1]+1)
MemoryError
```
x86 - https://ci.appveyor.com/project/conda-forge/nbexamples-feedstock/build/job/mgoqtm6s7n4rjcpv
```
run_conda_forge_build_setup
Fatal Python error: Can't initialize instance type
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```
x64 - https://ci.appveyor.com/project/conda-forge/nbexamples-feedstock/build/job/dmyx74a54x97sllx
```
run_conda_forge_build_setup
Using Anaconda API: https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications: ..........
# All requested packages already installed.
# packages in environment at C:\conda:
#
conda                     4.1.12                   py27_0    conda-forge
Traceback (most recent call last):
  File "C:\conda\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\conda\lib\site-packages\conda\cli\main.py", line 61, in main
    from conda.cli import conda_argparse
  File "C:\conda\lib\site-packages\conda\cli\conda_argparse.py", line 15, in <module>
    
  File "C:\conda\lib\site-packages\conda\cli\common.py", line 12, in <module>
    
  File "C:\conda\lib\site-packages\conda\config.py", line 475, in <module>
    
  File "C:\conda\lib\site-packages\conda\config.py", line 391, in load_condarc
    
  File "C:\conda\lib\site-packages\conda\config.py", line 129, in load_condarc_
    
  File "C:\conda\lib\site-packages\conda\utils.py", line 296, in yaml_load
    
  File "C:\conda\lib\site-packages\conda\utils.py", line 43, in __call__
    
  File "C:\conda\lib\site-packages\conda\utils.py", line 282, in get_yaml
    
  File "C:\conda\lib\site-packages\ruamel_yaml\__init__.py", line 13, in <module>
    
  File "C:\conda\lib\site-packages\ruamel_yaml\cyaml.py", line 5, in <module>
    
  File "ruamel_yaml\ext\_ruamel_yaml.pyx", line 18, in init ruamel_yaml.ext._ruamel_yaml (ruamel_yaml/ext/_ruamel_yaml.c:23219)
  File "C:\conda\lib\site-packages\ruamel_yaml\reader.py", line 58, in <module>
    
  File "C:\conda\lib\site-packages\ruamel_yaml\reader.py", line 152, in Reader
    
  File "C:\conda\lib\re.py", line 194, in compile
    
  File "C:\conda\lib\re.py", line 249, in _compile
    
  File "C:\conda\lib\sre_compile.py", line 576, in compile
    
  File "C:\conda\lib\sre_compile.py", line 558, in _code
    
  File "C:\conda\lib\sre_compile.py", line 536, in _compile_info
    
  File "C:\conda\lib\sre_compile.py", line 232, in _compile_charset
    
  File "C:\conda\lib\sre_compile.py", line 274, in _optimize_charset
    
MemoryError
```
x86 - https://ci.appveyor.com/project/conda-forge/pandas-feedstock/build/job/prq7voio6itw1cmm
```
run_conda_forge_build_setup
Traceback (most recent call last):
  File "C:\conda\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\conda\lib\site-packages\conda\cli\main.py", line 61, in main
    from conda.cli import conda_argparse
  File "C:\conda\lib\site-packages\conda\cli\conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "C:\conda\lib\site-packages\conda\cli\common.py", line 12, in <module>
    from ..config import (envs_dirs, default_prefix, platform, update_dependencies,
  File "C:\conda\lib\site-packages\conda\config.py", line 475, in <module>
    load_condarc(rc_path)
  File "C:\conda\lib\site-packages\conda\config.py", line 391, in load_condarc
    rc = load_condarc_(path)
  File "C:\conda\lib\site-packages\conda\config.py", line 129, in load_condarc_
    return yaml_load(f) or {}
  File "C:\conda\lib\site-packages\conda\utils.py", line 296, in yaml_load
    yaml = get_yaml()
  File "C:\conda\lib\site-packages\conda\utils.py", line 43, in __call__
    value = self.func(*args, **kw)
  File "C:\conda\lib\site-packages\conda\utils.py", line 282, in get_yaml
    import ruamel_yaml as yaml
  File "C:\conda\lib\site-packages\ruamel_yaml\__init__.py", line 13, in <module>
    from .cyaml import *                               # NOQA
  File "C:\conda\lib\site-packages\ruamel_yaml\cyaml.py", line 5, in <module>
    from ruamel_yaml.ext._ruamel_yaml import CParser, CEmitter
  File "ruamel_yaml\ext\_ruamel_yaml.pyx", line 18, in init ruamel_yaml.ext._ruamel_yaml (ruamel_yaml/ext/_ruamel_yaml.c:23219)
  File "C:\conda\lib\site-packages\ruamel_yaml\reader.py", line 58, in <module>
    class Reader(object):
  File "C:\conda\lib\site-packages\ruamel_yaml\reader.py", line 152, in Reader
    u'[^\x09\x0A\x0D\x20-\x7E\x85\xA0-\uD7FF\uE000-\uFFFD]')
  File "C:\conda\lib\re.py", line 194, in compile
    return _compile(pattern, flags)
  File "C:\conda\lib\re.py", line 249, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\conda\lib\sre_compile.py", line 576, in compile
    code = _code(p, flags)
  File "C:\conda\lib\sre_compile.py", line 558, in _code
    _compile_info(code, p, flags)
  File "C:\conda\lib\sre_compile.py", line 536, in _compile_info
    _compile_charset(charset, flags, code)
  File "C:\conda\lib\sre_compile.py", line 232, in _compile_charset
    flags & SRE_FLAG_UNICODE):
  File "C:\conda\lib\sre_compile.py", line 274, in _optimize_charset
    r = range(av[0], av[1]+1)
MemoryError
```
x64 - https://ci.appveyor.com/project/conda-forge/pandas-feedstock/build/job/o188b8xmgcong0q7
```
run_conda_forge_build_setup
Traceback (most recent call last):
  File "C:\conda\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\conda\lib\site-packages\conda\cli\main.py", line 61, in main
    from conda.cli import conda_argparse
  File "C:\conda\lib\site-packages\conda\cli\conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "C:\conda\lib\site-packages\conda\cli\common.py", line 12, in <module>
    from ..config import (envs_dirs, default_prefix, platform, update_dependencies,
  File "C:\conda\lib\site-packages\conda\config.py", line 17, in <module>
    from .compat import urlparse, string_types
  File "C:\conda\lib\site-packages\conda\compat.py", line 42, in <module>
    from urllib import quote as urllib_quote
MemoryError
```
</details>

and the offending line is in the [conda-forge-build-setup-feedstock](https://github.com/conda-forge/conda-forge-build-setup-feedstock/blob/master/recipe/run_conda_forge_build_setup_win.bat#L12). It takes approximatly 5 minutes until the `Fetching metadata .....` process starts. I suspect there is something wrong in some meta-requirements/data field in some win-py27 package. 

Collecting the packages from the `defaults` channel works. See for example https://github.com/conda-forge/iteration_utilities-feedstock/pull/5

**Comment by jakirkham** [comment]
That's interesting info. Though I don't think I agree with your conclusion.

The main reason for disagreement is we also use `conda-forge-build-setup` in staged-recipes as well, but do not experience the same slow down. This points to something else being the cause of the issue. Given you have narrowed it down to the `conda install` line and we are seeing references to `ctypes`, I'm a bit curious if something funny is happening with `pycosat`. Not totally sure what it is yet, but that seems like the right place to look.

**Comment by jakirkham** [comment]
It's starting to look like `ruamel_yaml` could be playing a part. `staged-recipes` has a newer version of it than the feedstocks as it continues to use it from `defaults`. Unfortunately we have had trouble getting any clear idea of how to build new versions of `ruamel_yaml`. ( https://github.com/conda-forge/ruamel_yaml-feedstock/issues/2 )

**Comment by MSeifert04** [comment]
But why does it work if I just do the one line from the `conda-forge-build-setup` before adding the `conda-forge` channel?

Note: `ruamel_yaml` and `ctypes` are just more likely to run out of memory than other tasks. I think the reason is somewhere else. But I'm really guessing here.

**Comment by jakirkham** [comment]
Maybe. Really all we can do is systematically eliminate problems until we are left with the source of the issue. Right now it looks like `ruamel_yaml` is part of the problem. So eliminating that variable should help.

**Comment by jakirkham** [comment]
As PR ( https://github.com/conda-forge/conda-smithy/pull/370 ) works, I'm rolling that out as `v1.5.0`. I would love to better understand the issues behind this problem when I and/or others have more time to investigate. However, for now I'm happy enough to take the fix we have and go forward with it.

**Comment by jakirkham** [comment]
Try re-rendering with `1.5.0` or `1.5.1`. The re-renderings are the same, but there were some linter improvements in the latter.

**Comment by kalefranz** [comment]
Just stumbling into this issue. Will help with https://github.com/conda-forge/ruamel_yaml-feedstock/pull/3

Does anyone know what the actual memory limit is on these Appveyor boxes? Just curious.

**Comment by MSeifert04** [comment]
The only information ([1] don't know if it's reliable) is that their virtual machines have 4GB RAM.

But I think it's just a never-ending `while`-loop somewhere that causes the memoryerror.

[1] : https://www.appveyor.com/blog/2016/07/16/migration-to-rackspace/

**Comment by jakirkham** [comment]
This appears to have resurfaced.

xref: https://ci.appveyor.com/project/conda-forge/libssh2-feedstock/build/1.0.4/job/xcra9t5bevmcj3d8#L181

**Comment by jakirkham** [comment]
AFAICT this is a product of using `conda` 4.1. While we don't know the exact cause, we know that `conda` 4.2 does not encounter this problem. The reason `conda` 4.1 is being picked up is because we have the old `ruamel_yaml` (0.11.7) in our channel, but have not been able to upgrade to (0.11.14). The solver tries to prefer our channel, but gets confused between upgrading `conda` and downgrading `ruamel_yaml`. Recently it seems to prefer downgrading to make sure channel priority is preserved so that both `conda` and `ruamel_yaml` come from `conda-forge`.

**Comment by shadowwalkersb** [comment]
> This appears to have resurfaced.
> 
> xref: https://ci.appveyor.com/project/conda-forge/libssh2-feedstock/build/1.0.4/job/xcra9t5bevmcj3d8#L120

This build seems to be from 3 months ago, if I am not mistaken.

**Comment by jakirkham** [comment]
Ok, sorry for the miscommunication. Closing...
