### ISSUE TITLE
AttributeError: 'Dist' object has no attribute 'fn' from rerender

### ISSUE THREAD

**Issue by asmeurer** [conda-forge/conda-smithy#435]
I tried to rerender [sphinxcontrib-autoprogram](https://github.com/conda-forge/sphinxcontrib-autoprogram-feedstock) and got this error:

```
$conda smithy rerender
No circle token.  Create a token at https://circleci.com/account/api and
put it in ~/.conda-smithy/circle.token
No appveyor token. Create a token at https://ci.appveyor.com/api-token and
Put one in ~/.conda-smithy/appveyor.token
No anaconda token. Create a token via
  anaconda auth --create --name conda-smithy --scopes "repos conda api"
and put it in ~/.conda-smithy/anaconda.token
Fetching package metadata .................
Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda3/bin/conda-smithy", line 6, in <module>
    sys.exit(conda_smithy.cli.main())
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/conda_smithy/cli.py", line 289, in main
    args.subcommand_func(args)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/conda_smithy/cli.py", line 200, in __call__
    configure_feedstock.main(args.feedstock_directory)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 644, in main
    render_run_docker_build(env, config, forge_dir)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 77, in render_run_docker_build
    forge_config.get('channels', {}).get('sources', tuple())
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 565, in compute_build_matrix
    mtx = special_case_version_matrix(meta, index)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/conda_build_all/version_matrix.py", line 212, in special_case_version_matrix
    py_vn = minor_vn(index[python_pkg.fn]['version'])
AttributeError: 'Dist' object has no attribute 'fn'
```

**Comment by jakirkham** [comment]
Also this [example]( https://github.com/conda-forge/tzlocal-feedstock/pull/4#issuecomment-273116940 ) cropped up elsewhere. Looks like it is the same issue.

cc @synapticarbors

**Comment by jakirkham** [comment]
What does `conda list -n root` show, @asmeurer?

**Comment by jakirkham** [comment]
Should add this is pretty strange as a [couple lines earlier]( https://github.com/SciTools/conda-build-all/blob/v1.0.1/conda_build_all/version_matrix.py#L202 ) it accesses `fn`. Since the traceback doesn't point there, we must have `fn`. However it is magically gone a few lines later.

**Comment by jakirkham** [comment]
FWICT this is a [`conda-build-all`]( https://github.com/SciTools/conda-build-all ) issue. Am going to move this over there and see what they think.

**Comment by jakirkham** [comment]
This issue was moved to SciTools/conda-build-all#76
