### ISSUE TITLE
smithy fails with attribute error

### ISSUE THREAD

**Issue by moorepants** [conda-forge/conda-smithy#449]
```
moorepants@garuda:yeadon-feedstock(rerender)$ conda smithy rerender
No circle token.  Create a token at https://circleci.com/account/api and
put it in ~/.conda-smithy/circle.token
No appveyor token. Create a token at https://ci.appveyor.com/api-token and
Put one in ~/.conda-smithy/appveyor.token
No anaconda token. Create a token via
  anaconda auth --create --name conda-smithy --scopes "repos conda api"
and put it in ~/.conda-smithy/anaconda.token
Fetching package metadata .................
Traceback (most recent call last):
  File "/home/moorepants/miniconda3/bin/conda-smithy", line 6, in <module>
    sys.exit(conda_smithy.cli.main())
  File "/home/moorepants/miniconda3/lib/python3.5/site-packages/conda_smithy/cli.py", line 289, in main
    args.subcommand_func(args)
  File "/home/moorepants/miniconda3/lib/python3.5/site-packages/conda_smithy/cli.py", line 200, in __call__
    configure_feedstock.main(args.feedstock_directory)
  File "/home/moorepants/miniconda3/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 644, in main
    render_run_docker_build(env, config, forge_dir)
  File "/home/moorepants/miniconda3/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 77, in render_run_docker_build
    forge_config.get('channels', {}).get('sources', tuple())
  File "/home/moorepants/miniconda3/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 565, in compute_build_matrix
    mtx = special_case_version_matrix(meta, index)
  File "/home/moorepants/miniconda3/lib/python3.5/site-packages/conda_build_all/version_matrix.py", line 212, in special_case_version_matrix
    py_vn = minor_vn(index[python_pkg.fn]['version'])
AttributeError: 'Dist' object has no attribute 'fn'
```

**Comment by jakirkham** [comment]
Please try downgrading `conda` to 4.2 and retrying. Note `conda-smithy` is not currently compatible with `conda` 4.3.

**Comment by jakirkham** [comment]
Also this particular problem looks like a dup of issue ( https://github.com/conda-forge/conda-smithy/issues/435 ), which was bumped upstream as issue ( https://github.com/SciTools/conda-build-all/issues/76 ).

**Comment by jakirkham** [comment]
Ultimately a fix was added to `conda` in PR ( https://github.com/conda/conda/pull/4424 ). So that particular issue should go away with `conda` 4.3.9. Would be interesting to know if that checks out or not. Based on more recent bug reports this particular issue does appear to be fixed.

That being said, one likely just runs into issue ( https://github.com/conda-forge/conda-smithy/issues/451 ), which appears to be a different compatibility issue with `conda-build-all`.
