### ISSUE TITLE
conda-smithy fails with KeyError

### ISSUE THREAD

**Issue by astrofrog** [conda-forge/conda-smithy#451]
While trying to rerender the qtpy feedstock, I got the following error:

```python
Traceback (most recent call last):
  File "/Users/tom/miniconda3/bin/conda-smithy", line 6, in <module>
    sys.exit(conda_smithy.cli.main())
  File "/Users/tom/miniconda3/lib/python3.5/site-packages/conda_smithy/cli.py", line 289, in main
    args.subcommand_func(args)
  File "/Users/tom/miniconda3/lib/python3.5/site-packages/conda_smithy/cli.py", line 200, in __call__
    configure_feedstock.main(args.feedstock_directory)
  File "/Users/tom/miniconda3/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 644, in main
    render_run_docker_build(env, config, forge_dir)
  File "/Users/tom/miniconda3/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 77, in render_run_docker_build
    forge_config.get('channels', {}).get('sources', tuple())
  File "/Users/tom/miniconda3/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 565, in compute_build_matrix
    mtx = special_case_version_matrix(meta, index)
  File "/Users/tom/miniconda3/lib/python3.5/site-packages/conda_build_all/version_matrix.py", line 212, in special_case_version_matrix
    py_vn = minor_vn(index[python_pkg.fn]['version'])
KeyError: 'python-3.3.0-pro0.tar.bz2'
```

Here are some relevant version numbers:

```
conda                     4.3.9                    py35_0  
conda-build               2.1.0                    py35_0  
conda-build-all           1.0.1                    py35_1    conda-forge
conda-env                 2.6.0                         0  
conda-smithy              2.0.1                    py35_0    conda-forge
conda-verify              2.0.0                    py35_0  
```

**Comment by rth** [comment]
I am experiencing the same issue in the webargs feedstock. This appears to affect only conda-smithy  2.0.1, version 1.7.0 still works. Though I'm not sure if it's a good idea to use v1.7.0 ?

**Comment by jakirkham** [comment]
We don't support `conda` 4.3 yet. Please downgrade to 4.2 and try again.

**Comment by rth** [comment]
Thanks @jakirkham! Downgrading to conda 4.2 fixes it in my case.

**Comment by astrofrog** [comment]
Same here - thanks!

**Comment by jakirkham** [comment]
Could you please raise this issue with [`conda-build-all`]( https://github.com/SciTools/conda-build-all ), @astrofrog? Looks like the problem originates there.
