### ISSUE TITLE
rerender fails with a local file-path in condarc channels

### ISSUE THREAD

**Issue by looooo** [conda-forge/conda-smithy#452]
occured here: https://github.com/conda-forge/vtk-feedstock/pull/23
after removing the local channel re-rendering worked.
```
>>> conda smithy rerender

No circle token.  Create a token at https://circleci.com/account/api and
put it in ~/.conda-smithy/circle.token
No appveyor token. Create a token at https://ci.appveyor.com/api-token and
Put one in ~/.conda-smithy/appveyor.token
No anaconda token. Create a token via
  anaconda auth --create --name conda-smithy --scopes "repos conda api"
and put it in ~/.conda-smithy/anaconda.token
Fetching package metadata .................
Fetching package metadata .................
Fetching package metadata ................Traceback (most recent call last):
  File "~/miniconda3/bin/conda-smithy", line 6, in <module>
    sys.exit(conda_smithy.cli.main())
  File "~/miniconda3/lib/python3.5/site-packages/conda_smithy/cli.py", line 289, in main
    args.subcommand_func(args)
  File "~/miniconda3/lib/python3.5/site-packages/conda_smithy/cli.py", line 200, in __call__
    configure_feedstock.main(args.feedstock_directory)
  File "~/miniconda3/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 646, in main
    render_travis(env, config, forge_dir)
  File "~/miniconda3/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 239, in render_travis
    forge_config.get('channels', {}).get('sources', tuple())
  File "~/miniconda3/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 564, in compute_build_matrix
    platform=meta_config(meta).subdir)
  File "~/miniconda3/lib/python3.5/site-packages/conda/api.py", line 24, in get_index
    index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
  File "~/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 300, in fetch_index
    repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
  File "~/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 300, in <listcomp>
    repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
  File "~/miniconda3/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "~/miniconda3/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "~/miniconda3/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "~/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 75, in func
    res = f(*args, **kwargs)
  File "~/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 117, in fetch_repodata
    timeout=(6.1, 60))
  File "~/miniconda3/lib/python3.5/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "~/miniconda3/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "~/miniconda3/lib/python3.5/site-packages/requests/sessions.py", line 641, in send
    r.content
  File "~/miniconda3/lib/python3.5/site-packages/requests/models.py", line 797, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "~/miniconda3/lib/python3.5/site-packages/requests/models.py", line 730, in generate
    chunk = self.raw.read(chunk_size)
AttributeError: 'FileNotFoundError' object has no attribute 'read'
```

**Comment by jakirkham** [comment]
What version of `conda-smithy` was this with ? Can you reproduce this with any `conda-smithy` version 2.0.0+? If so, please include `conda info` and `conda list -n root`. Also info from your `.condarc` would be very useful.

Note: As of 2.0.0, we don't use `.condarc` so this may just be a `conda` bug.

**Comment by looooo** [comment]
I don't remember the version. Just re-rendered a package and the local branch in condarc doesn't stop the re-rendering anymore for me.
