### ISSUE TITLE
AttributeError with conda-build 3.0.4

### ISSUE THREAD

**Issue by dfm** [conda-forge/conda-smithy#545]
With fresh miniconda installs of Python 2.7 and 3.6, I got the following error when re-rendering:

```
george-feedstock [ master: ✗ ] 104d  conda smithy rerender
No circle token.  Create a token at https://circleci.com/account/api and
put it in ~/.conda-smithy/circle.token
No appveyor token. Create a token at https://ci.appveyor.com/api-token and
Put one in ~/.conda-smithy/appveyor.token
No anaconda token. Create a token via
  anaconda auth --create --name conda-smithy --scopes "repos conda api"
and put it in ~/.conda-smithy/anaconda.token
Traceback (most recent call last):
  File "/Users/dfm/smithy/bin/conda-smithy", line 6, in <module>
    sys.exit(conda_smithy.cli.main())
  File "/Users/dfm/smithy/lib/python2.7/site-packages/conda_smithy/cli.py", line 283, in main
    args.subcommand_func(args)
  File "/Users/dfm/smithy/lib/python2.7/site-packages/conda_smithy/cli.py", line 188, in __call__
    configure_feedstock.main(args.feedstock_directory)
  File "/Users/dfm/smithy/lib/python2.7/site-packages/conda_smithy/configure_feedstock.py", line 709, in main
    render_circle(env, config, forge_dir)
  File "/Users/dfm/smithy/lib/python2.7/site-packages/conda_smithy/configure_feedstock.py", line 72, in render_circle
    with fudge_subdir('linux-64', build_config=meta_config(meta)):
  File "/Users/dfm/smithy/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Users/dfm/smithy/lib/python2.7/site-packages/conda_smithy/configure_feedstock.py", line 223, in fudge_subdir
    build_config.subdir = subdir
AttributeError: can't set attribute
```

This was a clean miniconda install where I had only run `conda install -c conda-forge conda-smithy`.

The output of `conda list -n root` was:

```
# packages in environment at /Users/dfm/smithy:
#
anaconda-client           1.6.3                    py27_0    conda-forge
asn1crypto                0.22.0                   py27_0  
beautifulsoup4            4.6.0                    py27_0  
cffi                      1.10.0                   py27_0  
chardet                   3.0.4                    py27_0  
clyent                    1.2.2                    py27_0  
conda                     4.3.21                   py27_0  
conda-build               3.0.4                    py27_0  
conda-build-all           1.0.4                    py27_1    conda-forge
conda-env                 2.6.0                         0  
conda-smithy              2.3.2                    py27_0    conda-forge
conda-verify              2.0.0                    py27_0    conda-forge
configparser              3.5.0                    py27_0    conda-forge
contextlib2               0.5.5                    py27_0    conda-forge
cryptography              1.8.1                    py27_0  
enum34                    1.1.6                    py27_0  
filelock                  2.0.7                    py27_0  
flake8                    3.3.0                    py27_0    conda-forge
flake8-import-order       0.12                     py27_0    conda-forge
funcsigs                  1.0.2                    py27_0    conda-forge
futures                   3.1.1                    py27_0  
gitdb2                    2.0.0                    py27_0  
gitpython                 2.1.3                    py27_0  
glob2                     0.5                      py27_0    conda-forge
idna                      2.5                      py27_0  
ipaddress                 1.0.18                   py27_0  
jinja2                    2.9.6                    py27_0  
markupsafe                1.0                      py27_0    conda-forge
mccabe                    0.6.1                    py27_0    conda-forge
mock                      2.0.0                    py27_0    conda-forge
openssl                   1.0.2l                        0  
packaging                 16.8                     py27_0  
pbr                       3.1.1                    py27_0    conda-forge
pep8-naming               0.4.1                    py27_0    conda-forge
pip                       9.0.1                    py27_1  
pkginfo                   1.4.1                    py27_0  
pycodestyle               2.3.1                    py27_0    conda-forge
pycosat                   0.6.2                    py27_0  
pycparser                 2.17                     py27_0  
pycrypto                  2.6.1                    py27_1    conda-forge
pyflakes                  1.5.0                    py27_0    conda-forge
pygithub                  1.34                     py27_0    conda-forge
pyjwt                     1.5.2                    py27_0    conda-forge
pyopenssl                 17.0.0                   py27_0  
pyparsing                 2.1.4                    py27_0  
python                    2.7.13                        0  
python-dateutil           2.6.0                    py27_0    conda-forge
pytz                      2017.2                   py27_0    conda-forge
pyyaml                    3.12                     py27_1    conda-forge
readline                  6.2                           2  
requests                  2.14.2                   py27_0  
ruamel.ordereddict        0.4.6                    py27_0    conda-forge
ruamel.yaml               0.15.18                  py27_0    conda-forge
ruamel_yaml               0.11.14                  py27_1  
setuptools                27.2.0                   py27_0  
six                       1.10.0                   py27_0  
smmap2                    2.0.1                    py27_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
typing                    3.6.1                    py27_0    conda-forge
wheel                     0.29.0                   py27_0  
yaml                      0.1.6                         0  
zlib                      1.2.8                         3  
```

I resolved this issue by downgrading `conda-build` to `2.1.17`.

**Comment by jakirkham** [comment]
Thanks @dfm. Unfortunately `conda-smithy` and `conda-build-all` are not compatible with `conda-build` 3 at this time. Downgrading to `conda-build` 2 is the only workaround I can offer at the moment, which you have already found.

There is a question of whether to fix `conda-build-all` for `conda-build` 3 compatibility or whether to drop `conda-build-all` as a dependency of `conda-smithy` and rewrite things to rely on `conda-build` 3 only. This will determine what resolution is reached in `conda-smithy`. Once a solution is reached on that front we can re-evaluate what that means for `conda-smithy`. The discussion about `conda-build-all` and `conda-build` 3 compatibility is in issue ( https://github.com/conda-tools/conda-build-all/issues/89 ).

**Comment by dfm** [comment]
Ah cool. I hadn't tracked down that issue. Downgrading to `conda-build` 2 is absolutely acceptable - I just wanted to get this here to save others some headaches!

**Comment by jakirkham** [comment]
Completely agree. Also this is a discussion we should be having. So thanks for raising it. 😄

**Comment by ericmjl** [comment]
@jakirkham just wondering, is there a fix yet to conda-build 3.x that makes it compatible with conda-smithy? Just thought I'd ask, no pressures - conda-build 2.x is still good for me!

**Comment by jakirkham** [comment]
No updates on `conda-smithy` yet. Though we are working on `conda-build-all`.

**Comment by ericmjl** [comment]
@jakirkham thanks for the update! 👍

**Comment by jakirkham** [comment]
Should add that `conda-build-all` has been fixed. So now `conda-smithy` will need to be fixed for `conda-build` 3 as well.

**Comment by jakirkham** [comment]
`conda-smithy` 3 supports `conda-build` 3 and no longer relies on `conda-build-all`. This was done a while ago. Am just updating for historical record at this point.

Given this, will close the issue as it is resolved. Feel free to raise new issues if other problems arise.
