### ISSUE TITLE
conda smithy init UnicodeDecodeError

### ISSUE THREAD

**Issue by lab4quant** [conda-forge/conda-smithy#546]
Hello, I'm trying to create a new feedstock, and got unicode error, please advise, thanks!

```sh
$ conda smithy init quantlab
Initialized empty Git repository in /Users/jerry/Documents/github/quantlab-feedstock/.git/
Traceback (most recent call last):
  File "/Users/jerry/anaconda/bin/conda-smithy", line 6, in <module>
    sys.exit(conda_smithy.cli.main())
  File "/Users/jerry/anaconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 283, in main
    args.subcommand_func(args)
  File "/Users/jerry/anaconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 100, in __call__
    generate_feedstock_content(feedstock_directory, args.recipe_directory, meta)
  File "/Users/jerry/anaconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 31, in generate_feedstock_content
    configure_feedstock.copytree(source_recipe_dir, target_recipe_dir)
  File "/Users/jerry/anaconda/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 582, in copytree
    copy_file(s, d)
  File "/Users/jerry/anaconda/lib/python3.5/site-packages/conda_smithy/feedstock_io.py", line 80, in copy_file
    for line in fh_src:
  File "/Users/jerry/anaconda/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf7 in position 559: invalid start byte
```

**Comment by lab4quant** [comment]
closing ticket, I thought feedstock is added by this command
