### ISSUE TITLE
register-ci  fails to register to circle-ci with 504 Server Error: GATEWAY_TIMEOUT

### ISSUE THREAD

**Issue by DerThorsten** [conda-forge/conda-smithy#590]
Hi, I am trying to use conda smithy but
```conda smithy register-ci --user DerThorsten --feedstock_directory ./qpbo-feedstock``` fails with
```
conda smithy register-ci --user DerThorsten --feedstock_directory ./qpbo-feedstock
CI Summary for DerThorsten/qpbo (can take ~30s):
 * DerThorsten/qpbo already enabled on travis-ci
Traceback (most recent call last):
  File "/home/tbeier/miniconda3/bin/conda-smithy", line 6, in <module>
    exit(main())
  File "/home/tbeier/miniconda3/lib/python3.6/site-packages/conda_smithy/cli.py", line 290, in main
    args.subcommand_func(args)
  File "/home/tbeier/miniconda3/lib/python3.6/site-packages/conda_smithy/cli.py", line 169, in __call__
    ci_register.add_project_to_circle(owner, repo)
  File "/home/tbeier/miniconda3/lib/python3.6/site-packages/conda_smithy/ci_register.py", line 95, in add_project_to_circle
    response.raise_for_status()
  File "/home/tbeier/miniconda3/lib/python3.6/site-packages/requests/models.py", line 893, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: GATEWAY_TIMEOUT for url: https://circleci.com/api/v1.1/project/github/derthorsten/qpbo/follow?circle-token=XXXXXXXXXXXXXX
```
(I replaced my token with XXXXXXXXXXXXXX)

Here is the repo with the recipe: https://github.com/DerThorsten/qpbo
In the root folder of this repo I used the following steps before failing 
```conda smithy init recipe ``` 
```conda smithy register-github --user DerThorsten ./qpbo-feedstock```
```conda smithy register-ci --user DerThorsten --feedstock_directory ./qpbo-feedstock```

I also tried to add circle-ci by hand to the qpbo repo but this did not helped.
I triple-checked the API-TOKEN of circle-ci.... 
Any ideas?

Greetings

**Comment by jakirkham** [comment]
Hi Thorsten. 👋 The tokens all live in `~/.conda-smithy`. For CircleCI's token, this should `~/.conda-smithy/circle.token`.

**Comment by h-vetinari** [comment]
circleci is dead; closing as obsolete. Xref #2627
