### ISSUE TITLE
ModuleNotFoundError: conda_build_all

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/conda-smithy#613]
I got a No module named `conda_build_all` after updating to py36. 
```python
christopher@christopher-ubuntu ~/dev/conda-forge/pymongo-feedstock 36 $ conda smithy rerender --commit
Traceback (most recent call last):
  File "/home/christopher/mc/bin/conda-smithy", line 5, in <module>
    from conda_smithy.cli import main
  File "/home/christopher/mc/lib/python3.6/site-packages/conda_smithy/cli.py", line 14, in <module>
    from . import configure_feedstock
  File "/home/christopher/mc/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 48, in <module>
    from conda_build_all.version_matrix import special_case_version_matrix, filter_cases
ModuleNotFoundError: No module named 'conda_build_all'
```
Conda env
```
anaconda-client           1.6.5                      py_0    conda-forge
asn1crypto                0.22.0                   py36_0    conda-forge
asttokens                 1.1.6                      py_0    conda-forge
backports                 1.0                      py36_1    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
beautifulsoup4            4.6.0                    py36_0    conda-forge
blas                      1.1                    openblas    conda-forge
ca-certificates           2017.4.17                     0    conda-forge
certifi                   2017.7.27.1              py36_0    conda-forge
cffi                      1.10.0                   py36_0    conda-forge
chardet                   3.0.4                    py36_0    conda-forge
clyent                    1.2.2                    py36_0    conda-forge
conda                     4.3.29                   py36_0    conda-forge
conda-build               2.1.17                   py36_0    conda-forge
conda-build-all           1.1.1                      py_2    conda-forge
conda-env                 2.6.0                         0    conda-forge
conda-execute             0.8.2                      py_0    conda-forge
conda-smithy              2.4.2                      py_0    conda-forge
conda-verify              2.0.0                    py36_0    conda-forge
contextlib2               0.5.5                    py36_0    conda-forge
cryptography              2.0.3                    py36_0    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
dbus                      1.10.10                       3    conda-forge
decorator                 4.1.2                    py36_0    conda-forge
expat                     2.2.1                         0    conda-forge
filelock                  2.0.6                    py36_0    conda-forge
fire                      0.1.2                      py_0    conda-forge
flake8                    3.5.0                    py36_0    conda-forge
flake8-import-order       0.15                       py_0    conda-forge
fontconfig                2.12.1                        4    conda-forge
freetype                  2.7                           1    conda-forge
funcsigs                  1.0.2                      py_2    conda-forge
gettext                   0.19.7                        1    conda-forge
gitdb                     0.6.4                    py36_1    conda-forge
gitdb2                    2.0.2                    py36_0    conda-forge
github3.py                1.0.0a4                  py36_0    conda-forge
gitpython                 2.1.7                    py36_0    conda-forge
glib                      2.51.4                        0    conda-forge
glob2                     0.5                      py36_0    conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         2    conda-forge
icu                       58.1                          1    conda-forge
idna                      2.6                      py36_1    conda-forge
ipython                   6.2.1                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
jedi                      0.10.2                   py36_0    conda-forge
jinja2                    2.9.6                    py36_0    conda-forge
jpeg                      9b                            0    conda-forge
jsonschema                2.6.0                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
lazyasd                   0.1.3                    py36_0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgfortran               3.0.0                         1  
libiconv                  1.14                          4    conda-forge
libpng                    1.6.28                        0    conda-forge
libxcb                    1.12                          1    conda-forge
libxml2                   2.9.4                         4    conda-forge
markupsafe                1.0                      py36_0    conda-forge
mccabe                    0.6.1                    py36_0    conda-forge
mock                      2.0.0                    py36_0    conda-forge
nbformat                  4.4.0                    py36_0    conda-forge
ncurses                   5.9                          10    conda-forge
nose                      1.3.7                    py36_2    conda-forge
numpy                     1.13.3          py36_blas_openblas_200  [blas_openblas]  conda-forge
openblas                  0.2.19                        2    conda-forge
openssl                   1.0.2l                        0    conda-forge
packaging                 16.8                     py36_0    conda-forge
patchelf                  0.9                           2    conda-forge
pbr                       3.1.1                    py36_0    conda-forge
pcre                      8.39                          0    conda-forge
pep8-naming               0.4.1                    py36_0    conda-forge
pexpect                   4.2.1                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pip                       9.0.1                    py36_0    conda-forge
pkginfo                   1.4.1                    py36_0    conda-forge
ply                       3.10                     py36_0    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
psutil                    5.4.0                    py36_0    conda-forge
ptyprocess                0.5.2                    py36_0    conda-forge
py                        1.5.2                      py_0    conda-forge
pyasn1                    0.3.7                      py_0    conda-forge
pycodestyle               2.3.1                    py36_0    conda-forge
pycosat                   0.6.3                    py36_0    conda-forge
pycparser                 2.18                     py36_0    conda-forge
pycrypto                  2.6.1                    py36_1    conda-forge
pyflakes                  1.6.0                    py36_0    conda-forge
pygithub                  1.34                     py36_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
pyjwt                     1.5.3                      py_0    conda-forge
pymongo                   3.2.2            py36hd828e36_0    lightsource2-tag
pyopenssl                 17.2.0                   py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyqt                      5.6.0                    py36_4    conda-forge
pysocks                   1.6.7                    py36_0    conda-forge
pytest                    3.2.5                    py36_0    conda-forge
python                    3.6.3                         1    conda-forge
python-dateutil           2.6.1                    py36_0    conda-forge
pytz                      2017.3                     py_2    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
qt                        5.6.2                         3    conda-forge
readline                  6.2                           0    conda-forge
requests                  2.18.4                   py36_1    conda-forge
ruamel.yaml               0.15.34                  py36_0    conda-forge
ruamel_yaml               0.11.14                  py36_0    conda-forge
setproctitle              1.1.10                   py36_0    conda-forge
setuptools                36.6.0                   py36_1    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
smmap                     0.9.0                    py36_1    conda-forge
smmap2                    2.0.3                    py36_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
tk                        8.5.19                        1    conda-forge
tornado                   4.5.2                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
typing                    3.6.2                    py36_0    conda-forge
uritemplate.py            3.0.2                    py36_0    conda-forge
urllib3                   1.22                     py36_0    conda-forge
wcwidth                   0.1.7                    py36_0    conda-forge
wheel                     0.30.0                     py_1    conda-forge
xonda                     0.2                       <pip>
xonsh                     0.5.12                   py36_2    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.2                         0    conda-forge
yaml                      0.1.6                         0    conda-forge
zlib                      1.2.11                        0    conda-forge
```
Thoughts?

**Comment by isuruf** [comment]
Try removing `conda-build-all` (and all the noarch packages) and reinstalling. This can happen when you upgrade conda from 4.2 to 4.3 and at the same time you install noarch packages

**Comment by CJ-Wright** [comment]
How can I tell the noarch packages?

**Comment by isuruf** [comment]
packages which build numbers like `py_2` instead of `py36_2`

**Comment by CJ-Wright** [comment]
ah ok
It seems to work (it hasn't crashed yet, and it usually doesn't get this far) although I just uninstalled/installed `conda-build-all`.
