### ISSUE TITLE
Conda smithy incompatible with conda 4.4 (missing conda.config)

### ISSUE THREAD

**Issue by jcb91** [conda-forge/conda-smithy#630]
Attempting to rerender a local copy of [conda-forge/jupyter_nbextensions_configurator-feedstock](https://github.com/conda-forge/jupyter_nbextensions_configurator-feedstock)

```bash session
~/workspace/feedstocks/jupyter_nbextensions_configurator-feedstock $ conda smithy rerender
Traceback (most recent call last):
  File "/home/josh/miniconda3/bin/conda-smithy", line 6, in <module>
    from conda_smithy.cli import main
  File "/home/josh/miniconda3/lib/python3.5/site-packages/conda_smithy/cli.py", line 14, in <module>
    from . import configure_feedstock
  File "/home/josh/miniconda3/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 13, in <module>
    import conda.config
ImportError: No module named 'conda.config'
```

I guess what's happened here is that the removal of the conda.config module from version 4.4.0 onwards has caused conda-smithy to bork?

```pycon
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import conda
>>> print(conda.__version__)
4.4.2
>>> import conda.config
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'conda.config'
```

env: <details>
```
$ conda list
# packages in environment:
#
anaconda-client           1.6.2                    py35_0  
beautifulsoup4            4.5.3                    py35_0  
bleach                    1.5.0                    py35_0  
ca-certificates           2017.08.26           h1d4fec5_0  
cffi                      1.9.1                    py35_0  
chardet                   2.3.0                    py35_0  
clyent                    1.2.2                    py35_0  
conda                     4.4.2                    py35_0  
conda-build               3.2.0                    py35_0  
conda-build-all           1.1.3                      py_0    conda-forge
conda-env                 2.6.0                h36134e3_1  
conda-smithy              2.4.4                      py_0    conda-forge
conda-verify              2.0.0                    py35_0  
cryptography              1.7.1                    py35_0  
decorator                 4.1.2                    py35_0  
entrypoints               0.2.3                    py35_0  
filelock                  2.0.7                    py35_0  
flake8                    2.5.1                    py35_0  
gitdb2                    2.0.0                    py35_0  
gitpython                 2.1.1                    py35_0  
glob2                     0.6              py35hff66265_0  
html5lib                  0.9999999                py35_0  
idna                      2.2                      py35_0  
ipython                   6.1.0                    py35_0  
ipython_genutils          0.2.0                    py35_0  
jedi                      0.10.2                   py35_2  
jinja2                    2.9.5                    py35_0  
jsonschema                2.6.0                    py35_0  
libffi                    3.2.1                         1  
libgcc-ng                 7.2.0                h7cc24e2_2  
libsodium                 1.0.10                        0  
markupsafe                0.23                     py35_2  
mccabe                    0.3.1                    py35_0  
mistune                   0.7.4                    py35_0  
mock                      2.0.0                    py35_0  
openssl                   1.0.2n               hb7f436b_0  
pandocfilters             1.4.2                    py35_0  
patchelf                  0.9                           0  
path.py                   10.3.1                   py35_0  
pbr                       1.10.0                   py35_0  
pep8                      1.7.0                    py35_0  
pexpect                   4.2.1                    py35_0  
pickleshare               0.7.4                    py35_0  
pip                       8.1.2                    py35_0  
pkginfo                   1.4.1                    py35_0  
pluggy                    0.5.2                      py_0    conda-forge
prompt_toolkit            1.0.15                   py35_0  
ptyprocess                0.5.2                    py35_0  
py                        1.4.34                   py35_0  
pyasn1                    0.1.9                    py35_0  
pycosat                   0.6.3            py35h6b6bb97_0  
pycparser                 2.17                     py35_0  
pycrypto                  2.6.1                    py35_4  
pyflakes                  1.5.0                    py35_0  
pygithub                  1.29                     py35_0    conda-forge
pygments                  2.2.0                    py35_0  
pyopenssl                 16.2.0                   py35_0  
python                    3.5.2                         0  
python-dateutil           2.6.0                    py35_0  
pytz                      2016.10                  py35_0  
pyyaml                    3.12                     py35_0  
pyzmq                     16.0.2                   py35_0  
readline                  6.2                           2  
requests                  2.14.2                   py35_0  
ruamel.yaml               0.13.14                  py35_0    conda-forge
ruamel_yaml               0.11.14                  py35_0  
setuptools                27.2.0                   py35_0  
simplegeneric             0.8.1                    py35_1  
six                       1.10.0                   py35_0  
smmap2                    2.0.1                    py35_0  
sqlite                    3.13.0                        0  
terminado                 0.6                      py35_0  
testpath                  0.3.1                    py35_0  
tk                        8.5.18                        0  
tornado                   4.5.2                    py35_0  
tox                       2.8.2                      py_0    conda-forge
traitlets                 4.3.2                    py35_0  
virtualenv                15.1.0                   py35_0  
wcwidth                   0.1.7                    py35_0  
wheel                     0.29.0                   py35_0  
xz                        5.2.2                         0  
yaml                      0.1.6                         0  
zeromq                    4.1.5                         0  
zlib                      1.2.8                         3 
```
</details>

**Comment by pmlandwehr** [comment]
Just confirming this issue for myself as well.

**Comment by jakirkham** [comment]
Yep, `conda-smithy` does not yet support `conda` 4.4. Only `conda` 4.3 at present.

**Comment by guyer** [comment]
`conda-smithy`'s recipe should enforce this restriction. Here's how I got `conda` 4.4.x in the first place:
```
$ conda update conda-smithy
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /Users/guyer/anaconda:

The following packages will be UPDATED:

    conda:     4.3.27-py27h94ab009_0           --> 4.4.8-py27_0        
    pycosat:   0.6.1-py27_0          <unknown> --> 0.6.3-py27h6c51c7e_0

The following packages will be SUPERSEDED by a higher-priority channel:

    conda-env: 2.6.0-0                         --> 2.6.0-h36134e3_0    

Proceed ([y]/n)? 

conda-env-2.6. 100% |#######################################################| Time: 0:00:00   1.29 MB/s
pycosat-0.6.3- 100% |#######################################################| Time: 0:00:00   4.41 MB/s
conda-4.4.8-py 100% |#######################################################| Time: 0:00:00   2.38 MB/s
```

**Comment by jakirkham** [comment]
Even if we added such a constraint, `conda` would just install an older version of `conda-smithy` that doesn’t have the constraint.

**Comment by jakirkham** [comment]
Just tested this with `conda-smithy` 3 (which is not yet prod ready, but very close) and this issue seems to be resolved. If I had to guess, this is likely due to @msarahan's heroic efforts in PR ( https://github.com/conda-forge/conda-smithy/pull/625 ). Going to go ahead and close this out.

**Comment by jakirkham** [comment]
cc @kalefranz (for awareness)

**Comment by Aya-S** [comment]
I'm having this issue with conda 4.7.12

**Comment by stuertz** [comment]
Workaround use no longer a py27 env, but eg a py37 env:
```
> conda create -n smithy python=3.7 
> conda activate smithy
> conda install conda-build conda-smithy  
> conda smithy rerender
```
