### ISSUE TITLE
Skipping all platforms fail in rendering readme

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-smithy#653]
```
Traceback (most recent call last):
  File "/home/isuru/miniconda3/bin/conda-smithy", line 11, in <module>
    load_entry_point('conda-smithy==2.4.6.dev57', 'console_scripts', 'conda-smithy')()
  File "/home/isuru/projects/conda-smithy/conda_smithy/cli.py", line 253, in main
    args.subcommand_func(args)
  File "/home/isuru/projects/conda-smithy/conda_smithy/cli.py", line 194, in __call__
    no_check_uptodate=args.no_check_uptodate, commit=args.commit)
  File "/home/isuru/projects/conda-smithy/conda_smithy/configure_feedstock.py", line 691, in main
    render_README(env, config, forge_dir)
  File "/home/isuru/projects/conda-smithy/conda_smithy/configure_feedstock.py", line 508, in render_README
    bypass_env_check=True)[0][0]
IndexError: list index out of range
```
cc @msarahan

**Comment by isuruf** [comment]
Skipping your host platform, (linux-64 for me), would fail the rerendering of readme.

**Comment by msarahan** [comment]
Thanks for figuring out this edge case.  I'll look into it.
