### ISSUE TITLE
Rerender Attribute Error

### ISSUE THREAD

**Issue by scopatz** [conda-forge/conda-smithy#680]
When I try to rerender the openmc-feedstock locally I see, 

```sh
scopatz@artemis ~/feedstocks/openmc v0.10.0 $ conda smithy rerender -c auto
WARNING: attribute CONDA_NPY is deprecated and will be removed in conda-build 4.0.  Please update your code - file issues on the conda-build issue tracker if you need help.
WARNING conda_build.config:func_wrapper(170): WARNING: attribute CONDA_NPY is deprecated and will be removed in conda-build 4.0.  Please update your code - file issues on the conda-build issue tracker if you need help.
WARNING: attribute CONDA_PY is deprecated and will be removed in conda-build 4.0.  Please update your code - file issues on the conda-build issue tracker if you need help.
WARNING conda_build.config:func_wrapper(170): WARNING: attribute CONDA_PY is deprecated and will be removed in conda-build 4.0.  Please update your code - file issues on the conda-build issue tracker if you need help.
Traceback (most recent call last):
  File "/home/scopatz/miniconda/bin/conda-smithy", line 6, in <module>
    exit(main())
  File "/home/scopatz/miniconda/lib/python3.6/site-packages/conda_smithy/cli.py", line 290, in main
    args.subcommand_func(args)
  File "/home/scopatz/miniconda/lib/python3.6/site-packages/conda_smithy/cli.py", line 194, in __call__
    configure_feedstock.main(args.feedstock_directory)
  File "/home/scopatz/miniconda/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 722, in main
    render_circle(env, config, forge_dir)
  File "/home/scopatz/miniconda/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 72, in render_circle
    with fudge_subdir('linux-64', build_config=meta_config(meta)):
  File "/home/scopatz/miniconda/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/scopatz/miniconda/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 221, in fudge_subdir
    build_config.subdir = subdir
AttributeError: can't set attribute
```

I believe that I am on the most recent version of these packages:

```sh
scopatz@artemis ~/feedstocks/openmc v0.10.0 $ conda list conda-
# packages in environment at /home/scopatz/miniconda:
#
anaconda-client           1.6.5                      py_0    conda-forge
conda-build               3.4.2                    py36_0    conda-forge
conda-build-all           1.1.3                      py_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
conda-smithy              2.4.5                      py_1    conda-forge
conda-verify              2.0.0                    py36_0    conda-forge
```

I have also notices the "please rerender" hasn't worked, perhaps because of this. Any ideas?

**Comment by isuruf** [comment]
Needs `conda-build 2.x` `conda-smithy==2.4.5` has a version constraint on conda-build, but it's not honored.

**Comment by isuruf** [comment]
Can you open an issue in conda issue tracker since `conda-smithy==2.4.5=py_1` and `conda-build=3.4.2` clearly shouldn't exist in the same environment?

**Comment by scopatz** [comment]
Thanks @isuruf this seems to work once I downgraded.  Do you want me to open an issue on the conda issue tracker or the conda-build issue tracker?

**Comment by scopatz** [comment]
or the conda-build-feedstock?

**Comment by isuruf** [comment]
conda issue tracker, since this seems to be a conda solver issue

**Comment by jakirkham** [comment]
Honestly have thought about just shipping a Docker image with a working `conda-smithy` install. Kind of heavy weight, but reliability in these matters is nice.
