### ISSUE TITLE
Improperly wrapped text causes linter crash

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#727]
Ran into an issue with [this recipe]( https://github.com/conda-forge/staged-recipes/blob/73081829cef5d649977bf9f9c561bba00d8fec38/quest/meta.yaml ). Namely it has some issues with the lack of text wrapping. Ideally this should be a lint error and not an exception that brings the linter to a halt. That said, this one is a little tricky.

<details>
<summary>Example:</summary>

```python
$ conda smithy recipe-lint quest/
Traceback (most recent call last):
  File "/Users/kirkhamj/miniforge/bin/conda-smithy", line 11, in <module>
    load_entry_point('conda-smithy', 'console_scripts', 'conda-smithy')()
  File "/Users/kirkhamj/Developer/Conda/conda-forge/conda-smithy/conda_smithy/cli.py", line 250, in main
    args.subcommand_func(args)
  File "/Users/kirkhamj/Developer/Conda/conda-forge/conda-smithy/conda_smithy/cli.py", line 209, in __call__
    lint = lint_recipe.main(os.path.join(recipe), conda_forge=args.conda_forge)
  File "/Users/kirkhamj/Developer/Conda/conda-forge/conda-smithy/conda_smithy/lint_recipe.py", line 352, in main
    meta = ruamel.yaml.load(content, ruamel.yaml.RoundTripLoader)
  File "/Users/kirkhamj/miniforge/lib/python3.6/site-packages/ruamel/yaml/main.py", line 639, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "/Users/kirkhamj/miniforge/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 102, in get_single_data
    node = self.composer.get_single_node()
  File "/Users/kirkhamj/miniforge/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 75, in get_single_node
    document = self.compose_document()
  File "/Users/kirkhamj/miniforge/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 96, in compose_document
    node = self.compose_node(None, None)
  File "/Users/kirkhamj/miniforge/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/kirkhamj/miniforge/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Users/kirkhamj/miniforge/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/kirkhamj/miniforge/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Users/kirkhamj/miniforge/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 106, in compose_node
    if self.parser.check_event(AliasEvent):
  File "/Users/kirkhamj/miniforge/lib/python3.6/site-packages/ruamel/yaml/parser.py", line 144, in check_event
    self.current_event = self.state()
  File "/Users/kirkhamj/miniforge/lib/python3.6/site-packages/ruamel/yaml/parser.py", line 572, in parse_block_mapping_value
    if self.scanner.check_token(ValueToken):
  File "/Users/kirkhamj/miniforge/lib/python3.6/site-packages/ruamel/yaml/scanner.py", line 1620, in check_token
    self._gather_comments()
  File "/Users/kirkhamj/miniforge/lib/python3.6/site-packages/ruamel/yaml/scanner.py", line 1662, in _gather_comments
    self.fetch_more_tokens()
  File "/Users/kirkhamj/miniforge/lib/python3.6/site-packages/ruamel/yaml/scanner.py", line 289, in fetch_more_tokens
    return self.fetch_literal()
  File "/Users/kirkhamj/miniforge/lib/python3.6/site-packages/ruamel/yaml/scanner.py", line 677, in fetch_literal
    self.fetch_block_scalar(style='|')
  File "/Users/kirkhamj/miniforge/lib/python3.6/site-packages/ruamel/yaml/scanner.py", line 690, in fetch_block_scalar
    self.tokens.append(self.scan_block_scalar(style))
  File "/Users/kirkhamj/miniforge/lib/python3.6/site-packages/ruamel/yaml/scanner.py", line 1075, in scan_block_scalar
    self.scan_block_scalar_ignored_line(start_mark)
  File "/Users/kirkhamj/miniforge/lib/python3.6/site-packages/ruamel/yaml/scanner.py", line 1225, in scan_block_scalar_ignored_line
    % utf8(ch), self.reader.get_mark())
ruamel.yaml.scanner.ScannerError: while scanning a block scalar
  in "<unicode string>", line 58, column 12:
      summary: | Quest is a python library that ... 
               ^ (line: 58)
expected a comment or a line break, but found 'Q'
  in "<unicode string>", line 58, column 14:
      summary: | Quest is a python library that p ... 
                 ^ (line: 58)
```

</details>

**Comment by jakirkham** [comment]
Have re-run and this is still an issue.
