### ISSUE TITLE
conda smithy rerender -c auto broken?

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/conda-smithy#749]
Something odd seems to be happening with conda smithy in the bot.
The bot has the 3.1.0 version of conda-smithy, but I'm not getting any message during the rerender (normally it said something about it) or a commit.
I'm using the command `conda smithy rerender -c auto`

**Comment by CJ-Wright** [comment]
Traceback.
```python
Traceback (most recent call last):
  File "/home/christopher/mc/bin/conda-smithy", line 6, in <module>
    exit(main())
  File "/home/christopher/mc/lib/python3.6/site-packages/conda_smithy/cli.py", line 238, in main
    args.subcommand_func(args)
  File "/home/christopher/mc/lib/python3.6/site-packages/conda_smithy/cli.py", line 182, in __call__
    exclusive_config_file=args.exclusive_config_file)
  File "/home/christopher/mc/lib/python3.6/site-packages/conda_smithy/configure_feedstock.py", line 796, in main
    raise RuntimeError("Install conda-forge-pinning or edit conda-forge.yml")
RuntimeError: Install conda-forge-pinning or edit conda-forge.yml
```

**Comment by isuruf** [comment]
Install `conda-forge-pinning`. :smile:

**Comment by CJ-Wright** [comment]
yea

**Comment by jakirkham** [comment]
We should add that as a requirement of the `conda-smithy` package though.
