### ISSUE TITLE
Changelog must come before tag?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#752]
Ran into this when trying to generate a patch release with `rever`. Any ideas?

```python
Traceback (most recent call last):
  File "/zopt/conda2/envs/rever/bin/rever", line 3, in <module>
    main()
  File "/zopt/conda2/envs/rever/lib/python3.6/site-packages/rever/main.xsh", line 219, in main
    env_main(args=args)
  File "/zopt/conda2/envs/rever/lib/python3.6/site-packages/rever/main.xsh", line 213, in env_main
    run_activities(ns)
  File "/zopt/conda2/envs/rever/lib/python3.6/site-packages/rever/main.xsh", line 129, in run_activities
    need, done = compute_activities_to_run()
  File "/zopt/conda2/envs/rever/lib/python3.6/site-packages/rever/main.xsh", line 110, in compute_activities_to_run
    a + ' in the $ACTIVITIES list.')
ValueError: changelog is a dependency of tag and must come before tag in the $ACTIVITIES list.
```

cc @scopatz @CJ-Wright

**Comment by CJ-Wright** [comment]
Sorry, my fault. Can you move the `changelog` string in the `$ACTIVITIES` list to the first position?

**Comment by jakirkham** [comment]
No worries. Thanks for the tip. PR ( https://github.com/conda-forge/conda-smithy/pull/753 ) should do this. Could you please check/merge?
