### ISSUE TITLE
404 during feedstock rever release

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#755]
So this is kind of expected as I do weird things like put my forked feedstocks in a separate org. Anyways the feedstock release part of the rever script doesn't work for me. Would it be easy to adjust for my use case or is this an outlandish idea? For the average user it might be reasonable to actually make the fork if it doesn't exist.

```python
Traceback (most recent call last):
  File "/zopt/conda2/envs/rever/lib/python3.6/site-packages/rever/activity.xsh", line 62, in __call__
    self.func(*args, **kwargs)
  File "/zopt/conda2/envs/rever/lib/python3.6/site-packages/rever/activities/conda_forge.xsh", line 146, in _func
    fork_repo = gh.repository(username, feedstock_reponame)
  File "/zopt/conda2/envs/rever/lib/python3.6/site-packages/github3/github.py", line 1490, in repository
    json = self._json(self._get(url), 200)
  File "/zopt/conda2/envs/rever/lib/python3.6/site-packages/github3/models.py", line 156, in _json
    raise exceptions.error_for(response)
github3.exceptions.NotFoundError: 404 Not Found
rewinding to 4de5836d547f30c43a9f731bc43929a8ee6baac6
```

cc @CJ-Wright

**Comment by CJ-Wright** [comment]
@jakirkham has this been fixed?
