### ISSUE TITLE
HTTPError: 403 Client Error: Forbidden for url: https://api.github.com/repos/conda-forge/...-feedstock/hooks

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#773]
Seeing an error like the one below repeatedly at `staged-recipes` during feedstock conversion.

```
CI Summary for conda-forge/numina-feedstock (can take ~30s):
 * conda-forge/numina-feedstock registered on travis-ci
 * conda-forge/numina-feedstock enabled on CircleCI
 * conda-forge/numina-feedstock has been enabled on appveyor
numina-feedstock              : Current setting for skipBranchesWithoutAppveyorYml = False.
numina-feedstock              : Current setting for rollingBuildsOnlyForPullRequests = False.
numina-feedstock              : Current setting for rollingBuilds = False.
Traceback (most recent call last):
  File "/home/travis/miniconda/bin/conda-smithy", line 11, in <module>
    load_entry_point('conda-smithy==3.1.3.dev12', 'console_scripts', 'conda-smithy')()
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_smithy/cli.py", line 238, in main
    args.subcommand_func(args)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_smithy/cli.py", line 157, in __call__
    ci_register.add_conda_forge_webservice_hooks(owner, repo)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_smithy/ci_register.py", line 359, in add_conda_forge_webservice_hooks
    response.raise_for_status()
  File "/home/travis/miniconda/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.github.com/repos/conda-forge/numina-feedstock/hooks
Traceback (most recent call last):
  File ".travis_scripts/create_feedstocks.py", line 170, in <module>
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/home/travis/miniconda/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', u'/tmp/tmp7bIlW7__feedstocks/numina-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1
```

Relevant code below.

https://github.com/conda-forge/conda-smithy/blob/f64713d0fa40ce88f26d30a019c12b478b7f55e3/conda_smithy/ci_register.py#L349-L359

ref: https://travis-ci.org/conda-forge/staged-recipes/builds/379026518#L1055-L1079

**Comment by jakirkham** [comment]
Seems to be followed soon after by a conversion job that fails due to GitHub rate limiting. Have seen this a couple of times now. So maybe this is GitHub not explaining that very well?

ref: https://travis-ci.org/conda-forge/staged-recipes/builds/379028041
