### ISSUE TITLE
Feedstock conversion issue - KeyError: 'id'

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#804]
Running into issues registering repos with Travis CI.

```python
CI Summary for conda-forge/awscli-cwlogs-feedstock (can take ~30s):
 * Travis: checking if there's a syncing already.................... * Travis is being synced by somebody else. Ignoring
 * Travis doesn't know about the repo, syncing (takes a few seconds).Traceback (most recent call last):
  File "/home/travis/miniconda/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_smithy/cli.py", line 244, in main
    args.subcommand_func(args)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_smithy/cli.py", line 148, in __call__
    ci_register.add_project_to_travis(owner, repo)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_smithy/ci_register.py", line 236, in add_project_to_travis
    sync_url = '{}/user/{}/sync'.format(travis_endpoint, user_info['id'])
KeyError: 'id'
Traceback (most recent call last):
  File ".travis_scripts/create_feedstocks.py", line 167, in <module>
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/home/travis/miniconda/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', u'/tmp/tmphX7bDD__feedstocks/awscli-cwlogs-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1
```

ref: https://travis-ci.org/conda-forge/staged-recipes/builds/392555543#L919-L937

**Comment by h-vetinari** [comment]
Travis is dead; closing as obsolete. Xref #2627
