### ISSUE TITLE
Can't run conda-smithy - import errors

### ISSUE THREAD

**Issue by marcelotrevisani** [conda-forge/conda-smithy#817]
I tried to run ``conda-smithy`` and I'm facing this error:

```
Traceback (most recent call last):
  File "/home/trevisani/miniconda3/bin/conda-smithy", line 6, in <module>
    from conda_smithy.cli import main
  File "/home/trevisani/miniconda3/lib/python3.6/site-packages/conda_smithy/cli.py", line 17, in <module>
    from . import lint_recipe
  File "/home/trevisani/miniconda3/lib/python3.6/site-packages/conda_smithy/lint_recipe.py", line 12, in <module>
    import github
  File "/home/trevisani/miniconda3/lib/python3.6/site-packages/github/__init__.py", line 42, in <module>
    from .MainClass import Github, GithubIntegration
  File "/home/trevisani/miniconda3/lib/python3.6/site-packages/github/MainClass.py", line 50, in <module>
    import jwt
ModuleNotFoundError: No module named 'jwt'

```
using:
``conda-smithy 3.1.6-py_0``
``conda 4.5.4``
``conda-build 3.10.9``

**Comment by scopatz** [comment]
Hmm do you not have pyjwt installed?

**Comment by marcelotrevisani** [comment]
@scopatz yes! 
``pyjwt 1.6.1``

**Comment by marcelotrevisani** [comment]
Yes, I was doing exactly that :)

However, I just realized that with ``pyjwt 1.6.1`` does not work with ``conda-smithy``. Do we have to put ``pyjwt 1.6.4`` as a minimum requirement?

**Comment by jakirkham** [comment]
Hmm...the error makes it sound like it doesn't exist though. Is it possible that `conda` left things in an incomplete state at some point? Would it be possible to try `pyjwt 1.6.1` again?

**Comment by marcelotrevisani** [comment]
I downgraded ``pyjwt`` to ``1.6.1`` and it worked at this time... 

I'm going to close this issue then, however I don't know what happened. If anyone have a explanation for that, please share :) 
I would appreciate that

Thanks for the help!
