### ISSUE TITLE
`update-cb3` does not work for ftp GNU packages

### ISSUE THREAD

**Issue by bgruening** [conda-forge/conda-smithy#842]
As discussed here: https://github.com/conda-forge/readline-feedstock/pull/11
```
Traceback (most recent call last):
  File "/home/bag/miniconda3/envs/smithy/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/home/bag/miniconda3/envs/smithy/lib/python3.6/site-packages/conda_smithy/cli.py", line 275, in main
    args.subcommand_func(args)
  File "/home/bag/miniconda3/envs/smithy/lib/python3.6/site-packages/conda_smithy/cli.py", line 237, in __call__
    output_content, messages = update_cb3(recipe_file, cbc)
  File "/home/bag/miniconda3/envs/smithy/lib/python3.6/site-packages/conda_smithy/update_cb3.py", line 163, in update_cb3
    need_f, need_c, need_cxx, need_numpy_pin = get_compilers(url)
  File "/home/bag/miniconda3/envs/smithy/lib/python3.6/site-packages/conda_smithy/update_cb3.py", line 87, in get_compilers
    r = requests.get(url, allow_redirects=True)
  File "/home/bag/miniconda3/envs/smithy/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/bag/miniconda3/envs/smithy/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/bag/miniconda3/envs/smithy/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bag/miniconda3/envs/smithy/lib/python3.6/site-packages/requests/sessions.py", line 616, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/bag/miniconda3/envs/smithy/lib/python3.6/site-packages/requests/sessions.py", line 707, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'ftp://ftp.gnu.org/gnu/readline/readline-7.0.tar.gz'
```

**Comment by CJ-Wright** [comment]
Not relevant, we don't support update-cb3 any more.

**Comment by jakirkham** [comment]
Should we drop that subcommand then?
