### ISSUE TITLE
update-cb3 parsing error

### ISSUE THREAD

**Issue by justcalamari** [conda-forge/conda-smithy#860]
When migrating cyrus-sasl-feedstock, `update-cb3` gives
```
Traceback (most recent call last):
  File "/home/justin/miniconda3/envs/bot/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/home/justin/miniconda3/envs/bot/lib/python3.6/site-packages/conda_smithy/cli.py", line 275, in main
    args.subcommand_func(args)
  File "/home/justin/miniconda3/envs/bot/lib/python3.6/site-packages/conda_smithy/cli.py", line 237, in __call__
    output_content, messages = update_cb3(recipe_file, cbc)
  File "/home/justin/miniconda3/envs/bot/lib/python3.6/site-packages/conda_smithy/update_cb3.py", line 138, in update_cb3
    meta_ = yaml.load(content)
  File "/home/justin/miniconda3/envs/bot/lib/python3.6/site-packages/ruamel/yaml/main.py", line 266, in load
    return constructor.get_single_data()
  File "/home/justin/miniconda3/envs/bot/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 103, in get_single_data
    node = self.composer.get_single_node()
  File "/home/justin/miniconda3/envs/bot/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 75, in get_single_node
    document = self.compose_document()
  File "/home/justin/miniconda3/envs/bot/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 96, in compose_document
    node = self.compose_node(None, None)
  File "/home/justin/miniconda3/envs/bot/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/justin/miniconda3/envs/bot/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/justin/miniconda3/envs/bot/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/justin/miniconda3/envs/bot/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 187, in compose_mapping_node
    while not self.parser.check_event(MappingEndEvent):
  File "/home/justin/miniconda3/envs/bot/lib/python3.6/site-packages/ruamel/yaml/parser.py", line 144, in check_event
    self.current_event = self.state()
  File "/home/justin/miniconda3/envs/bot/lib/python3.6/site-packages/ruamel/yaml/parser.py", line 561, in parse_block_mapping_key
    token.start_mark)
ruamel.yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 11, column 3:
      fn: -.tar.gz
      ^ (line: 11)
expected <block end>, but found ':'
  in "<unicode string>", line 13, column 3:
      : 
      ^ (line: 13)
```
CC @isuruf

**Comment by jakirkham** [comment]
cc @dougalsutherland

**Comment by jakirkham** [comment]
If you have time, @justcalamari, it would help to isolate the problematic commit using [`git bisect`]( https://stackoverflow.com/a/4714297 ). Would give others a bit more information to work with.

**Comment by jakirkham** [comment]
If `fn` is removed, does the problem persist?

**Comment by CJ-Wright** [comment]
Not relevant.
