### ISSUE TITLE
update-cb3: 'str' object is not callable

### ISSUE THREAD

**Issue by justcalamari** [conda-forge/conda-smithy#861]
Running on halide-feedstock
```
Traceback (most recent call last):
  File "/home/justin/miniconda3/envs/bot/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/home/justin/miniconda3/envs/bot/lib/python3.6/site-packages/conda_smithy/cli.py", line 275, in main
    args.subcommand_func(args)
  File "/home/justin/miniconda3/envs/bot/lib/python3.6/site-packages/conda_smithy/cli.py", line 237, in __call__
    output_content, messages = update_cb3(recipe_file, cbc)
  File "/home/justin/miniconda3/envs/bot/lib/python3.6/site-packages/conda_smithy/update_cb3.py", line 136, in update_cb3
    content = render_meta_yaml(content)
  File "/home/justin/miniconda3/envs/bot/lib/python3.6/site-packages/conda_smithy/utils.py", line 49, in render_meta_yaml
    content = env.from_string(text).render(os=mockos, environ=mockos.environ)
  File "/home/justin/miniconda3/envs/bot/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/justin/miniconda3/envs/bot/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/justin/miniconda3/envs/bot/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/justin/miniconda3/envs/bot/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 12, in top-level template code
TypeError: 'str' object is not callable
```
CC @isuruf

**Comment by CJ-Wright** [comment]
Not relevant.
