### ISSUE TITLE
Rerender fails even with --no-check-uptodate with non-standard version string (e.g. source install)

### ISSUE THREAD

**Issue by CAM-Gerlach** [conda-forge/conda-smithy#865]
## The Problem

Installing the latest master from a Github clone following the instructions in the readme (clean all-conda-forge environment, install deps, clone from github, ``python -m pip install .``, ``conda smithy rerender``) and then making any changes to the repository and redoing the last two steps results in a ``conda.exceptions.CondaValueError: Malformed version string`` due to the version check, since ``pip`` produces a non-standard version string (e.g. ``3.1.11+fix.no.newline.g855f23b``) once any modifications are made. Worse, this happens even if ``--no-check-uptodate`` is set, so there is no way to even run ``conda smithy`` in this state despite it not actually requiring the version check, except to manually hack the code to comment it out. This occurs on a Windows 8.1 x64 machine with Anaconda 5.2.0 x64, installed into a brand new clean environment with Python 3,6,6 and all conda-forge packages. 

## The Traceback

```python-traceback
$ conda smithy rerender --no-check-uptodate
Traceback (most recent call last):
  File "c:\anaconda3\envs\conda-smithy-test\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\envs\conda-smithy-test\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\envs\conda-smithy-test\Scripts\conda-smithy.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\envs\conda-smithy-test\lib\site-packages\conda_smithy\cli.py", line 278, in main
    args.subcommand_func(args)
  File "c:\anaconda3\envs\conda-smithy-test\lib\site-packages\conda_smithy\cli.py", line 186, in __call__

    exclusive_config_file=args.exclusive_config_file)
  File "c:\anaconda3\envs\conda-smithy-test\lib\site-packages\conda_smithy\configure_feedstock.py", line
889, in main
    check_version_uptodate(r, "conda-smithy", __version__, error_on_warn)
  File "c:\anaconda3\envs\conda-smithy-test\lib\site-packages\conda_smithy\configure_feedstock.py", line
810, in check_version_uptodate
    elif VersionOrder(installed_version) < VersionOrder(most_recent_version):
  File "c:\anaconda3\envs\conda-smithy-test\lib\site-packages\conda\models\version.py", line 163, in __ne w__
    raise CondaValueError(message + "invalid character(s).")
conda.exceptions.CondaValueError: Malformed version string '3.1.11+fix-no-newline_g855f23b': invalid character(s).
```

## The Proposed Solution

Obviously, it is very silly to fail entirely on a non-essential version check if something with the version string is non-standard, at least when enforcement of said check is manually disabled. Therefore, I propose ``excepting`` the error in ``check_version_uptodate()`` and if ``not error_on_warn`` (i.e. ``--no-check-uptodate``), printing a warning message that the version check failed due to <exception message>, as is currently done if the version is out of date. If that flag is not set, then we can either ``raise`` the ``CondaValueError`` as currently, or raise the ``RuntimeError`` as with an out of date version and print the same warning message as the aforementioned case, for a little more user-friendliness.

I am ready to go ahead with a PR on this, just let me know what you think. Thanks!

**Comment by scopatz** [comment]
Please don't use `pkg_resources` it is a totally broken package that can cause dramatic increases in import time.

**Comment by jakirkham** [comment]
Wonder if `importlib_resources` has something we can use?

**Comment by CAM-Gerlach** [comment]
Sorry for the lack of response, somehow missed this—the modern standard, widely used replacement is [`packaging.version.parse`](https://packaging.pypa.io/en/latest/version.html) from the official PyPA [packaging](https://packaging.pypa.io/) package.
