### ISSUE TITLE
zip field python length does not match zip field vc 

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#868]
Getting the following error when trying to re-render [`llvmdev`]( https://github.com/conda-forge/llvmdev-feedstock ).

```python
Traceback (most recent call last):
  File "/zopt/conda3/bin/conda-smithy", line 11, in <module>
    load_entry_point('conda-smithy', 'console_scripts', 'conda-smithy')()
  File "/Users/kirkhamj/Developer/Conda/conda-forge/conda-smithy/conda_smithy/cli.py", line 278, in main
    args.subcommand_func(args)
  File "/Users/kirkhamj/Developer/Conda/conda-forge/conda-smithy/conda_smithy/cli.py", line 186, in __call__
    exclusive_config_file=args.exclusive_config_file)
  File "/Users/kirkhamj/Developer/Conda/conda-forge/conda-smithy/conda_smithy/configure_feedstock.py", line 923, in main
    render_appveyor(env, config, forge_dir)
  File "/Users/kirkhamj/Developer/Conda/conda-forge/conda-smithy/conda_smithy/configure_feedstock.py", line 702, in render_appveyor
    platform_specific_setup=_appveyor_specific_setup)
  File "/Users/kirkhamj/Developer/Conda/conda-forge/conda-smithy/conda_smithy/configure_feedstock.py", line 440, in _render_ci_provider
    configs.extend(dump_subspace_config_files(metas, forge_dir, platform))
  File "/Users/kirkhamj/Developer/Conda/conda-forge/conda-smithy/conda_smithy/configure_feedstock.py", line 316, in dump_subspace_config_files
    configs, top_level_loop_vars = _collapse_subpackage_variants(metas)
  File "/Users/kirkhamj/Developer/Conda/conda-forge/conda-smithy/conda_smithy/configure_feedstock.py", line 292, in _collapse_subpackage_variants
    'ignore_version', 'ignore_build_only_deps'})
  File "/zopt/conda3/lib/python3.6/site-packages/conda_build/variants.py", line 400, in dict_of_lists_to_list_of_dicts
    for group in _get_zip_groups(dict_of_lists):
  File "/zopt/conda3/lib/python3.6/site-packages/conda_build/variants.py", line 360, in _get_zip_groups
    groups.append(_get_zip_dict_of_lists(combined_variant, group))
  File "/zopt/conda3/lib/python3.6/site-packages/conda_build/variants.py", line 343, in _get_zip_dict_of_lists
    key, combined_variant[key]))
ValueError: zip field python (('3.6', '2.7', '3.5')) length does not match zip field vc (('14', '14')) length.  All zip fields within a group must be the same length.
```

**Comment by isuruf** [comment]
I don't think this is a conda-smithy issue. Does `conda render recipe -m /path/to/config/yaml` work?

**Comment by jakirkham** [comment]
It's weird. This issue was reproducible for me. Then I pinned `python` and it went away. Though now that I've removed the pinning for `python` am able to re-render without issues.

Let's just close it out. Sorry for the noise.
