### ISSUE TITLE
Clarify AZURE_SERVICE_ENDPOINT_NAME name

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#922]
xref: https://github.com/conda-forge/conda-smithy/pull/901#discussion_r226677329

**Comment by hmaarrfk** [comment]
What does this mean? I created my team, my project (`feedstock-builds`), set the environment variables
`AZURE_INSTANCE` to point to my team, but how do I create the "service-endpoint"

I keep getting
```
$ conda smithy register-ci --organization ramonaoptics --feedstock_directory .
                                                                              
CI Summary for ramonaoptics/imageio-feedstock (can take ~30s):
 * ramonaoptics/imageio-feedstock already enabled on travis-ci
 * ramonaoptics/imageio-feedstock enabled on CircleCI
> /home/mark2/miniconda3/lib/python3.7/site-packages/conda_smithy/azure_ci_utils.py(185)repo_registered()
-> bclient: BuildClient = connection.get_client(
(Pdb) c
Traceback (most recent call last):
  File "/home/mark2/miniconda3/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/home/mark2/miniconda3/lib/python3.7/site-packages/conda_smithy/cli.py", line 279, in main
    args.subcommand_func(args)
  File "/home/mark2/miniconda3/lib/python3.7/site-packages/conda_smithy/cli.py", line 157, in __call__
    ci_register.add_project_to_azure(owner, repo)
  File "/home/mark2/miniconda3/lib/python3.7/site-packages/conda_smithy/ci_register.py", line 131, in add_project_to_azure
    azure_ci_utils.register_repo(user, project)
  File "/home/mark2/miniconda3/lib/python3.7/site-packages/conda_smithy/azure_ci_utils.py", line 99, in register_repo
    source_repo = get_repo_reference(project_id, github_org, repo_name)
  File "/home/mark2/miniconda3/lib/python3.7/site-packages/conda_smithy/azure_ci_utils.py", line 69, in get_repo_reference
    service_endpoint = get_service_endpoint(project_id)
  File "/home/mark2/miniconda3/lib/python3.7/site-packages/conda_smithy/azure_ci_utils.py", line 44, in get_service_endpoint
    raise KeyError("Service endpoint not found")
KeyError: 'Service endpoint not found'
```

**Comment by jakirkham** [comment]
I've copied the comment from the diff into the OP as GitHub has trouble following the link for some reason.

**Comment by hmaarrfk** [comment]
Yeah, I had found that comment (once) but it is still a mystery for me....
