### ISSUE TITLE
Client Error: Bad Request for url: https://ci.appveyor.com/api/projects

### ISSUE THREAD

**Issue by mjscosta** [conda-forge/conda-smithy#938]
Error when registering the ci:

```
$ conda smithy register-ci --organization eyeware --feedstock_directory ./lcov-feedstock/
CI Summary for eyeware/lcov-feedstock (can take ~30s):
 * eyeware/lcov-feedstock already enabled on travis-ci
 * eyeware/lcov-feedstock enabled on CircleCI
Traceback (most recent call last):
  File "/opt/conda/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/conda_smithy/cli.py", line 278, in main
    args.subcommand_func(args)
  File "/opt/conda/lib/python3.6/site-packages/conda_smithy/cli.py", line 158, in __call__
    ci_register.add_project_to_appveyor(owner, repo)
  File "/opt/conda/lib/python3.6/site-packages/conda_smithy/ci_register.py", line 136, in add_project_to_appveyor
    response.raise_for_status()
  File "/opt/conda/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://ci.appveyor.com/api/projects
```

Debugging with curl:
```
curl -i -v  https://ci.appveyor.com/api/projects  -H "Authorization: Bearer ***************************"
*   Trying 138.91.141.243...
* Connected to ci.appveyor.com (138.91.141.243) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* error fetching CN from cert:The requested data were not available.
* 	 common name:  (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: 
* 	 start date: Wed, 13 Dec 2017 00:00:00 GMT
* 	 expire date: Sat, 08 Dec 2018 23:59:59 GMT
* 	 issuer: C=GB,ST=Greater Manchester,L=Salford,O=COMODO CA Limited,CN=COMODO RSA Extended Validation Secure Server CA
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> GET /api/projects HTTP/1.1
> Host: ci.appveyor.com
> User-Agent: curl/7.47.0
> Accept: */*
> Authorization: Bearer ***************************
> 
< HTTP/1.1 400 Bad Request
HTTP/1.1 400 Bad Request
< Cache-Control: no-cache
Cache-Control: no-cache
< Pragma: no-cache
Pragma: no-cache
< Content-Type: application/json; charset=utf-8
Content-Type: application/json; charset=utf-8
< Expires: -1
Expires: -1
< X-XSS-Protection: 1; mode=block
X-XSS-Protection: 1; mode=block
< X-Frame-Options: SAMEORIGIN
X-Frame-Options: SAMEORIGIN
< Strict-Transport-Security: max-age=31536000
Strict-Transport-Security: max-age=31536000
< X-Content-Type-Options: nosniff
X-Content-Type-Options: nosniff
< Date: Fri, 16 Nov 2018 11:53:28 GMT
Date: Fri, 16 Nov 2018 11:53:28 GMT
< Content-Length: 62
Content-Length: 62

< 
* Connection #0 to host ci.appveyor.com left intact
{"message":"Value cannot be null.\r\nParameter name: account"}vagrant@vagrant:~$ 
```

For some reason the API is expecting an account parameter:

https://www.appveyor.com/docs/api/
https://www.appveyor.com/docs/api/projects-builds/#get-projects

Any idea of what's going on?

**Comment by isuruf** [comment]
The token needs to be a v1 token instead of a v2 token. You need to select the box after `API key can be generated to access either all user accounts or specific account only:`

**Comment by mjscosta** [comment]
@isuruf thanks, it did fixed it.
Cheers

**Comment by h-vetinari** [comment]
Appveyor is dead; closing as obsolete. Xref #2627
