### ISSUE TITLE
Linter can't handle multi-line commands

### ISSUE THREAD

**Issue by sodre** [conda-forge/conda-smithy#965]
While working on [mongo-tool-feedstock meta.yaml](https://github.com/sodre/mongo-tools-feedstock/blob/add-replay/recipe/meta.yaml) I discovered that a [test.command item spanning multiple lines](https://github.com/sodre/mongo-tools-feedstock/blob/929c70e40977814b36993560c86e3b28c6c53a9d/recipe/meta.yaml#L40-L43)  will break the lint code with the following exception:

```
Traceback (most recent call last):
  File "/opt/conda/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/conda_smithy/cli.py", line 278, in main
    args.subcommand_func(args)
  File "/opt/conda/lib/python3.6/site-packages/conda_smithy/cli.py", line 202, in __call__
    return_hints=True)
  File "/opt/conda/lib/python3.6/site-packages/conda_smithy/lint_recipe.py", line 426, in main
    meta = ruamel.yaml.load(content, ruamel.yaml.RoundTripLoader)
  File "/opt/conda/lib/python3.6/site-packages/ruamel/yaml/main.py", line 935, in load
    return loader._constructor.get_single_data()
  File "/opt/conda/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 106, in get_single_data
    node = self.composer.get_single_node()
  File "/opt/conda/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 78, in get_single_node
    document = self.compose_document()
  File "/opt/conda/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 101, in compose_document
    node = self.compose_node(None, None)
  File "/opt/conda/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 138, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/opt/conda/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 217, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/opt/conda/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 138, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/opt/conda/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 217, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/opt/conda/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 136, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/opt/conda/lib/python3.6/site-packages/ruamel/yaml/composer.py", line 178, in compose_sequence_node
    while not self.parser.check_event(SequenceEndEvent):
  File "/opt/conda/lib/python3.6/site-packages/ruamel/yaml/parser.py", line 141, in check_event
    self.current_event = self.state()
  File "/opt/conda/lib/python3.6/site-packages/ruamel/yaml/parser.py", line 517, in parse_block_sequence_entry
    token.start_mark,
ruamel.yaml.parser.ParserError: while parsing a block collection
  in "<unicode string>", line 29, column 5:
        - bsondump --help
        ^ (line: 29)
expected <block end>, but found '<scalar>'
  in "<unicode string>", line 41, column 7:
          if [ $(sysctl -n hw.ncpu) -ge 2  ... 
          ^ (line: 41)
```

**Comment by mariusvniekerk** [comment]
The exception suggests that what you are passing is not valid yaml.  If you want to have multiline yaml you need to change your script from

```yaml
    - if [ $(nproc) -ge 2 ]; then  # [linux]
      if [ $(sysctl -n hw.ncpu) -ge 2 ]; then  # [osx]
        mongoreplay --help;
      fi  # [not win]
```

to 

```yaml
    - |
      if [ $(nproc) -ge 2 ]; then  # [linux]
      if [ $(sysctl -n hw.ncpu) -ge 2 ]; then  # [osx]
        mongoreplay --help;
      fi  # [not win]
```

**Comment by sodre** [comment]
Thanks @mariusvniekerk, I've since changed the logic but I recall the initial syntax still "building"

Either way, your solution is more elegant!

**Comment by jakirkham** [comment]
Am seeing this issue even with valid YAML. Please see commit ( https://github.com/conda-forge/protobuf-feedstock/pull/143/commits/ef932a827b1ed19daa445590b1823ed281529e32 ). Passing this through a YAML linter returns valid YAML, but `conda-smithy` runs into the same issue Patrick observed above.
