### ISSUE TITLE
Conversion at staged-recipes broken

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#967]
Initially this looks like a dependency issue. AFAICT [`msrest` is installed]( https://travis-ci.org/conda-forge/staged-recipes/builds/468471230#L761 ). So it might be something more subtle like having the wrong version or a broken package. Help looking into this would be appreciated.

```python
Traceback (most recent call last):
  File "/home/travis/miniconda/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_smithy/cli.py", line 279, in main
    args.subcommand_func(args)
  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_smithy/cli.py", line 157, in __call__
    ci_register.add_project_to_azure(owner, repo)
  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_smithy/ci_register.py", line 127, in add_project_to_azure
    from . import azure_ci_utils
  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_smithy/azure_ci_utils.py", line 4, in <module>
    from vsts.vss_connection import VssConnection
  File "/home/travis/miniconda/lib/python3.7/site-packages/vsts/vss_connection.py", line 11, in <module>
    from .location.v4_0.location_client import LocationClient
  File "/home/travis/miniconda/lib/python3.7/site-packages/vsts/location/v4_0/location_client.py", line 10, in <module>
    from ...vss_client import VssClient
  File "/home/travis/miniconda/lib/python3.7/site-packages/vsts/vss_client.py", line 15, in <module>
    from msrest.pipeline import ClientRequest
ImportError: cannot import name 'ClientRequest' from 'msrest.pipeline' (/home/travis/miniconda/lib/python3.7/site-packages/msrest/pipeline/__init__.py)
```

ref: https://travis-ci.org/conda-forge/staged-recipes/builds/468471230#L1120-L1137

**Comment by CJ-Wright** [comment]
the problem is here https://github.com/conda-forge/vsts-python-api-feedstock/pull/4

**Comment by CJ-Wright** [comment]
I think the version is wrong, maybe msrest is overpinned?

**Comment by jakirkham** [comment]
Thanks @CJ-Wright!

**Comment by CJ-Wright** [comment]
I've restarted the build now that the new version of vsts is up

**Comment by jakirkham** [comment]
Thanks. Looks like things are working again. Let’s close this out.
