### ISSUE TITLE
travis-ci.org registration no longer seems to work

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#987]
I think we need to stop using [travis-ci.org]( https://travis-ci.org/ ) and just use [travis-ci.com]( https://travis-ci.com/ ). This is taken from a `staged-recipes` build failure.

```python
Repository registered at github, now call 'conda smithy register-ci'
CI Summary for conda-forge/bullet-feedstock (can take ~30s):
 * Travis: checking if there's a syncing already.
 * Travis repo settings are not writable, syncing (takes a few seconds)..
Traceback (most recent call last):
  File "/home/travis/miniconda/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_smithy/cli.py", line 279, in main
    args.subcommand_func(args)
  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_smithy/cli.py", line 151, in __call__
    ci_register.add_project_to_travis(owner, repo)
  File "/home/travis/miniconda/lib/python3.7/site-packages/conda_smithy/ci_register.py", line 286, in add_project_to_travis
    raise RuntimeError(msg.format(user, project))
RuntimeError: Access denied for the repo conda-forge/bullet-feedstock
Traceback (most recent call last):
  File ".travis_scripts/create_feedstocks.py", line 169, in <module>
    subprocess.check_call(['conda', 'smithy', 'register-ci', '--feedstock_directory', feedstock_dir] + owner_info)
  File "/home/travis/miniconda/lib/python3.7/subprocess.py", line 341, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'smithy', 'register-ci', '--feedstock_directory', '/tmp/tmpddkm5x6q__feedstocks/bullet-feedstock', '--organization', 'conda-forge']' returned non-zero exit status 1.
```

ref: https://travis-ci.org/conda-forge/staged-recipes/builds/478771152#L942-L961

**Comment by jakirkham** [comment]
Closing as this no longer appears to be an issue.
